vega/vega-lite

build/vega-lite-schema.json
src/fielddef.ts

Update docs to hide longitude/latitude type

---

src/compile/axis/assemble.ts
test/compile/axis/assemble.test.ts

Make zindex for axis work again

---

CONTRIBUTING.md

Hi, this is my first PR in this repository. I read at CONTRIBUTE.md that for small fixes would be possible to just create the PR instead of creating the relate ISSUE before. If I have done something wrong, just tell me (:

Fix broken link to site examples gallery at CONTRIBUTE.md

---

examples/compiled/area_horizon.vg.json
src/compile/layoutsize/parse.ts
src/compile/legend/encode.ts
src/compile/mark/mark.ts
src/compile/mark/mixins.ts
src/compile/mark/valueref.ts
src/compile/scale/parse.ts
src/compile/scale/range.ts
src/compile/selection/transforms/nearest.ts
src/compile/unit.ts
src/log.ts
test/compile/mark/bar.test.ts

 Make bar starting point correct when a custom domain that include zero is specified

---

examples/compiled/circle_natural_disasters.vg.json
examples/compiled/layer_bar_annotations.vg.json
src/compile/axis/parse.ts

Zero works for subsequent layers when default angle not specified

---

site/usage/applications.md

A yeoman generator supporting vega, vega-lite and optionally vega-tooltip.
Please:
- Please add new commit(s) when addressing comments, so we can see easily the new changeset (instead of the whole changeset).  

Add generator-veeg

---

examples/compiled/layer_line_co2_concentration.vg.json
src/compile/scale/properties.ts
test/compile/scale/properties.test.ts

Update zero rules to be smart for bar, line, and area

---

test-gallery/main.ts

Please:
- Please add new commit(s) when addressing comments, so we can see easily the new changeset (instead of the whole changeset).  
Fixes error thrown while running `yarn start`.
Missed the rename in this [PR](https://github.com/vega/vega-lite/commit/6ff9f0f87ce7ebf8147cae8e4727b0beee80c76a).

Add missed Variable Rename

---

site/docs/transform/timeunit.md

Please:
- Please add new commit(s) when addressing comments, so we can see easily the new changeset (instead of the whole changeset).  

Fix typo in timeunit.md

---

README.md

A small change to include my name in the help from part of the README.
@kanitw

updated README to include my name as a contributor

---

build/vega-lite-schema.json
examples/specs/histogram_no_spacing.vl.json
site/docs/mark/bar.md
src/compile/mark/bar.ts
src/mark.ts

Allow setting binSpacing instead mark definition block

---

src/log.ts
src/spec.ts

Use rule mark instead for line mark with x2/y2

---

_data/versions.yml
_includes/docs_toc.md
site/usage/applications.md

Adding application documentation links to data.world Chart Builder application/open source project per request from @domoritz in the Slack channel.

Added data.world chart builder to applications documentation

---

src/stack.ts
test/stack.test.ts

Fix https://github.com/vega/vega-lite/issues/3653

Allow log scale with stack (but still show warning)

---

site/docs/composition/layer.md

<details><summary>checklist</summary>
Please:
</details>

docs: fix "example gallery" link in layering docs

---

build/vega-lite-schema.json
src/mark.ts
src/spec.ts

Remove the unnecessary `MarkProperties` interface

---

package.json
src/spec.ts
yarn.lock

Depends on https://github.com/vega/ts-json-schema-generator/issues/24

Define data only once

---

src/compile/axis/parse.ts
src/compile/legend/parse.ts
test/compile/axis/parse.test.ts
test/compile/legend/parse.test.ts

(Fixing old comment in https://github.com/vega/vega-lite/pull/3717#issuecomment-387136239)

Make fieldDef.title produces explicit title for axis/legend

---

CONTRIBUTING.md
site/index.md
src/compile/compile.ts

Updates CONTRIBUTING.md

---

src/compile/mark/mark.ts
src/compile/scale/domain.ts
src/compile/scale/properties.ts
src/compile/unit.ts

Also Remove model.sort()
Fix #3712

Make sort logic reads from conditional fieldDef too

---

src/compile/data/formatparse.ts
src/compile/scale/domain.ts
src/fielddef.ts
src/util.ts
test/compile/data/formatparse.test.ts
test/compile/scale/domain.test.ts

Flatten domain sort. Fixes #3727

---

src/compile/mark/area.ts
src/compile/mark/bar.ts
src/compile/mark/init.ts
src/compile/mark/mixins.ts
src/compile/mark/rect.ts
test/compile/mark/bar.test.ts

Make `bar` support prebinned data

---

_data/examples.json
site/index.md

The teaser is upgraded with more customized visual,  composition and interactive plots!

Improve Gallery

---

build/vega-lite-schema.json
scripts/check-schema.sh
src/axis.ts
src/compositemark/boxplot.ts
src/config.ts
src/data.ts
src/encoding.ts
src/guide.ts
src/mark.ts
src/scale.ts
src/selection.ts
src/sort.ts
src/title.ts
src/transform.ts
src/vega.schema.ts

Fix all docs url to use absolute url

---

build/vega-lite-schema.json
package.json
site/docs/transform/filter.md
src/compile/data/parse.ts
src/predicate.ts
test/predicate.test.ts

Add lt, lte, gt, gte filters

---

src/compile/layoutsize/parse.ts
src/compile/projection/parse.ts
src/compile/unit.ts
test/compile/layoutsize/parse.test.ts

Make config.view.size work with projection

---

_data/examples.json
site/docs/mark/line.md

Also move invalid lines to after overlay as it uses overlay too.

[Docs] Improve line overlay docs

---

build/vega-lite-schema.json
package.json
src/compile/data/assemble.ts
src/compile/data/parse.ts
src/compile/data/sample.ts
src/transform.ts
src/vega.schema.ts
test/compile/data/parse.test.ts
test/compile/data/sample.test.ts
yarn.lock

Add Sample Transform

---

build/vega-lite-schema.json
src/bin.ts
test/compile/data/bin.test.ts

Fixes [#3817](https://github.com/vega/vega-lite/issues/3817).

Add anchor to BaseBin

---

build/vega-lite-schema.json
src/compile/data/assemble.ts
src/compile/data/impute.ts
src/compile/data/parse.ts
src/transform.ts
src/vega.schema.ts
test/compile/data/impute.test.ts
test/compile/data/parse.test.ts

Will make separate PRs for 
- Decoupling from stack 
- Impute Transform docs

Add Impute Transform

---

build/vega-lite-schema.json
examples/compiled/layer_cumulative_histogram.vg.json
src/compile/data/bin.ts
src/compile/data/parse.ts
src/transform.ts
test/compile/data/bin.test.ts
test/compile/data/parse.test.ts

Allow bin.as to be an array of 2 strings

---

site/examples/index.md

New example based on vega example: https://vega.github.io/vega-editor/?mode=vega&spec=weather

Add new example in Bl.ock to Community Examples

---

examples/specs/point_href.vl.json
site/docs/encoding.md
site/docs/mark/mark.md
src/compile/mark/init.ts
test/compile/mark/init.test.ts

Enable cursor when href channel present

---

build/vega-lite-schema.json
site/docs/mark/bar.md
site/docs/mark/mark.md
site/docs/mark/rect.md
site/docs/mark/text.md
site/docs/mark/tick.md
src/vega.schema.ts

Updating docs to account for new mark properties. Some I added in PR #3883 and some were already added but not in the docs.

Change docs to account for new mark properties

---

examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json
examples/specs/normalized/boxplot_2D_horizontal_explicit_aggregate_normalized.vl.json
examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json
examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json
examples/specs/normalized/layer_boxplot_circle_normalized.vl.json
src/compositemark/boxplot.ts
src/compositemark/errorband.ts
src/compositemark/errorbar.ts
src/encoding.ts
test/compositemark/boxplot.test.ts
test/compositemark/errorband.test.ts
test/compositemark/errorbar.test.ts
test/spec.test.ts

Refactor error bar and error band as in issue #3770 .

Refactor error bar and error band

---

site/tutorials/explore.md

Thanks to @mbostock. CC @jakevdp (Altair) and @jwoLondon (Elm Vega)

Correct precipitation unit

---

build/vega-lite-schema.json
scripts/rename-schema.sh
src/spec.ts

Support extended nested specs

---

test/compile/data/fold.test.ts

Remove console.log from test

---

build/vega-lite-schema.json
examples/compiled/bar_aggregate_transform.vg.json
examples/compiled/boxplot_1D_horizontal.vg.json
examples/compiled/boxplot_1D_horizontal_custom_mark.vg.json
examples/compiled/boxplot_1D_horizontal_explicit.vg.json
examples/compiled/boxplot_1D_vertical.vg.json
examples/compiled/boxplot_2D_horizontal.vg.json
examples/compiled/boxplot_2D_horizontal_color_size.vg.json
examples/compiled/boxplot_2D_horizontal_explicit_aggregate.vg.json
examples/compiled/boxplot_2D_vertical.vg.json
examples/compiled/boxplot_minmax_2D_horizontal.vg.json
examples/compiled/boxplot_minmax_2D_horizontal_custom_midtick_color.vg.json
examples/compiled/boxplot_minmax_2D_vertical.vg.json
examples/compiled/errorband_2d_horizontal_color_encoding.vg.json
examples/compiled/errorband_2d_vertical_borders.vg.json
examples/compiled/errorbar_2d_vertical_ticks.vg.json
examples/compiled/layer_boxplot_circle.vg.json
examples/compiled/layer_cumulative_histogram.vg.json
examples/compiled/layer_line_errorband_2d_horizontal_borders_strokedash.vg.json
examples/compiled/layer_line_errorband_ci.vg.json
examples/compiled/layer_point_errorbar_2d_horizontal_ci.vg.json
examples/compiled/layer_point_errorbar_2d_horizontal_iqr.vg.json
examples/compiled/layer_point_errorbar_ci.vg.json
src/compile/data/aggregate.ts
src/compile/data/index.ts
src/compile/data/parse.ts
src/data.ts
test/compile/data/aggregate.test.ts
test/compile/data/parse.test.ts

Required for https://github.com/vega/vega-lite/pull/3992

Fix bug in derived fields for aggregate transforms

---

site/docs/data.md

Adding some code examples on how to use named data sources
Please:
- [ x] Make your pull request atomic, fixing one issue at a time unless there are multiple relevant issues that would not make sense in isolation. For the latter case, please make atomic commits so we can easily review each issue.
- [N/A] Provide a test case & update the documentation under `site/docs/`
- [N/A] Make lint and test pass. (Run `yarn test`.  If your change affects Vega outputs of some examples, re-run `yarn build` and run `yarn build:example EXAMPLE_NAME` to re-compile a specific example or `yarn build:examples` to re-compile all examples.)
- [x ] Provide a concise title that we can …

Document: How to use named data sources

---

site/tutorials/getting_started.md

Does vega-lite still depend on d3?

---

src/compile/data/assemble.ts
src/compile/data/filterinvalid.ts
src/compile/data/parse.ts
src/compile/mark/rule.ts
test/compile/selection/translate.test.ts
test/compile/selection/zoom.test.ts
test/compile/unit.test.ts
tsconfig.json

Enable `noUnusedLocals` in tsconfig

---

src/compile/mark/mark.ts

Make tooltip work correctly with stack area

---

site/usage/applications.md

added leaflet map

---

build/vega-lite-schema.json
src/fielddef.ts

This is useful for color/fill/stroke -- see https://github.com/vega/vega/issues/1367

Support null for value def

---

scripts/check-and-fix.sh

We actually never commit on master, so there is no point pushing

Make the script a bit more readable.

---

build/vega-lite-schema.json
scripts/rename-schema.sh

These are accidentally renamed in https://github.com/vega/vega-lite/pull/3787

Fix schema renaming for FieldDefWithoutScale

---

build/vega-lite-schema.json
examples/compiled/concat_marginal_histograms.vg.json
examples/compiled/concat_population_pyramid.vg.json
examples/compiled/facet_bullet.vg.json
examples/compiled/rect_lasagna_future.vg.json
src/compile/axis/assemble.ts
src/compile/facet.ts
src/compile/legend/parse.ts
src/compile/mark/valueref.ts
src/encoding.ts
src/facet.ts
src/fielddef.ts
test/fielddef.test.ts

Consolidate Title

---

src/compile/legend/encode.ts
src/compile/mark/mixins.ts

Make `fill`/`stroke` respect `null`

---

site/docs/mark/mark.md

(The published one is weird.  -- We should release and update once we merge this)

Revise mark docs

---

examples/compiled/concat_bar_scales_discretize.vg.json
examples/specs/concat_bar_scales_discretize.vl.json

This PR updates description for example added in #4000

CLN: Update concat_bar_scales_discretize spec description

---

src/compile/facet.ts
src/compile/selection/selection.ts
test/compile/selection/facets.test.ts

Add only a single "facet" signal per FacetModel (fixes #3688).

Add only a single "facet" signal per FacetModel (fixes #3688).

---

src/compile/data/optimizers.ts
src/util.ts
test/util.test.ts

Change the intersection function to determine dependencies

---

src/compile/data/assemble.ts

Removing excess changes from #2485. Tested before and after removing excess chunk and all tests pass.

Removing excess changes from boxplot iqr pr

---

site/usage/applications.md

Add Saite exploration system under "Bindings ... " heading
Add new "Frameworks ..." heading and place Hanami under that

Add new Saite and Hanami entries.

---

site/usage/compile.md

Add field-title tag for internal formatter link

---

src/compile/data/optimize.ts
src/compile/data/optimizers.ts
test/compile/data/optimize.test.ts

Merge after #4097 is merged and #3832 is resolved.

Make ParseNode Merging Logic Bottom-Up

---

examples/compiled/layer_overlay.vg.json
src/compile/data/optimize.ts
src/compile/data/optimizer.ts
src/compile/data/optimizers.ts
test/compile/data/optimize.test.ts
test/compile/data/optimizers.test.ts

Merge after #4097, #4118 are merged and #3832 is resolved.

Refactor optimizers to classes

---

src/compile/common.ts
test/compile/common.test.ts

Support formatting non quantitative encodings

---

src/compile/mark/mark.ts
test/compile/mark/mark.test.ts

Do not group pathgroup by tooltip fields.

---

src/compile/data/window.ts
test/compile/data/aggregate.test.ts
test/compile/data/window.test.ts

Produced and dependent field fixes

---

package.json
src/compile/data/assemble.ts
src/compile/data/index.ts
src/compile/data/lookup.ts
src/compile/data/optimize.ts
src/compile/data/parse.ts
src/compile/data/source.ts
src/compile/model.ts
src/data.ts
src/util.ts
test/compile/data/assemble.test.ts

Don’t hash datasets

---

.travis.yml
test/compile/data/optimize.test.ts

This makes sure travis fails if the tests fail and also fixes the dataflow tests.

Travis should fail when tests fail

---

examples/compiled/interactive_query_widgets.vg.json
examples/compiled/selection_bind_cylyr.vg.json
examples/compiled/selection_bind_origin.vg.json
examples/compiled/trellis_selections.vg.json
src/compile/selection/transforms/inputs.ts
test/compile/selection/inputs.test.ts

Fixes #4158. 
**This PR branches off the refactoring introduced by #4068, so please merge that one first.**

Use explicit null check for bound selection signals

---

build/vega-lite-schema.json
src/compositemark/common.ts
test/compositemark/common.test.ts

Add clip support to composite mark

---

src/compile/mark/valueref.ts

Warning on channel2 instead of channel for binned

---

yarn.lock

This should fix the travis tests.

Upgrade har-validator

---

examples/compiled/interactive_panzoom_splom.vg.json
examples/compiled/interactive_panzoom_vconcat_shared.vg.json
examples/compiled/interactive_splom.vg.json
examples/compiled/selection_concat.vg.json
examples/compiled/trellis_selections.vg.json
src/compile/selection/transforms/scales.ts
test/compile/selection/scales.test.ts

Wrap keys as strings for top-level scale-bound selection signal.

---

site/static/main.css

Wrap overflowing code

---

build/vega-lite-schema.json
package.json
src/fielddef.ts

Replaces https://github.com/vega/vega-lite/pull/4284

Make ValueDefWithCondition type more strict. Fixes #4236

---

_layouts/docs.html
site/docs/data.md

Fix data docs

---

src/compile/mark/mixins.ts
test/compile/mark/mixins.test.ts

[Bug Fix] Make nonPosition respect default value set in the markDef

---

src/compile/mark/mixins.ts

Follow up https://github.com/vega/vega-lite/pull/4328

Simplify color mixins logic

---

examples/compiled/boxplot_1D_horizontal.vg.json
examples/compiled/boxplot_1D_horizontal_custom_mark.vg.json
examples/compiled/boxplot_1D_horizontal_explicit.vg.json
examples/compiled/boxplot_1D_vertical.vg.json
examples/compiled/boxplot_2D_horizontal.vg.json
examples/compiled/boxplot_2D_horizontal_color_size.vg.json
examples/compiled/boxplot_2D_horizontal_explicit_aggregate.vg.json
examples/compiled/boxplot_2D_vertical.vg.json
examples/compiled/boxplot_minmax_2D_horizontal.vg.json
examples/compiled/boxplot_minmax_2D_horizontal_custom_midtick_color.vg.json
examples/compiled/boxplot_minmax_2D_vertical.vg.json
examples/compiled/layer_boxplot_circle.vg.json
examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json
examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json
examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json
examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json
examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json
examples/specs/normalized/boxplot_2D_horizontal_explicit_aggregate_normalized.vl.json
examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json
examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json
examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json
examples/specs/normalized/layer_boxplot_circle_normalized.vl.json
src/compositemark/boxplot.ts
test/compositemark/boxplot.test.ts

Old tooltip was so broken due to axis title:
New:
TODO: Need to fix the tests

Better boxplot tooltip

---

.vscode/settings.json

Now that we apply prettify to other file types too.

Change formatOnSave config to apply to all file types

---

src/axis.ts

Otherwise the grids won't align.
Fix #4363

Make grid axes respect bandPosition and tickOffset

---

build/vega-lite-schema.json
src/spec/base.ts
src/spec/concat.ts
src/spec/facet.ts
src/spec/index.ts
src/spec/layer.ts
src/spec/repeat.ts
src/spec/unit.ts

Add docs for spec

---

src/compile/model.ts
src/compile/scale/assemble.ts

getSizeName => getSignalName

---

build/vega-lite-schema.json
src/compile/mark/mixins.ts
src/compile/repeater.ts
src/encoding.ts
test/compile/mark/mixins.test.ts

Support `encoding.tooltip` = `null`

---

.travis.yml
scripts/deploy-gh.sh
scripts/deploy.sh
scripts/pre-deploy.sh

Clean up set

---

build/vega-lite-schema.json
examples/specs/layer_point_errorbar_pre_aggregated_asymmetric_error.vl.json
examples/specs/layer_point_errorbar_pre_aggregated_symmetric_error.vl.json
src/compile/mark/mixins.ts
src/compile/mark/valueref.ts
src/compositemark/common.ts
src/compositemark/errorbar.ts
src/encoding.ts
src/fielddef.ts
test/channel.test.ts
test/compositemark/errorbar.test.ts

Make `x/yError` use `SecondaryFieldDef` type

---

_data/link.yml
build/vega-lite-schema.json
src/compile/mark/mixins.ts
src/encoding.ts

Update type for links in the docs

---

examples/compiled/trellis_area.vg.json
examples/compiled/trellis_area_sort_array.vg.json
src/compile/data/stack.ts

Include `facetby` in the output `impute` from `stack` -- Fix #4446

---

build/vega-lite-schema.json
src/fielddef.ts

Fix https://github.com/vega/vega-lite/issues/4448
cc: @marcprux

Add "ShapeType" as an alias for `'nominal' | 'ordinal' | 'geojson'`

---

.travis.yml
package.json
src/encoding.ts
yarn.lock

I just ran `rm yarn.lock && yarn`

Update dependencies to fix the site. Fixes #4451.

---

src/title.ts

Fix missing frame title property in config

---

site/usage/applications.md

Updates for Clojure/ClojureScript library

Add updated feature list for Oz

---

site/usage/applications.md

add vegawidget to applications-documentation

---

site/examples/index.md

add wheat and wages example

---

src/spec/index.ts

Remove methods as mentioned in #4399

Remove unused usedFields method from spec

---

build/vega-lite-schema.json
site/docs/tooltip.md
src/mark.ts

Allow disabling tooltips from the config and document how to disable tooltips.

---

site/examples/index.md

Following the example in Vega (https://vega.github.io/vega/examples/top-k-plot-with-others/), I implemented this same example in VL performing subsequent aggregations.

add top-k plot WITH others

---

src/stack.ts
test/stack.test.ts

[BugFix] Ignore tooltip in `stackBy`

---

.gitignore

Remove ds_store from gitignore

---

src/log.ts
src/normalize/core.ts
test/normalize/core.test.ts

Drop `columns` from row/column facet

---

examples/compiled/bar_layered_weather.vg.json
src/compile/axis/parse.ts

Fix incorrect labelAlign in spec with top orient

---

CONTRIBUTING.md

Run `yarn tsc -w` for automatic compilation.

Updating README for "Manually Testing with Vega-Editor"

---

package.json

Update author and collaborators in package.json.

---

examples/compiled/layer_line_co2_concentration.vg.json
examples/specs/layer_line_co2_concentration.vl.json
examples/specs/normalized/layer_line_co2_concentration_normalized.vl.json

Remove redundant sort from window in CO2 example.

---

examples/compiled/concat_bar_layer_circle.vg.json
examples/compiled/interactive_concat_layer.vg.json
src/compile/axis/parse.ts

Make isExplicit check for label/titleAngle respect normalized angle

---

build/vega-lite-schema.json
src/axis.ts

Fix the problem that `Field`  gets overridden by Vega's `Field` in the schema

---

src/compile/model.ts
src/log.ts
test/compile/compile.test.ts

Support title anchor for multi-view composition

---

examples/compiled/interactive_multi_line_label.vg.json
examples/compiled/interactive_paintbrush.vg.json
examples/compiled/interactive_paintbrush_color_nearest.vg.json
examples/compiled/interactive_stocks_nearest_index.vg.json
examples/compiled/selection_multi_condition.vg.json
examples/compiled/trellis_selections.vg.json
src/compile/common.ts
src/compile/mark/mixins.ts
src/compile/mark/valueref.ts
src/compile/selection/transforms/nearest.ts
src/fielddef.ts
src/util.ts
test/compile/selection/nearest.test.ts

Fix https://github.com/vega/vega-lite/issues/4295

[BugFix] Add tooltip to the voronoi underlying `nearest`

---

src/channel.ts
src/compile/data/aggregate.ts
test/compile/data/aggregate.test.ts

Make aggregate use the right group-by field for lat/long

---

build/vega-lite-schema.json
site/docs/encoding/header.md
src/compile/facet.ts
src/compile/header/assemble.ts
src/compile/header/common.ts
src/compile/header/parse.ts
src/compile/model.ts
src/config.ts
src/fielddef.ts
src/guide.ts
src/header.ts
src/normalize/core.ts
src/vega.schema.ts
test/compile/facet.test.ts
test/compile/header/assemble.test.ts

Merge https://github.com/vega/vega-lite/pull/4695 first

Many fixes for header

---

site/examples/index.md

Add example for international flight data visualisation: https://observablehq.com/@alhenry/international-flight-map

Add flightt example

---

src/compile/legend/encode.ts

Fix https://github.com/vega/vega-lite/issues/4748

[Bug Fix] Respect `config.legend.symbolBaseFillColor`  

---

package.json
src/util.ts
typings/fast-json-stable-stringify/index.d.ts
yarn.lock

So dependent projects get this automatically

[Build Fix] Use @types/fast-json-stable-stringify

---

examples/compiled/selection_bind_origin.vg.json

Rebuild example to fix master

---

src/compile/selection/transforms/project.ts

Fixes the bug identified in https://github.com/vega/vega-lite/issues/4766#issuecomment-476023981.

Fix bug with inferring projection from selection initialization

---

examples/compiled/bar_grouped_horizontal.vg.json
examples/compiled/concat_marginal_histograms.vg.json
examples/compiled/concat_population_pyramid.vg.json
examples/compiled/layer_dual_axis.vg.json
examples/compiled/parallel_coordinate.vg.json
examples/compiled/rect_mosaic_labelled.vg.json
examples/compiled/rect_mosaic_labelled_with_offset.vg.json
examples/compiled/stacked_area_normalize.vg.json
examples/compiled/stacked_area_stream.vg.json
src/compile/axis/assemble.ts

Fix bugs due to width/height for fixing grid axis causing problems to selection

---

src/channel.ts
src/normalize/ruleforrangedline.ts
test/normalize/ruleforrangedline.test.ts

[BugFix] Don't change line to rule for binned data

---

examples/compiled/trellis_scatter_binned_row.vg.json
src/compile/facet.ts
test/compile/facet.test.ts

[BugFix] Fix labels for binned facet field

---

src/compile/mark/bar.ts
src/compile/mark/mixins.ts
test/compile/mark/bar.test.ts

Fix https://github.com/vega/vega-lite/issues/4783

[BugFix] Make bar's bandPosition respect `config.bar.discreteBandSize`

---

_data/link.yml
build/vega-lite-schema.json
site/docs/encoding.md
site/docs/encoding/axis.md
site/docs/encoding/condition.md
site/docs/encoding/field.md
site/docs/encoding/header.md
site/docs/encoding/legend.md
site/docs/encoding/scale.md
site/docs/encoding/sort.md
site/docs/encoding/value.md
site/docs/selection/selection.md
site/docs/transform/aggregate.md
site/docs/transform/bin.md
site/docs/transform/calculate.md
site/docs/transform/filter.md
site/docs/transform/flatten.md
site/docs/transform/fold.md
site/docs/transform/impute.md
site/docs/transform/joinaggregate.md
site/docs/transform/lookup.md
site/docs/transform/sample.md
site/docs/transform/stack.md
site/docs/transform/timeunit.md
site/docs/transform/window.md
src/fielddef.ts

Note that the reference if currently quite nightmarish, but I think fixing https://github.com/vega/ts-json-schema-generator/issues/84 should alleviate this problem
(Still need to check the site if this really fixes the problem, but I can't run `yarn site`

Improve Docs

---

build/vega-lite-schema.json
src/encoding.ts

instead of `StringFieldDefWithCondition`
(StringFieldDefWithCondition includes scale, legend -- which do not make sense  for `href`.

[Fix Schema] Make `href` channel use `TextFieldDefWithCondition` 

---

site/docs/overview.md
site/static/main.css

Add search to docs overview.

---

examples/compiled/layer_dual_axis.vg.json
examples/compiled/parallel_coordinate.vg.json
examples/specs/layer_dual_axis.vl.json
examples/specs/normalized/layer_dual_axis_normalized.vl.json
examples/specs/normalized/parallel_coordinate_normalized.vl.json

Replaces https://github.com/vega/vega-lite/pull/4900

Use local data path instead of absolute URL

---

src/compile/data/assemble.ts
src/compile/data/parse.ts
src/compile/data/source.ts
src/data.ts
test/compile/data/parse.test.ts

Fixes #4910
Replaces https://github.com/vega/vega-lite/pull/4912

Do not merge conflicting data sources

---

site/docs/encoding/condition.md

Fix what went wrong in https://github.com/vega/vega-lite/commit/707e628c4bdf6875fa84f41ecb760fdb5509c92b#diff-ef71775030033dcbaa33d3a722a6691dL65

Correct code block. Fixes #4952

---

src/stack.ts
test/stack.test.ts

Add disallowNonLinearStack option to `stack()` method for usage in CompassQL

---

build/vega-lite-schema.json
src/legend.ts

Fixes https://github.com/vega/vega-lite/issues/4924

Add 'top' and 'bottom' options for legend orient to documentation

---

src/sort.ts

[Comment] that field should be optional in EncodingSortField

---

src/compile/mark/rect.ts
test/compile/mark/rect.test.ts

Fix ranged rect on ordinal scale

---

src/channel.ts
test/compile/legend/parse.test.ts

Part of https://github.com/vega/vega-lite/issues/4982

[Enhancement] Enable legend for strokeWidth

---

build/vega-lite-schema.json
src/compile/header/parse.ts
src/header.ts

Fix: Add header `labels` property for disabling header labels

---

src/transform.ts
test/compile/data/impute.test.ts

Fix: Make impute sequence support start

---

examples/compiled/concat_weather.vg.json
examples/compiled/layer_dual_axis.vg.json
examples/compiled/layer_line_errorband_2d_horizontal_borders_strokedash.vg.json
examples/compiled/layer_line_errorband_ci.vg.json
examples/compiled/layer_line_errorband_pre_aggregated.vg.json
examples/compiled/layer_line_mean_point_raw.vg.json
examples/compiled/repeat_layer.vg.json
examples/compiled/repeat_line_weather.vg.json
examples/compiled/selection_brush_timeunit.vg.json
src/compile/data/optimize.ts
src/compile/data/optimizers.ts
src/compile/data/parse.ts
src/compile/data/timeunit.ts
src/compile/selection/transforms/project.ts
test/compile/data/optimizers.test.ts
test/compile/data/timeunit.test.ts
test/transformextract.test.ts

Add optimization to merge adjacent TimeUnit nodes in DataFlow tree.

Merge TimeUnit nodes

---

site/docs/encoding/axis.md
site/docs/encoding/legend.md
site/docs/view/title.md

Please rebase since the commits are atomic.

docs: add missing axis, legend, and title properties 

---

build/vega-lite-schema.json
examples/examples.test.ts
examples/schema.test.ts
src/header.ts
src/mark.ts
src/selection.ts
src/spec/base.ts
src/vega.schema.ts

Enables better autocomplete in the editor. See https://github.com/microsoft/monaco-json

Use the Color type more consistently

---

build/vega-lite-schema.json
site/docs/encoding/scale.md
src/scale.ts
src/vega.schema.ts

feat: add the mixing scale `align` property

---

site/docs/encoding/type.md

docs: discuss how quantitative is related to ratio and interval type of measurement

---

_data/examples.json

example: https://vega.github.io/vega-lite/examples/window_top_k_others.html
* without "https://" the previous link routes to https://vega.github.io/vega-lite/examples/github.com/manzt (does not exist)
* add link to wheat and wages example

docs (example): change author name to @author 

---

src/channeldef.ts
test/channeldef.test.ts

Fix https://github.com/vega/vega-lite/issues/5115

fix: coerce fields to always be strings

---

src/channeldef.ts

Merge https://github.com/vega/vega-lite/pull/5155 first

refactor: simplify normalize fielddef

---

examples/compiled/bar_layered_weather.vg.json
examples/compiled/concat_layer_voyager_result_future.vg.json
src/compile/legend/assemble.ts
src/compile/mark/valueref.ts
src/compile/scale/assemble.ts
src/compile/scale/component.ts
src/compile/scale/domain.ts
src/compile/split.ts
src/log/message.ts
test/compile/layer.test.ts
test/compile/repeat.test.ts
test/compile/scale/domain.test.ts
test/compile/scale/parse.test.ts

fix: split scale domains into explicit and implicit.

---

package.json

Fixes https://github.com/vega/vega-lite/issues/5178

chore(package): update @types/node to version 12.6.0

---

build/vega-lite-schema.json
src/compile/model.ts
src/spec/base.ts

fix: view style can be an array

---

src/compile/data/optimize.ts

Removes the excessive passing around and reassigning of `mutatedFlag`.
~~Merge after #5170.~~

chore: refactor optimizationDataflowHelper 

---

build/vega-lite-schema.json
src/aggregate.ts
src/axis.ts
src/channel.ts
src/legend.ts
src/mark.ts
src/scale.ts
src/spec/base.ts
src/timeunit.ts
src/util.ts
src/vega.schema.ts

* remove `flagKeys` since it's the same as `keys`
* simplify code since the schema generator supports typeof

Refactor: simplify flag typings

---

build/vega-lite-schema.json
package.json
src/compile/data/parse.ts
src/compile/model.ts
src/spec/base.ts
src/spec/index.ts
src/spec/unit.ts
yarn.lock

feat: set data: null to ignore the parent's data

---

_data/link.yml
build/vega-lite-schema.json
site/docs/transform/aggregate.md
src/aggregate.ts
src/compile/scale/domain.ts
src/encoding.ts
src/sort.ts
test/stack.test.ts

WIP: Let's wait until https://github.com/vega/vega/pull/1819 got merged and released.

fix(schema): remove `argmin/max` from  fieldDef's `aggregate`

---

src/compile/mark/mixins.ts
src/compile/predicate.ts
src/compile/selection/assemble.ts
src/compile/selection/parse.ts
test/compile/selection/predicate.test.ts

(as it's happening during parse)

refactor: move `assembleSelectionPredicate` to `parseSelectionPredicate`

---

_data/link.yml
build/vega-lite-schema.json
site/docs/selection/init.md
src/compile/common.ts
src/compile/selection/index.ts
src/compile/selection/transforms/project.ts
src/selection.ts

fix: refactor selection initialization and docs

---

build/vega-lite-schema.json
site/docs/encoding/header.md
src/axis.ts
src/compile/axis/parse.ts
src/compile/header/assemble.ts
src/compile/legend/parse.ts
src/guide.ts
src/legend.ts
test/compile/header/assemble.test.ts

Follow up for https://github.com/vega/vega-lite/pull/5260 to also support headers.

feat: support labelExpr in headers

---

site/usage/ecosystem.md

Please:
- Mention relevant issues. (e.g., `Fix #1` / `Fix part of #1`)
- For new features
Tips:
- https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice pull request.
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/)

docs: add vega for Node-RED node to ecosystem list

---

package.json
src/aggregate.ts
src/compile/scale/domain.ts
src/log/message.ts
test/compile/scale/domain.test.ts

Made possible by https://github.com/vega/vega/pull/1957

feat: support sorting unioned domains by min and max in addition to count

---

site/tutorials/getting_started.md

:wave: 
The array is formatted the same way as in the previous example.
Cheers,
Markus

docs: remove sentence about reformatted array

---

src/log/index.ts

refactor: use explicit type annotation

---

src/compositemark/boxplot.ts

We know that filteredLayersMixins is true already.

refactor: simplify expression in boxplot.ts

---

.eslintignore
commitlint.config.js
package.json
yarn.lock

I understand that we may not want to do this since we often squash PRs. 
Merge after #5390

chore: lint commit messages

---

site/docs/transform/timeunit.md

docs: a negation missing

---

src/compile/axis/assemble.ts
src/compile/axis/parse.ts
src/compile/baseconcat.ts
src/compile/common.ts
src/compile/data/aggregate.ts
src/compile/data/debug.ts
src/compile/data/pivot.ts
src/compile/data/window.ts
src/compile/facet.ts
src/compile/layer.ts
src/compile/mark/mixins.ts
src/compile/model.ts
src/compile/scale/parse.ts
src/compile/selection/assemble.ts
src/compile/unit.ts
src/log/index.ts
src/util.ts
test-runtime/discrete.test.ts
test-runtime/util.ts
test/util.test.ts

Inspired by https://twitter.com/WrocTypeScript/status/1167907329389387779.

refactor: ensure more functions don't modify arguments, remove unused functions

---

site/docs/mark/mark.md

docs: fix link to rect mark

---

src/aggregate.ts
src/bin.ts
src/channeldef.ts
src/datetime.ts
src/mark.ts
src/scale.ts
src/type.ts
src/util.ts
tsconfig.json

feat: more changes to prepare for strictNullCheck support

---

src/compile/selection/parse.ts
test/compile/selection/inputs.test.ts

fix: look up selection origDef using original name not varName

---

build/vega-lite-schema.json
src/vega.schema.ts

Fixes https://github.com/vega/vega-lite/issues/5598

fix: allow any tension value

---

build/vega-lite-schema.json
src/channeldef.ts
src/stack.ts
test/stack.test.ts

Fixes https://github.com/vega/vega-lite/issues/5611

feat: support disabling impute for stacking

---

src/compile/common.ts
test/compile/data/bin.test.ts
test/compile/mark/text.test.ts
test/compile/mark/valueref.test.ts

fix: use en dash for legend ranges

---

build/vega-lite-schema.json
src/axis.ts

fix: remove unnecessary aliases for conditional axis properties  

---

site/docs/types.md

part of https://github.com/vega/vega-lite/issues/5634

docs: fix broken gradient table

---

site/_data/examples.json

the bar_size_responsive doesn't show up...

docs: add responsive bar chart example

---

src/compile/data/parse.ts
test/compile/data/parse.test.ts

fix: do not treat data sources with different features or meshes as the same

---

src/compile/mark/valueref.ts
test/compile/mark/point.test.ts

fix: respect offset for mark.x/y

---

src/compile/mark/mixins.ts
test/compile/mark/rect.test.ts

also don't throw incorrect warning
Fix https://github.com/vega/vega-lite/issues/5505

fix: correctly apply align to `bandPosition`, make center the default align

---

src/util.ts
test/util.test.ts

Fixes https://github.com/vega/vega-lite/issues/5660

fix: support escaping of brackets

---

examples/examples.test.ts
src/compile/legend/parse.ts
src/compile/selection/transforms/legends.ts

fix: make sure that names are valid even when fields have special characters

---

build/vega-lite-schema.json
site/_data/link.yml
site/_includes/type-anyof.html
src/axis.ts

fix: axis type (labelAlign) and docs

---

site/docs/data.md

See https://github.com/vega/vega-lite/issues/5753#issuecomment-580225225
cc @mattijn

docs: fix order of graticulr params

---

build/vega-lite-schema.json
examples/compiled/bar_layered_weather.vg.json
examples/compiled/layer_bar_labels_grey.vg.json
examples/compiled/layer_likert.vg.json
examples/compiled/layer_point_line_regression.vg.json
src/channeldef.ts
src/compile/common.ts
src/compile/legend/encode.ts
src/compile/legend/properties.ts
src/compile/mark/encode/color.ts
src/compile/mark/encode/nonposition.ts
src/compile/mark/encode/position-rect.ts
src/compile/mark/encode/valueref.ts
src/compile/mark/tick.ts
src/config.ts
src/mark.ts
src/spec/base.ts
src/title.ts
src/vega.schema.ts

(Note the target branch to merge is `signal`)

feat: support signal reference in mark properties and configs

---

build/vega-lite-schema.json
site/docs/config.md
site/docs/encoding/axis.md
src/axis.ts
src/compile/axis/config.ts
src/compile/axis/parse.ts
src/compile/axis/properties.ts
src/config.ts

Part of https://github.com/vega/vega-lite/issues/5871

feat: support config.axisQuantitative/Temporal

---

build/vega-lite-schema.json
src/axis.ts

Follow up for https://github.com/vega/vega-lite/pull/5873/

docs: simplify axis config descriptions

---

package.json
src/compile/compile.ts
src/config.ts
src/spec/base.ts
test/config.test.ts

feat: support (experimental) signal-based color/fontSize config

---

build/vega-lite-schema.json
src/compile/scale/domain.ts
src/scale.ts
test/compile/scale/domain.test.ts

Fix https://github.com/vega/vega-lite/issues/5823
Merge https://github.com/vega/vega-lite/pull/5886 first

feat: add domain unionWith support

---

build/vega-lite-schema.json
src/config.ts
test/config.test.ts

Note that since this feature doesn't involve signal, I'm not hiding it.

feat: support config.font

---

src/config.ts
test/config.test.ts

My bad, I didn't know how we didn't catch this.

fix: remove broken legend config

---

examples/specs/normalized/area_density_facet_normalized.vl.json
examples/specs/normalized/bar_grouped_horizontal_normalized.vl.json
examples/specs/normalized/bar_grouped_normalized.vl.json
examples/specs/normalized/facet_custom_header_normalized.vl.json
examples/specs/normalized/facet_custom_normalized.vl.json
examples/specs/normalized/geo_trellis_normalized.vl.json
examples/specs/normalized/isotype_bar_chart_emoji_normalized.vl.json
examples/specs/normalized/isotype_bar_chart_normalized.vl.json
examples/specs/normalized/trellis_area_normalized.vl.json
examples/specs/normalized/trellis_area_sort_array_normalized.vl.json
examples/specs/normalized/trellis_bar_normalized.vl.json
examples/specs/normalized/trellis_barley_independent_normalized.vl.json
examples/specs/normalized/trellis_barley_normalized.vl.json
examples/specs/normalized/trellis_scatter_small_normalized.vl.json
src/normalize/core.ts

fix: propagate view property for faceted unit spec

---

build/vega-lite-schema.json
site/docs/encoding/axis.md
src/axis.ts
src/compile/axis/parse.ts

Merge https://github.com/vega/vega-lite/pull/5928 first

feat: support `tickCount` and `labelExpr` as axis config

---

build/vega-lite-schema.json
src/axis.ts
src/compile/axis/assemble.ts
src/compile/axis/component.ts
test/compile/axis/assemble.test.ts

Note: this is a temporary implementation, we should remove this and use Vega's once Vega ships the next version

feat: support axis `labelOffset`

---

build/vega-lite-schema.json
package.json
src/compile/scale/assemble.ts
src/compile/scale/component.ts
src/compile/scale/domain.ts
src/compile/scale/properties.ts
src/scale.ts
src/vega.schema.ts
test/compile/selection/scales.test.ts
yarn.lock

refactor: re-use typings for Vega scale

---

build/vega-lite-schema.json
site/_data/link.yml
site/docs/encoding/scale.md
src/channeldef.ts
src/compile/scale/component.ts
src/compile/scale/domain.ts
src/compile/scale/range.ts
src/scale.ts
test/compile/scale/domain.test.ts
test/compile/scale/range.test.ts

Merge https://github.com/vega/vega-lite/pull/5935 first

feat: support signal for scale properties

---

examples/compiled/bar_diverging_stack_population_pyramid.vg.json
examples/compiled/circle_wilkinson_dotplot.vg.json
examples/compiled/concat_population_pyramid.vg.json
src/compile/scale/domain.ts
test/compile/scale/domain.test.ts

refactor: simplify sorted domains

---

src/compile/scale/domain.ts
test/compile/scale/domain.test.ts

refactor: simplify date domains

---

examples/specs/normalized/area_gradient_normalized.vl.json
examples/specs/normalized/area_overlay_normalized.vl.json
examples/specs/normalized/stacked_area_overlay_normalized.vl.json
src/normalize/pathoverlay.ts
test/normalize/pathoverlay.test.ts

fix: allow overriding area opacity with line: true

---

src/compile/model.ts
test/compile/model.test.ts

fix: support signals in view properties

---

src/config.ts

Fix https://github.com/vega/vega-lite/issues/5947

fix: correct title config precedence

---

src/util.ts
test/util.test.ts

fix: correctly unescape quotes

---

build/vega-lite-schema.json
src/axis.ts
yarn.lock

fix: correct type of label offset

---

src/compile/legend/assemble.ts
src/legend.ts

Fixes https://github.com/vega/vega-lite/issues/6006

fix: don't encode with properties that the legend encodes

---

build/vega-lite-schema.json
src/axis.ts
src/compile/axis/assemble.ts
src/compile/axis/component.ts
test/compile/axis/assemble.test.ts

Fix https://github.com/vega/vega-lite/issues/6013?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDczODExNTk4MzoxMTEyNjk%3D

fix: support conditional labelOffset

---

src/compile/axis/parse.ts
test/compile/axis/parse.test.ts

fix https://github.com/vega/vega-lite/issues/5983

fix: make labelExpr work correctly in axis config

---

src/scale.ts
test/scale.test.ts

fix: allow ordinal scale for opacity/size/strokeWidth

---

rollup.config.js
src/compile/selection/parse.ts
yarn.lock

fix: do not import keys from d3

---

examples/compiled/brush_table.vg.json
examples/compiled/concat_bar_scales_discretize.vg.json
examples/compiled/concat_bar_scales_discretize_2_cols.vg.json
examples/compiled/concat_hover.vg.json
examples/compiled/concat_hover_filter.vg.json
examples/compiled/concat_weather.vg.json
examples/compiled/geo_layer_multi.vg.json
examples/compiled/interactive_bin_extent.vg.json
examples/compiled/interactive_panzoom_vconcat_shared.vg.json
examples/compiled/nested_concat_align.vg.json
examples/compiled/point_quantile_quantile.vg.json
examples/compiled/sample_scatterplot.vg.json
examples/compiled/selection_brush_timeunit.vg.json
examples/compiled/selection_concat.vg.json
examples/compiled/selection_filter.vg.json
examples/compiled/selection_filter_composition.vg.json
examples/compiled/vconcat_flatten.vg.json
examples/compiled/vconcat_weather.vg.json
src/compile/concat.ts
src/compile/layoutsize/assemble.ts
src/compile/layoutsize/component.ts
src/compile/layoutsize/parse.ts
src/compile/model.ts

fix https://github.com/vega/vega-lite/issues/6024
replacing https://github.com/vega/vega-lite/pull/6026

fix: make concat always merge its children width and height	

---

.github/workflows/test.yml
bin/vl2pdf
bin/vl2png
bin/vl2svg
bin/vl2vg
package.json
site/usage/compile.md

Fixes https://github.com/vega/vega-lite/issues/4727

feat: add vl2pdf, test the cli, support windows

---

.npmignore

Please:
- Mention relevant issues. (e.g., `Fixes #1` / `Fixes part of #1`)
Tips:
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/)

chore: remove tsconfig.base.json from npm packages

---

src/channel.ts
src/compile/scale/domain.ts

Fixes https://github.com/vega/vega-lite/issues/6068

fix: use type of main field def since type of secondary is always the same

---

src/compile/scale/domain.ts
src/stack.ts
test/compile/scale/domain.test.ts

Fixes https://github.com/vega/vega-lite/issues/6064

fix: don't sum up stacked dimension fields

---

src/compile/header/assemble.ts

fix: filter null header groups

---

examples/compiled/trellis_area_sort_array.vg.json
examples/compiled/trellis_cross_sort_array.vg.json
src/compile/data/parse.ts
src/encoding.ts

fix: remove duplicate sort index computation in faceted charts

---

src/channeldef.ts
src/compile/data/formatparse.ts
src/predicate.ts
test/predicate.test.ts

Merge https://github.com/vega/vega-lite/pull/6083 first

fix: make predicate value support experimental signals

---

examples/compiled/bar_diverging_stack_population_pyramid.vg.json
examples/compiled/geo_layer_line_london.vg.json
examples/compiled/rect_heatmap_weather.vg.json
examples/compiled/sequence_line_fold.vg.json
src/compile/legend/parse.ts

fix: make legend title work with multi-view resolution

---

src/compile/format.ts
src/compile/mark/encode/tooltip.ts
src/stack.ts
test/compile/mark/encoding/tooltip.test.ts

fix: correct tooltip for normalize stack

---

.github/workflows/check.yml
.github/workflows/test.yml

This way we should also run tests for dependabot.

ci: run on all pushes

---

build/vega-lite-schema.json
src/header.ts
src/mark.ts

Fix https://github.com/vega/vega-lite/issues/6129

feat: add missing header `labelBaseline/FontWeight/LineHeight`

---

examples/compiled/layer_falkensee.vg.json
src/compile/axis/parse.ts
src/config.ts

fix: correctly apply `axisDiscrete/axisPoint` config

---

src/normalize/base.ts
src/normalize/core.ts

Fix follow-up comments in https://github.com/vega/vega-lite/pull/6002

fix: correct repeat child name logic and data precedence

---

site/docs/encoding/axis.md
site/docs/encoding/header.md
site/docs/encoding/legend.md
site/docs/mark/text.md

Fix https://github.com/vega/vega-lite/issues/6162

docs: add missing line height and related properties

---

examples/compiled/bar_1d.vg.json
examples/compiled/bar_1d_step_config.vg.json
examples/compiled/boxplot_1D_horizontal.vg.json
examples/compiled/boxplot_1D_horizontal_custom_mark.vg.json
examples/compiled/boxplot_1D_horizontal_explicit.vg.json
examples/compiled/boxplot_1D_vertical.vg.json
examples/compiled/circle_scale_quantile.vg.json
examples/compiled/circle_scale_quantize.vg.json
examples/compiled/circle_scale_threshold.vg.json
examples/compiled/embedded_csv.vg.json
examples/compiled/layer_point_errorbar_1d_horizontal.vg.json
examples/compiled/layer_point_errorbar_1d_vertical.vg.json
examples/compiled/point_1d.vg.json
examples/compiled/point_1d_array.vg.json
examples/compiled/point_dot_timeunit_color.vg.json
examples/compiled/rule_color_mean.vg.json
examples/compiled/stacked_bar_1d.vg.json
examples/compiled/text_format.vg.json
examples/compiled/tick_dot.vg.json
examples/compiled/tick_dot_thickness.vg.json
examples/compiled/tick_sort.vg.json
examples/compiled/time_parse_local.vg.json
examples/compiled/time_parse_utc.vg.json
examples/compiled/time_parse_utc_format.vg.json
src/compile/axis/assemble.ts

Extracted from https://github.com/vega/vega-lite/pull/6173

fix: generate correct axis signals

---

src/compile/mark/encode/valueref.ts

Fix https://github.com/vega/vega-lite/issues/5970

fix: make band property correctly work for field with timeUnit

---

src/compile/header/parse.ts

fix: support config.header.labels

---

site/docs/transform/pivot.md

The old docs is Vega, not Vega-Lite!

docs: fix pivot

---

test/transformextract.test.ts

test: make master test pass

---

examples/compiled/bar_diverging_stack_population_pyramid.vg.json
examples/compiled/bar_grouped.vg.json
examples/compiled/bar_grouped_horizontal.vg.json
examples/compiled/concat_population_pyramid.vg.json
examples/compiled/parallel_coordinate.vg.json
examples/compiled/rect_heatmap_weather.vg.json
examples/compiled/rect_mosaic_labelled.vg.json
examples/compiled/rect_mosaic_labelled_with_offset.vg.json
examples/compiled/selection_heatmap.vg.json
examples/compiled/wheat_wages.vg.json
src/compile/axis/config.ts
src/compile/axis/parse.ts
src/config.ts

No need to loop over them if they don't exist

perf: skip empty & unnecessary axis config

---

src/compile/concat.ts
src/compile/data/assemble.ts
src/compile/data/debug.ts
src/compile/data/joinaggregate.ts
src/compile/data/optimize.ts
src/compile/data/optimizers.ts
src/compile/data/stack.ts
src/compile/data/window.ts
src/compile/layer.ts
src/compile/legend/parse.ts
src/compile/scale/parse.ts
src/compile/scale/properties.ts
src/compile/scale/range.ts
src/compile/selection/transforms/clear.ts
src/compositemark/common.ts
src/encoding.ts
src/stack.ts
src/util.ts
test/compile/data/dataflow.test.ts

Loops make it easier to step through code in the debugger.

refactor: replace forEach with proper loops

---

src/channel.ts

Fix: https://github.com/vega/vega-lite/issues/6267

fix: make square support angle channel

---

examples/specs/tick_strip_tick_band.vl.json
src/compile/scale/type.ts

Merge https://github.com/vega/vega-lite/pull/6273 first 
fix https://github.com/vega/vega-lite/issues/6208

fix: automatically use band scale there is fieldDef.band or axis.tickBand

---

src/compile/legend/parse.ts

* Don't use reduce for large code blocks. 
* Use existing LEGEND_SCALE_CHANNELS

refactor: simplify legend parsing code

---

src/compile/axis/config.ts
src/compile/axis/parse.ts
src/compile/axis/properties.ts
test/compile/axis/properties.test.ts

Misc Axis Refactor

---

src/compile/mark/encode/text.ts
test/compile/mark/encode/color.test.ts
test/compile/mark/encode/nonposition.test.ts
test/compile/mark/encode/offset.test.ts
test/compile/mark/encode/position-point.test.ts
test/compile/mark/encode/position-rect.test.ts
test/compile/mark/encode/text.test.ts
test/compile/mark/encode/tooltip.test.ts
test/compile/mark/encode/valueref.test.ts

fix: support signals in text encodings

---

build/vega-lite-schema.json
package.json
site/_data/link.yml
src/axis.ts
src/compile/axis/parse.ts
src/vega.schema.ts
yarn.lock

blocked by https://github.com/vega/vega/pull/2516

feat: support TimeInterval/TimeIntervalStep in tickCount

---

src/compile/axis/properties.ts

revert part of https://github.com/vega/vega-lite/pull/6289

refactor: decouple orient and angle in defaultLabelAlign/Baseline

---

build/vega-lite-schema.json
src/axis.ts
src/compile/axis/config.ts
src/compile/axis/parse.ts
src/compile/common.ts

refactor: avoid repetitive existence check for axis

---

build/vega-lite-schema.json
site/_includes/docs_toc.md
site/docs/config.md
src/encoding.ts
src/mark.ts

Fixes links and clarifies how to remove fill.

docs: improve docs for fill/stroke

---

src/compile/mark/encode/tooltip.ts
test/compile/mark/encode/tooltip.test.ts

fix: make voronoi layer use the right data-driven tooltip

---

build/vega-lite-schema.json
package.json
src/compile/common.ts
src/compile/mark/encode/base.ts
src/compile/mark/mark.ts
src/mark.ts
yarn.lock

fix: make cornerRadius* supports signal + fix other signal support

---

src/compile/axis/parse.ts
src/compile/legend/parse.ts

fix: always set axis/legend disable for correct merging

---

src/compile/mark/mark.ts
test/compile/mark/mark.test.ts

fix: make line work with sort:null correctly

---

examples/compiled/bar.vg.json
examples/compiled/bar_negative.vg.json
examples/compiled/circle_natural_disasters.vg.json
examples/compiled/layer_bar_annotations.vg.json
examples/compiled/parallel_coordinate.vg.json
examples/compiled/rect_heatmap_weather.vg.json
examples/compiled/rect_lasagna.vg.json
examples/compiled/waterfall_chart.vg.json
src/compile/axis/assemble.ts
src/compile/axis/properties.ts
test/compile/axis/properties.test.ts
test/compile/header/assemble.test.ts

fix: don't generate label align when angle is 0 for top or bottom axis

---

src/compile/axis/properties.ts
src/compile/header/assemble.ts
test/compile/axis/properties.test.ts

fix: make labelFlush work when labelAngle is set

---

src/channeldef.ts
src/compile/data/parse.ts
src/compile/legend/parse.ts

Discovered in https://lgtm.com/projects/g/vega/vega-lite

fix: various small code fixes

---

src/channeldef.ts
src/compile/mark/encode/valueref.ts
test/compile/mark/encode/valueref.test.ts

feat: support signals in datum

---

.github/workflows/check.yml
.github/workflows/test.yml

ci: cache yarn in CI

---

build/vega-lite-schema.json
src/channeldef.ts
src/compile/mark/encode/text.ts
src/encoding.ts
test/compile/mark/encode/text.test.ts

Merge https://github.com/vega/vega-lite/pull/6438 first

feat: support datum def in text encoding

---

src/channeldef.ts
src/compile/axis/encode.ts
src/compile/axis/properties.ts
src/compile/facet.ts
src/compile/format.ts
src/compile/legend/encode.ts
src/compile/legend/properties.ts
src/compile/unit.ts
src/encoding.ts
src/log/message.ts
test/channeldef.test.ts
test/encoding.test.ts

fix: drop custom format type if disabled + throw warning

---

test/compile/legend/assemble.test.ts

Fix for broken test from https://github.com/vega/vega-lite/pull/6391

chore: fix test

---

src/compile/data/timeunit.ts

fix: support nested access for time units

---

src/bin.ts
src/compile/mark/encode/position-rect.ts
test/compile/mark/encode/position-rect.test.ts

Part of #6086
This isn't a complete fix for #6086 yet since we still have to fix the scale domain, which will be much more complicated.  But at least this is a step into the right direction.

fix: make rect-position support binned field without x2/y2

---

site/docs/transform/aggregate.md

docs: motivate argmin/argmax

---

src/compile/scale/properties.ts

refactor: make scale use "rules" structure similar to axis

---

src/compile/model.ts

fix: title.aria should take precedence over config.aria

---

src/channeldef.ts
src/compile/axis/assemble.ts
src/compile/axis/config.ts
src/compile/common.ts
src/compile/mark/encode/aria.ts
src/compile/mark/encode/position-rect.ts
src/compile/scale/range.ts
src/compositemark/errorbar.ts
src/util.ts

Fixes #6488
Also extracts common functionality for working with siganls so that we can see where certain functionality is used.

fix: support signals in descriptions

---

site/docs/encoding/scale.md

docs: update scale docs about x/y range

---

site/static/index.ts

fixes highlighting on https://vega.github.io/vega-lite/usage/compile.html

docs: add ts highlighting

---

src/compositemark/index.ts

tiny typing patch, feel free to fold into something more substantial.

refactor: allow generic field for encodings

---

site/docs/transform/aggregate.md

See https://github.com/vega/vega/pull/2674

docs: document values aggregate

---

package.json
scripts/bump.sh
site/_data/versions.yml
src/compile/axis/assemble.ts
src/compile/legend/assemble.ts
test/compile/axis/assemble.test.ts
test/compile/legend/assemble.test.ts

fix: make `datum.label` in `labelExpr` work with custom formatter

---

site/docs/encoding/axis.md

docs: document domainDash and domainOffset

---

site/ecosystem.md

It was requested that I add my library `emacs-vega-view` to this document, so here it is. :)
Please:
- [ X] Make the pull requests (PRs) atomic. (Fix one issue at a time.) Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [ X] Provide a concise title so we can easily copy it to the release note.
- Mention relevant issues. (e.g., `Fixes #1` / `Fixes part of #1`)
Tips:
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/)

docs: update ecosystem.md to include emacs-vega-view

---

src/axis.ts
src/compile/axis/parse.ts

fix: correctly apply conditional dash offsets

---

site/docs/encoding/scale.md

Headings cannot have links. I forgot to push the local change I had.

docs: follow up fix for #6600

---

site/docs/encoding/axis.md
site/docs/encoding/legend.md

docs: for axis/legend config's `disable`

---

src/channeldef.ts
src/compile/data/facet.ts
src/compile/facet.ts
src/compile/model.ts
src/compile/scale/domain.ts
src/compile/selection/transforms/project.ts
src/log/message.ts

Fixes https://github.com/vega/vega-lite/issues/6001

refactor: extract all log messages

---

site/index.md

- We now support a lot of customization pretty well
- Make it clear that Vega-Lite works as a primary tool for users (even if they know how to use vega)
fix #6657

docs: revise framing for Vega-Lite

---

src/compile/mark/encode/tooltip.ts
src/mark.ts
test/compile/mark/encode/tooltip.test.ts

fix: make tooltip support signal

---

src/bin.ts
src/channel.ts
src/channeldef.ts
src/compile/data/aggregate.ts
src/compile/data/bin.ts
src/compile/facet.ts
src/compile/legend/encode.ts
src/compile/legend/properties.ts
src/compile/mark/encode/position-rect.ts
src/compile/mark/encode/tooltip.ts
src/compile/model.ts
src/compile/scale/assemble.ts
src/compile/scale/properties.ts
src/compile/scale/range.ts
src/compile/selection/transforms/scales.ts
src/compile/unit.ts
src/encoding.ts
src/log/message.ts
src/scale.ts
test/channeldef.test.ts
test/compile/scale/properties.test.ts
test/compile/unit.test.ts
test/scale.test.ts
tsconfig.base.json

Fixes https://github.com/vega/vega-lite/issues/5173

refactor: use stricter channel types

---

src/compile/mark/encode/position-rect.ts
test/compile/mark/bar.test.ts
test/compile/mark/encode/position-rect.test.ts

fix: fix axis translate signal for binned bar marks

---

site/_data/examples.json

docs: correct repeat layer description

---

src/bin.ts
src/compile/data/debug.ts
src/compile/data/optimize.ts
src/compile/data/optimizer.ts
src/compile/data/optimizers.ts
src/compile/data/subtree.ts
src/compile/data/timeunit.ts
src/compile/mark/encode/aria.ts
src/compile/mark/encode/tooltip.ts
src/util.ts
test/compile/data/optimizers.test.ts
test/util.test.ts

depends on #6786 
fixes #5107, fixes #4174

refactor: improve dataflow optimizer

---

src/axis.ts
src/compile/axis/component.ts
src/compile/legend/assemble.ts
src/legend.ts
test/compile/legend/assemble.test.ts

(since Vega definition already include signals for these properties)

refactor: remove unnecessary `SignalAxisProp` type

---

build/vega-lite-schema.json
src/compile/model.ts
src/compositemark/errorbar.ts
src/config.ts
src/spec/base.ts
src/title.ts
test/config.test.ts

feat: support `expr` in `title

---

site/docs/transform/timeunit.md

docs: fix typo

---

site/docs/transform/quantile.md

docs: fix title in quantile docs

---

bin/args.js
bin/read.js
bin/render.js
bin/vl2pdf
bin/vl2png
bin/vl2svg
bin/vl2vg

feat: node only cli

---

site/docs/config.md

I don't think you can register a function with the view.

docs: fix custom formatter docs

---

package.json
yarn.lock

chore: remove direct vega typings dependency

---

site/ecosystem.md

Vega and Vega-Lite for Ruby 🎉  (disclaimer: am author)
Re https://twitter.com/domoritz/status/1311064305094152192

docs: add Vega.rb to ecosystem

---

rollup.config.js

Fixes #6857
Will do more when https://github.com/vega/vega/issues/2917 is fixed.

feat: externalize vega-util

---

.gitignore
package.json
rollup.config.js

This reverts commit 79b4fa4cba3dd04e6764c348fc1b7e44030d7ef8.

chore!: reapply externalizing Vega Util and removing es5 build

---

site/usage/compile.md

docs: document how to use npx

---

site/ecosystem.md

Coming from hackernews. Much obliged!
Please:
Tips:

docs: add Voyager clone to the ecosystem page

---

src/channeldef.ts
src/compile/data/dataflow.ts
src/compile/data/formatparse.ts
src/compile/facet.ts
src/compile/mark/mark.ts
src/compile/selection/interval.ts
src/compile/selection/transforms/legends.ts
src/compile/selection/transforms/scales.ts
src/mark.ts
src/scale.ts
src/util.ts
test-runtime/zoom.test.ts
test/compile/selection/timeunit.test.ts
test/util.ts

startsWith improves perf. Includes makes code more readable.

refactor: use startsWith and includes

---

build/vega-lite-schema.json
src/scale.ts

Fixes #7022
CC https://github.com/DougBurke

docs: correct documentation of domain union with

---

build/vega-lite-schema.json
examples/compiled/geo_layer_line_london.vg.json
examples/specs/geo_layer_line_london.vl.json
src/compile/projection/parse.ts
src/projection.ts
test/compile/projection/parse.test.ts

fix!: change default projection to equalEarth

---

src/compile/scale/range.ts

Fixes https://github.com/vega/vega-lite/issues/6997

feat: support getBinStepSignal for prebinned data

---

site/ecosystem.md

Hi,
Thanks a lot for making and maintaining vega-lite!
I added info about neptune.ai integration.

docs: add Neptune to ecosystem page

---

src/axis.ts

fix: apply tickMinStep to gridlines as well

---

src/compile/layoutsize/parse.ts
test/compile/layoutsize/parse.test.ts
test/util.ts

fix: use default resolve when computing layout size

---

build/vega-lite-schema.json
src/config.ts
src/log/message.ts
src/spec/base.ts
src/spec/unit.ts

chore!: remove deprecated code

---

.github/workflows/check.yml
.github/workflows/test.yml

* add back push events for tests
* only run pull request tests for forks

ci: run tests on push or pull request

---

src/normalize/index.ts
src/normalize/selectioncompat.ts
test/normalize/selectioncompat.test.ts

feat: normalize old selection syntax for backwards compatibility

---

examples/compiled/geo_repeat.vg.json
examples/compiled/geo_trellis.vg.json
src/compile/data/assemble.ts
src/compile/data/geojson.ts
test/compile/data/geojson.test.ts

feat: filter invalid for geojson data

---

site/_data/versions.yml
site/_layouts/usage.html
site/usage/typescript.md

docs: add typescript docs

---

examples/compiled/bar_negative_horizontal_label.vg.json
src/compile/axis/assemble.ts

This is what's failing the Vega validation in the master branch and in #7144
Replacing https://github.com/vega/vega-lite/pull/7146

fix: invalid labelBaseline problem

---

src/compile/selection/project.ts
test/compile/selection/parse.test.ts

fix: parse field projections after encodings to prevent duplicates

---

site/ecosystem.md

Context: https://github.com/jgehrcke/github-repo-stats/issues/1

docs: add github-repo-stats to ecosystem

---

build/vega-lite-schema.json
src/compile/selection/project.ts
src/selection.ts
test/compile/selection/point.test.ts

fix: smoothen `value` gradient for var param -> point selection

---

src/guide.ts

[The field-title link here is broken](https://vega.github.io/vega-lite/docs/header.html#general), not sure if this is the correct link, but it was the closest I could find.
---
Please:
Tips:

docs: fix broken field title link

---

data

Doesn't seem to be need for anything.

chore: remove data symlink

---

src/normalize/ruleforrangedline.ts

fix: normalize mark object like primitive mark.

---

.github/workflows/test.yml

Needs https://github.com/Automattic/node-canvas/issues/1688

ci: test node 15

---

site/_data/examples.json

chore: fix typo in chart title: "Highlgiht" to "Highlight"

---

src/vega.schema.ts

Follow up from #7352. 
CC @walterra

fix: do not allow signals in value refs value

---

site/docs/encoding.md

docs: fix typos on longitude and longitude2

---

src/compile/mark/encode/position-range.ts
src/compile/mark/encode/position-rect.ts
test/compile/mark/encode/position-point.test.ts
test/compile/mark/encode/position-range.test.ts

feat: support images on maps

---

site/tutorials/streaming.md

Minor documentation updates related PR https://github.com/vega/vega/pull/3172

docs: suggest using view.resize with streaming data

---

.github/workflows/test.yml
package.json

See https://nodejs.org/en/about/releases/

ci: remove node 10 support

---

site/ecosystem.md

Added [Deneb](https://deneb-viz.github.io), which is a Power BI custom visual for authoring Vega-Lite and Vega visualizations.

docs: update ecosystem.md

---

src/config.ts
test/config.test.ts

fix: correctly merge object-valued config properties

---

examples/compiled/selection_multi_condition.vg.json
src/compile/selection/point.ts
test/compile/selection/point.test.ts

fix: prevent brush marks from triggering point selections

---

site/ecosystem.md

Mention these projects, written in Elixir:
- VegaLite (bindings for the Elixir programming language)
- Livebook (interactive and collaborative notebooks that supports VegaLite visualisations)

docs: add related projects from the Elixir community

---

site/_layouts/base.html

I have not used the data we have collected so I hope we can safely remove Google Analytics from our page.

chore: remove google analytics

---

site/examples/index.md

a new example inserted in line 61 and the title of my previous example in line 60 was slightly changed (from car sales to car registrations)

docs(examples): add rank-plot community example

---

site/examples/index.md

also changed the reference to jlborges in my two previous examples

docs: add dashboard community example

---

site/docs/encoding/legend.md

docs: add labelExpr to legend docs

---

bin/render.js

Fixes https://github.com/vega/vega-lite/discussions/7447

fix: apply config in CLI

---

site/ecosystem.md

add vega-lite-linter package and vizlinter editor

docs: add vega-lite-linter package and vizlinter editor to ecosystem page

---

examples/compiled/line_color_binned.vg.json
examples/compiled/point_binned_color.vg.json
src/channel.ts
src/compile/axis/assemble.ts
src/compile/common.ts
src/compile/mark/encode/valueref.ts
src/compile/scale/properties.ts
src/compile/scale/type.ts
test/compile/mark/point.test.ts

fix #7682 + some minor refactors

fix: make point mark work with ordinal bin

---

package.json
rollup.config.js
src/compile/data/expressions.ts
test/compile/axis/properties.test.ts
yarn.lock

Reduces file sizes of bundles but means we need Vega with our bundles, which I think it okay.

feat: externalize vega-expression and vega-event-selector

---

site/_data/link.yml

docs: fix link to single view spec.

---

site/docs/types/predicate.md

Replaced `'selection_filter_true' + this.value` with `'selection_filter_' + this.value`

docs: fix empty toggle

---

site/ecosystem.md

Rath is a augmented analysis tool based on vega lite

docs: add Rath to ecosystem

---

package.json
src/spec/index.ts

Also remove unused directories property.

chore: add keywords to package.json

---

site/Gemfile.lock
site/_layouts/page_submenu.html
site/_layouts/plain.html
site/static/main.css

https://twitter.com/housecor/status/1476910306702077954

feat[site]: use aria-current for more accessible navigation

---

site/ecosystem.md

Adds documentation line for an additional R package that provides interface with Vega-Lite
Please:
Tips:

docs: add additional R interface vegabrite to ecosystems page

---

.github/workflows/first-interaction.yml

Format the first-interaction workflow to follow the proper schema.
<details>
<summary>📦 Published PR as canary version: <code>5.5.1--canary.8369.26ef9b6.0</code></summary>
<br />
```bash
npm install vega-lite@5.5.1--canary.8369.26ef9b6.0
yarn add vega-lite@5.5.1--canary.8369.26ef9b6.0
```
</details>

fix: first interaction workflow yml

---

site/docs/parameter/parameter.md

docs: remove redundant word

---

examples/specs/point_offset_random.vl.json

docs: fix typo in "Dot Plot with Jittering" example

---

site/ecosystem.md

Related issues: https://github.com/Kanaries/graphic-walker/issues/17

docs: add graphic-walker to ecosystem

---

src/channel.ts
src/compositemark/boxplot.ts
src/compositemark/errorband.ts
src/compositemark/errorbar.ts

Need liquid 4.0.4 because of https://github.com/jekyll/jekyll/issues/9233. 
<details>
<summary>📦 Published PR as canary version: <code>5.6.1--canary.8660.619c272.0</code></summary>
<br />
```bash
npm install vega-lite@5.6.1--canary.8660.619c272.0
yarn add vega-lite@5.6.1--canary.8660.619c272.0
```
</details>

style: run linter

---

site/docs/mark/tick.md

docs: fix wording in docs

---

.github/workflows/release-docs-and-schema.yml
site/_includes/docs_toc.md

Removing deprecated https://github.com/alex-page/blazing-fast-gh-pages-deploy

chore: update site build script to use native github actions support

---

site/ecosystem.md

Related to [https://github.com/Kanaries/pygwalker/issues/13#issue-1592756921]()

docs: add PyGWalker to ecosystem

---

site/_layouts/page_submenu.html

docs: use correct anchor in submenu

---

build/vega-lite-schema.json
examples/specs/repeat_layer_size.json
src/spec/repeat.ts

Replaces https://github.com/vega/vega-lite/pull/8676
Fixes https://github.com/vega/vega-lite/issues/8523

fix: allow setting width/height in repeated layers

---

src/normalize/toplevelselection.ts

See comment in https://github.com/vega/vega-lite/pull/8733#issuecomment-1444171786

feat: stay backwards compatible

---

bin/render.js

This makes it easier for tools that run the cli tools to detect when something went wrong.

feat: return error exit code for cli tools

---

site/ecosystem.md

Would be great if this PR could be accepted to add Kibana to the ecosystem docs page. Wasn't 100% sure about the right section, hope this fits.

docs: add kibana

---

codecov.yml

chore: fix codecov

---

src/sort.ts

Comments were referenced in the docs.

docs: Fix spelling

---

.github/workflows/check-pr.yml

Using https://github.com/marketplace/actions/semantic-pull-request

ci: lint pull request messages

---

site/index.md

docs: remove blocks link from home page

---

site/index.md

Merge after #9118. Thanks to @keckelt for the idea.

docs: link to Vega project about page

---

examples/specs/bar_month.vl.json

Now it doesn't overflow anymore.

style: format example on the home page

---

CONTRIBUTING.md

Needs https://github.com/vega/.github/pull/2

docs: link to governance docs

---

build/vega-lite-schema.json
src/timeunit.ts

Redid https://github.com/vega/vega-lite/pull/8021 by @willium

fix: fix typo in time unit 'weekdayhours'

---

site/ecosystem.md

Include a new project that uses vega in production.

docs: add prolly to ecosystem

---

commitlint.config.js

We are not using this anymore.

chore: delete commitlint file

---

README.md

docs: update roadmap link

---

examples/specs/line_dynamic_axis.vl.json
site/_data/examples.json

https://github.com/vega/vega-lite/issues/9245
@domoritz  FYI

docs: Add dynamic axis example

---

site/ecosystem.md

docs: update ecosystem.md on Java binding in Smile

---

src/transform.ts
test/compile/data/extent.test.ts

fix: extent name collision in transforms

---

examples/compiled/bar_q_qpow.vg.json
src/log/message.ts
src/stack.ts
test/stack.test.ts

Clone of #9311 by @richardliu-db to fix CI issues. See that PR for details.

fix: Allow non-linear scale for stacked bars

---

.github/workflows/check-toc.yml
.github/workflows/check.yml
.github/workflows/release-docs-and-schema.yml
.github/workflows/test-docs.yml
.github/workflows/test.yml

needed because of https://github.com/Automattic/node-canvas/issues/2377

ci: use node 21

---

src/compile/data/parse.ts

Simply refactor -- (I wanna re-use this extract method in a follow up PR)

refactor: extract makeOutputNode() in data.parse()

---

site/ecosystem.md

Just a one line pointer in ecosystem.md for a vega-lite tool I created.  PR suggested by @domoritz .

docs: add entry for vega-view to ecosystem.md

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Enhancement.md
.github/PULL_REQUEST_TEMPLATE.md

I don't like to always see the boilerplate from the template so I moved it into a summary that can be expanded.

chore: reduce noise in files issues and PRs

---

site/examples/index.md

A diverging dot plot showing Nobel Prize laureates by gender and award year, using data from the Nobel Prize [API](https://www.nobelprize.org/organization/developer-zone-2/). 
@domoritz

docs: add diverging dot plot to community examples

---

test-runtime/animation.test.ts
test-runtime/util.ts

- remove animation tests that required sleeps
- remove sleep from first animation test
- fix signal setting and getting

feat: animation test runs correctly without sleeps

---

build/vega-lite-schema.json
site/_includes/docs_toc.md
site/docs/encoding.md
site/docs/encoding/type.md
site/ecosystem.md
src/sort.ts

Part of #9533 
This cherry picks a few PRs into main
https://github.com/vega/vega-lite/pull/8899
https://github.com/vega/vega-lite/pull/8946
https://github.com/vega/vega-lite/pull/8990
https://github.com/vega/vega-lite/pull/9109

Add missing docs commits from next

---

site/index.md

@lacepadilla does this look good to you?

docs: add link to Lace's videos

---

site/ecosystem.md

- Make it easier for users to discover the WordPress community integration for Vega-Lite

docs: Update Wordpress, GraphPad entries in Vega-Lite ecosystem

---

site/docs/transform/window.md

See https://github.com/vega/vega-lite/pull/9648

docs: update window.md to fix broken link
