vega/vega-lite

- src/data.js
- test/data.spec.js
I’m moving getSchema to data-ui’s `dataset.js` instead.
> remove getSchema & update test

- editor/editor.js
- gulpfile.js
- index.html
- lib/datalib.js
As we need to make it work on gh-pages, I add lib/datalib.js and gulp task for copying it from the installed node_module.
> update editor to use datalib.

- src/schema/schema.js
fixes #239 -  add median to schema (as datalib already supports this)
> add median to schema

- gulp/serve.js
- src/compile/marks.js
- src/schema/schema.js
- test/.jshintrc
- test/compile/marks.spec.js
- test/fixtures.js
- fixes #388  -- log broken with bar (set `y2 = {group:'height'}`, and `x2= {value:0}`) + unit test
- add offset for single bar + unit test
- also set serve task to use google chrome
> bar positioning 

- src/Encoding.js
- src/compile/style.js
- src/consts.js
- src/enc.js
- src/field.js
- src/globals.js
**Please merge #439 and #440 first**
- always use string type ('O', 'Q', 'T') instead of bitcode (1,2,4)
> Eliminate bitcode type 

- bower.json
- package.json
- src/Encoding.js
- src/compile/axis.js
- src/compile/legend.js
- src/compile/scale.js
- src/compile/time.js
- src/field.js
- src/schema/schema.js
- test/compile/axis.spec.js
- test/compile/time.spec.js
> #451 fn => timeUnit

- src/compile/scale.js
- src/field.js
- test/compile/scale.spec.js
> Fix bug for stacked bar chart

- src/compiler/scale.js
- src/field.js
- fixes https://github.com/uwdata/vega-lite-ui/issues/37
- use c10/20palette config
> Fix wrong data schema order 

- src/compiler/filter.js
Changed the array iteration logic to use classic for loops in two places.
> Fixed array iteration bug

- src/Encoding.js
- src/compiler/axis.js
- src/compiler/compiler.js
- src/compiler/marks.js
- src/schema/schema.js
#497 Dealing with axis label format without knowledge about integer.
> Axis label format (1st version)

- src/field.js
https://github.com/uwdata/vega-lite-ui/issues/41
> remove vl.field.order 

- gallery/gallery.js
- gulp/tests.js
- gulp/watch.js
- src/compiler/axis.js
- src/compiler/layout.js
- src/schema/schema.js
- test/compiler/axis.spec.js
Please merge #516 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/axisLabelOffset...kw/axis))
- extract & refactor methods
- add test for `axis.title`, `axis.orient` 
- for methods I haven't tested -- I added `FIXME` and will fix later -- Today I should fix show-stopping bug first.
- fixes wrong alignment for labels of axis on top #481
- add `orient`, `ticks`, `titleMaxLength`, `layer` in axisConfig and adjust `title` to be consistent with vega
- adjust gulp a little bit. 
- fix gallery.js
> Refactor Axis

- .jshintrc
- src/compiler/marks.js
- src/compiler/scale.js
- src/consts.js
- src/enc.js
- src/globals.js
- src/schema/schema.js
- test/.jshintrc
remove ALPHA from encoding, add `opacity` as COLOR field's property – fixes #520
> remove ALPHA from encoding, add `opacity` as COLOR field's property

- src/Encoding.js
- src/compiler/scale.js
- src/schema/schema.js
- test/compiler/scale.spec.js
@domoritz  this is probably good enough for the video - but need some clean-up after deadline — especially fixing tests.
> Better ordinal scale

- src/compiler/compiler.js
> only call stacked if the plot is aggregated

- gulp/tests.js
- package.json
> turn off istanbul by default, add gulp coverage to run istanbul

- src/Encoding.js
- src/compiler/compiler.js
- src/compiler/facet.js
- src/compiler/scale.js
- src/compiler/template.js
eliminiate unnecessary complexity in `encoding.data`
Please merge #544 first!
> eliminiate unnecessary complexity in `encoding.data`

- src/Encoding.js
- src/compiler/compiler.js
- src/compiler/facet.js
- src/compiler/scale.js
- src/compiler/sort.js
- src/compiler/template.js
- test/compiler/scale.spec.js
- test/compiler/sort.spec.js
Please merge 545 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/e.data...kw/de-sorting))
> eliminate `sorting.getDataset` as it's confusing.

- src/compiler/compiler.js
- src/compiler/data.js
- src/compiler/filter.js
- src/compiler/time.js
- src/field.js
- test/compiler/data.spec.js
- test/compiler/time.spec.js
migrate time transform to `data.raw.transform.time`
Please merge 550 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/data.raw.transform.filter...kw/transform.time))
> migrate time transform to data.raw.transform.time

- test/compiler/marks.spec.js
- test/fixtures.js
I have added unit tests for point and line. I am planning to add more tests for point and line as well other mark types. But before that wanted to check if I am going in the right direction.
> Added unit tests for point and line

- src/compiler/layout.js
- src/compiler/time.js
so that a test case doesn't simply fail because I'm in Thailand!
> Instantiate LONG_DATE constant using Date.UTC

- gallery/gallery.js
- src/compiler/axis.js
- src/compiler/compiler.js
- src/compiler/data.js
- test/compiler/data.spec.js
- test/compiler/stack.spec.js
- Migrate aggregate and bin transform to Vega 2.
- Add Aggregate Bar Chart to the gallery
> Aggregate, Facet, Subfacet, and Bin for Vega 2

- src/Encoding.js
- src/compiler/data.js
- src/compiler/stack.js
- src/schema/schema.js
- add stack control to COLOR and DETAIL 
- add default sortby
Fixes #39 and address #634
> add stack control to COLOR and DETAIL and add default sortby

- src/Encoding.js
- src/compiler/stack.js
- src/schema/schema.js
> Revert "Make `stack` either boolean or object"

- src/schema/schema.js
@jheer Thanks for the heads-up.
> update schema for stack's `offset`

- docs/Data.md
- docs/Documentation.md
- docs/Encoding-Mapping.md
Home, Contribute, Roadmap pages are still in the wiki as those are not version dependent. 
Fixes #645
> moving docs to the main repo

- docs/Data.md
- docs/Documentation.md
- docs/Encoding-Mapping.md
- src/schema/schema.js
- filter, formulas, aggregation operations
> Update doc regarding recent changes

- src/Encoding.js
Remove `Encoding.toggleFilterNullO`, which should just be a part of `vega-lite-ui`
Address part of #598
> remove Encoding.toggleFilterNullO

- .gitignore
- README.md
- gulp/schema.js
- scripts/deploy.sh
Better version of https://github.com/vega/vega-lite/pull/681
> Rename spec.son -> vega-lite-spec.json

- editor/bower.json
- gallery/bower.json
- package.json
- src/compiler/compiler.js
- src/compiler/data.js
- test/compiler/data.spec.js
https://github.com/vega/vega/pull/388
Requires update to vega 2.3.
Also help remove `stats` from data (one TODO in #648)
> Use new vega 2.3 bin transform

- docs/Encoding-Mapping.md
- src/compiler/axis.js
(The new bin scale will come in another PR)
> Fix bin grid's default as suggested by @domoritz

- src/compiler/compiler.js
- src/compiler/stack.js
- src/compiler/subfacet.js
- prepend impute transform to stack transform for stacked area chart
- also remove sort transform for stack area as stack transform now include sort already
> Fix broken stack for stack area chart using the impute transform

- .jshintrc
- src/Encoding.js
- src/compiler/data.js
- src/compiler/scale.js
- src/globals.js
- src/schema/schema.js
- test/.jshintrc
- test/compiler/data.spec.js
- test/compiler/scale.spec.js
- test/compiler/stack.spec.js
- raw => source
- aggregate => summary
fixes #587
> Rename data tables

- src/compiler/compiler.js
> only produces scales, axes, legends when they are non-empty

- src/Encoding.ts
- src/compiler/axis.ts
- src/compiler/data.ts
- src/compiler/layout.ts
- src/compiler/legend.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/compiler/time.ts
- src/consts.ts
- src/data.ts
- src/enc.ts
- src/fielddef.ts
- src/schema/fielddef.scale.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/schema.ts
- test/compiler/scale.test.ts
- test/fielddef.test.ts
> all caps for constants

- src/compiler/axis.ts
- src/consts.ts
- src/schema/schema.ts
- add missing filed to support dates properly
- remove dead code
- export schema.aggregate
Partially addresses https://github.com/vega/polestar/issues/348
> Various fixes

- docs/Data.md
- src/compiler/data.ts
- src/schema/data.schema.ts
> changing `formulas` to `calculate`

- src/Encoding.ts
- src/channel.ts
- src/compiler/axis.ts
- src/compiler/compiler.ts
- src/compiler/data.ts
- src/compiler/facet.ts
- src/compiler/layout.ts
- src/compiler/legend.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/compiler/style.ts
- src/compiler/time.ts
- src/consts.ts
- src/enc.ts
- src/validate.ts
- src/vl.ts
- test/compiler/marks.test.ts
- tsconfig.json
- extract `vl.encType` in `consts.ts` to become `vl.channel` in `channel.ts`
- rename
- vl.Enctype.LIST => vl.channel.CHANNELS
- local variable `et` and `encType` => `channel`
> extract `vl.encType` in `consts.ts` to become `vl.channel` in `channel.ts`

- README.md
- docs/Data.md
- docs/Documentation.md
- docs/Encoding-Mapping.md
- gallery/examples.js
- src/compiler/Model.ts
- src/compiler/data.ts
- src/compiler/layout.ts
- src/compiler/time.ts
- src/encoding.ts
- src/fielddef.ts
- src/schema/data.schema.ts
- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/schema.ts
- src/shorthand.ts
- test/compiler/axis.test.ts
- test/compiler/data.test.ts
- test/compiler/legend.test.ts
- test/compiler/scale.test.ts
- test/compiler/time.test.ts
- test/fielddef.test.ts
- test/fixtures.ts
- test/schema.test.ts
- test/validate.test.ts
> name => field

- docs/Config.md
- docs/Data.md
- docs/Documentation.md
- docs/Encoding-Mapping.md
- docs/Marktype.md
- src/compiler/Model.ts
- src/compiler/axis.ts
- src/compiler/compiler.ts
- src/compiler/data.ts
- src/compiler/facet.ts
- src/compiler/legend.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/compiler/stack.ts
- src/schema/config.schema.ts
- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/legend.schema.ts
- src/spec.ts
- test/compiler/axis.test.ts
- test/compiler/data.test.ts
> Improving docs!

- src/compiler/axis.ts
- src/compiler/layout.ts
- src/util.ts
> Deal with floating point instability in javascript

- src/compiler/Model.ts
> Making sure that short types are renamed before stack calculation

- src/compiler/Model.ts
- src/compiler/layout.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/schema/config.schema.ts
- test/compiler/marks.test.ts
part of #648 (remove stats & layout)
> have one simple bandWidth calculation

- src/channel.ts
- src/schema/encoding.schema.ts
- test/schema.test.ts
> Move supportedMarktype to channel.ts

- src/channel.ts
- src/compiler/axis.ts
- src/schema/fielddef.schema.ts
- remove weird aggregate count from only ordinalField
- remove deprecated rules for offset (we no longer use grid for row and column))
- comments
> Some minor revisions

- src/compiler/data.ts
- test/compiler/data.test.ts
> omit calculated field from `parse`  

- src/compiler/data.ts
> also calculate cardinality for binned field

- bin/vl2png
- bin/vl2svg
> Add vl2png and vl2svg

- README.md
- package.json
so we don't have to ask people to install it globally
> Add istanbul to deps

- src/util.ts
- be more explicit about methods we import from datalib
- remove datalib/src/stats dependency
> Update util import from datalib

- src/compiler/compiler.ts
- src/compiler/marks.ts
- optimize order of Vega output (make sure that `from` comes before `properties`)
- move the logic for adding `from.data` from compiler.ts to marks.ts
> optimize order of Vega output (make sure that `from` comes before `properties`)

- src/compiler/Model.ts
- test/compiler/axis.test.ts
- test/compiler/data.test.ts
- test/compiler/legend.test.ts
- test/compiler/scale.test.ts
> Auto drop unsupported channel from the spec 

- src/compiler/Model.ts
- src/compiler/axis.ts
- src/compiler/compiler.ts
- src/compiler/facet.ts
- src/compiler/legend.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/encoding.ts
See log for each commit for more details. 
Fixes #819
> Add name as prefix to mark group and scale’s name 

- src/channel.ts
- src/compiler/marks.ts
- src/schema/encoding.schema.ts
This will be allow @willium to focus on the task rather than these scaffolding when he does #64  (and possibly later #240).
> provide scaffolding for label encoding

- src/compiler/Model.ts
- src/compiler/legend.ts
- src/compiler/marks.ts
- src/compiler/scale.ts
- src/schema/config.marks.schema.ts
- src/schema/config.schema.ts
(For consistency with `config.cell`  and the new `config.label`)
> Rename `config.marks` => `config.mark` and `marksConfig` => `markConfig`

- src/compiler/Model.ts
- src/compiler/axis.ts
- src/compiler/compiler.ts
- src/compiler/data.ts
- src/compiler/facet.ts
- src/compiler/layout.ts
- need to use `typeof` to make TS compilation pass
> add `interface Layout` + extract `compilerRootGroup`

- src/compiler/legend.ts
Fix broken legend color (Fixes #915) + add stroke transparent
> Fix broken legend color (Fixes #915) + add stroke transparent

- docs/config.md
- src/compiler/marks.ts
- src/schema/config.marks.schema.ts
> Make `tickSize` a mark config and set it to 1 by default.

- docs/encoding.md
> Fix levels

- site/gallery.css
Quick fix for #930. 
Tested in:
> Fix gallery flexbox in Safari and Chrome

- src/compile/data.ts
> Include bin_range in the output `aggregate` transform when binned field uses ordinal scale

- src/compile/Model.ts
- src/compile/axis.ts
- src/compile/legend.ts
- test/compile/Model.test.ts
- test/compile/axis.test.ts
- test/compile/legend.test.ts
- test/compile/mark-area.test.ts
- test/compile/mark-bar.test.ts
- test/compile/mark-line.test.ts
- test/compile/mark-point.test.ts
- test/compile/mark-tick.test.ts
- test/compile/scale.test.ts
- the refactor part should provide some structure for our junior colleague’s unit-test exercises
> format => formatMixins & provide scaffold for unit test

- src/compile/mark-area.ts
- src/compile/mark-bar.ts
- src/fielddef.ts
Quick fix allows for suffix to be added to fields as an option, for use with stacked bar. As proposed by @kanitw here: https://github.com/vega/vega-lite/pull/978#discussion_r50604826.
> add suffix to fieldDefOption for stack usage

- examples/transparent_layer_bar.json
- examples/vlexamples.json
> Transparent layer bar is added to examples

- src/compile/mark-bar.ts
- test/compile/mark-bar.test.ts
> Make bar also works for negative values

- src/fielddef.ts
Follow-up fix for bug caused by #983.
@willium – Please run the gallery to make sure you don’t break things. 
This is partly my fault because I didn't catch this during code review.  
(And ideally I should pull down the branch and do gallery check too.)
> Implement correct suffix behavior. 

- test/compile/mark-bar.test.ts
- test/compile/mark-line.test.ts
- test/compile/mark-point.test.ts
- test/compile/mark-tick.test.ts
> Test markType for mark-*.test.ts

- examples/trellis_scatter.json
- src/schema/config.schema.ts
- test/compile/mark-text.test.ts
- test/compile/util.test.ts
Undoes the default format change from #962
> Change default number format to SI units.

- test/compile/mark-point.test.ts
> Test “fill” of square and circle mark 

- src/compile/scale.ts
> Normalized Stacked Bar Chart

- docs/config.md
- src/channel.ts
- src/compile/mark.ts
- src/compile/scale.ts
- src/schema/config.marks.schema.ts
- src/schema/encoding.schema.ts
Note: Documentation will be written in another huge doc writing PR.
> Add `path` channel for sorting line's path + Replace `config.mark.sortLineBy`

- docs/mark.md
This page is great overall - just suggested some small rewordings and edits..
> Update mark.md with minor edits

- test/compile/mark-tick.test.ts
add a test for mark-tic, fixed y with quantitative and hard code model.fieldDef(X).scale.bandWidth / 2 to be 10.5
> Add mark tick test

- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- Declare schema for all types of fields inside field.schema.ts
- Make all channels support aggregate
> Refactor FieldDef Schema

- src/compile/mark-tick.ts
- test/compile/mark-tick.test.ts
i did the similar thing as mark bar, but still not sure if this what we expected about size of mark-tick? #932
> [WIP]support size for mark-tick

- src/compile/facet.ts
> Support hiding facet axis

- src/compile/Model.ts
> Make 1D stack bar chart works

- examples/bar_layered_transparent.json
- site/docs/mark.md
Still need to fill in more examples
> A pass over mark.md

- site/docs/axis.md
- src/compile/axis.ts
- src/schema/axis.schema.ts
- test/compile/axis.test.ts
Add axis property: `labelAngle`
> Add a labelAngle property to axis. Fix #939

- examples/ordinal_color.json
- examples/scatter_binned_color.json
- examples/timeunit_color.json
- examples/vl-examples.json
- src/compile/Model.ts
- src/compile/data.ts
- src/compile/legend.ts
- src/compile/mark-text.ts
- src/compile/scale.ts
- src/compile/util.ts
- src/fielddef.ts
- test/compile/scale.test.ts
> Ordinal color scales

- site/docs/axis.md
- site/docs/legend.md
Instead of a large, ugly table.  I cluster the properties into groups.
> Re-group axis.md

- site/docs/scale.md
- site/static/main.css
and add bottom margin to `<dd>`
> scale.md: add more description about scale type, add log scale example.

- src/compile/Model.ts
- src/compile/data.ts
- src/compile/facet.ts
- src/compile/legend.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/compile/util.ts
- src/schema/config.schema.ts
- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/legend.schema.ts
- src/schema/sort.schema.ts
- test/compile/scale.test.ts
Please merge #1107 first!  
(See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/channelDef...kw/legend-config))
> Remove `legend` from FieldDef, add `config.legend` and initialize it correctly

- site/docs/axis.md
- src/compile/Model.ts
- src/compile/axis.ts
- src/compile/data.ts
- src/compile/facet.ts
- src/compile/legend.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/compile/util.ts
- src/schema/axis.schema.ts
- src/schema/config.facet.schema.ts
- src/schema/config.schema.ts
- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/legend.schema.ts
- src/schema/sort.schema.ts
- test/compile/scale.test.ts
- tsconfig.json
Please merge #1108 first and see c097395.
> Remove `axis` from FieldDef, add `config.axis` and initialize it correctly

- examples/bar_grouped.json
- site/docs/axis.md
- src/compile/Model.ts
- src/compile/axis.ts
- src/compile/data.ts
- src/compile/facet.ts
- src/compile/legend.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/compile/util.ts
- src/schema/axis.schema.ts
- src/schema/config.facet.schema.ts
- src/schema/config.schema.ts
- src/schema/encoding.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/legend.schema.ts
- src/schema/sort.schema.ts
- test/compile/scale.test.ts
- tsconfig.json
Add axisWidth and use it in the bar_group example
(A follow-up for facet layout is following this PR and another layout refactor PR)
merge #1109 first    (See [branch specific diff](https://github.com/vega/vega-lite/compare/kw/axis-config...kw/axisWidth))
> Add axisWidth

- src/compile/data.ts
- src/compile/legend.ts
> Add rank transform after aggregation, simplify legend logic.

- src/compile/compile.ts
- src/compile/data.ts
- src/compile/layout.ts
- src/schema/vega.schema.ts
- test/compile/data.test.ts
- tsconfig.json
Its flow would be different from normal data in composition.
Normal data will be populated with pre-order traversal while layout data will have post-order traversal.
> Move layout data to layout.ts 

- site/docs/scale.md
- src/compile/Model.ts
- src/compile/data.ts
- src/compile/facet.ts
- src/compile/layout.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/compile/util.ts
- src/schema/bin.schema.ts
- src/schema/config.facet.schema.ts
- src/schema/config.schema.ts
- src/schema/fielddef.schema.ts
- src/schema/scale.schema.ts
- test/compile/scale.test.ts
- Add scale config, replace constants with config, remove default values from config
- remove schema.instantiate + perform necessary fixes to eliminate null pointer errors
> Migrate scale default value to config + remove schema.instantiate

- site/docs/config.md
- site/docs/scale.md
- site/static/main.css
- src/compile/scale.ts
- src/schema/scale.schema.ts
Feel free to go ahead and fix typos.
> Add missing scale config + Update Scale Docs

- site/gallery.md
- site/index.md
- site/static/main.css
> Add large buttons to home page

- examples/specs/bar_aggregate.json
- examples/specs/bar_aggregate_size.json
- examples/specs/bar_grouped.json
- examples/specs/bar_layered_transparent.json
- examples/specs/stacked_bar_normalize.json
- examples/specs/stacked_bar_population.json
- examples/specs/tick_dot_thickness.json
- examples/specs/trellis_bar.json
- examples/specs/trellis_barley.json
- site/docs/config.md
- site/docs/encoding.md
- site/docs/mark.md
- site/docs/scale.md
- site/docs/size.md
- src/compile/Model.ts
- src/compile/layout.ts
- src/compile/mark-tick.ts
- src/compile/scale.ts
- src/schema/config.mark.schema.ts
- src/schema/scale.schema.ts
Note that textBandWidth remains "width" because it is only applied to x-scale :)
> Scale's bandWidth => bandSize

- _layouts/docs.html
- _layouts/page_submenu.html
- _layouts/tutorials.html
- site/docs/composition.md
- site/docs/encoding.md
- site/docs/layer.md
- site/static/main.css
- site/tutorials/explore.md
- site/tutorials/gettings_started.md
Not a lot to show yet, most of my work for the redesign has been in sketches or partial implementations. Not a big fan of any of the versions I've built yet, and they all break at some point. Opening this up for discussion -- will update this description with more information.
> [WIP] Docs redesign and updates

- examples/vl-examples.json
- site/index.md
- site/static/main.css
- site/static/main.ts
* Add solid 1px border to showcase
* Make gallery border thinner
> Modify borders for showcase and gallery

- site/static/main.ts
- site/static/test-gallery.ts
- src/compile/Model.ts
- src/compile/compile.ts
- src/compile/data.ts
- src/compile/legend.ts
- src/compile/mark-area.ts
- src/compile/mark-line.ts
- src/compile/mark-point.ts
- src/compile/mark-tick.ts
- src/compile/mark.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/encoding.ts
- src/fielddef.ts
- src/shorthand.ts
- src/spec.ts
- src/util.ts
Fixes #907. Just a general plumbing thing, I thought would be nice for v1.
> Convert all vars to const or let where applicable

- site/static/main.ts
> Make file urls absolute so they work in the deployed editor

- site/docs/docs.md
- site/static/main.css
Should fix FF bug, Safari bug, and italicized optional for readability
> fix docs presentation and bugs in FF/Safari

- examples/specs/bar_aggregate_vertical.json
- examples/specs/histogram.json
- examples/specs/scatter_binned.json
- examples/vl-examples.json
- site/docs/bin.md
- update binned scatter plot and histogram to use the medium example.
- add binned scatter plot to the examples gallery.
- update bin.md accordingly
@domoritz  @willium
> Update for consistency with the Medium article

- src/compile/Model.ts
- src/compile/axis.ts
- src/compile/compile.ts
- src/compile/facet.ts
- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- src/compile/mark/point.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- src/compile/scale.ts
- test/compile/scale.test.ts
> Simplify model - removing unnecessary methods 

- src/compile/facet.ts
This fixes all but one of the failures in #1156
> Make count op an array to conform to vega schema

- examples/examples.test.ts
Fixes https://github.com/vega/vega-lite/issues/1156
> Copy the "validate generated vega spec against vega schema"

- src/compile/legend.ts
> Only omit fill/stroke config if the legend's channel is COLOR

- test/compile/axis.test.ts
- test/compile/common.test.ts
- test/compile/compile.test.ts
- test/compile/data.test.ts
- test/compile/legend.test.ts
- test/compile/mark/area.test.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/line.test.ts
- test/compile/mark/mark.test.ts
- test/compile/mark/point.test.ts
- test/compile/mark/text.test.ts
- test/compile/mark/tick.test.ts
- test/compile/scale.test.ts
- test/util.ts
> `parseModel` => `parseUnitModel`, `parseAnyModel` => `parseModel`

- src/compile/common.ts
- src/compile/mark/line.ts
- src/compile/mark/rule.ts
- src/compile/scale.ts
- src/compile/unit.ts
- src/config.ts
- src/scale.ts
See commit logs for more details
> Fixing sizing, config order

- src/compile/scale.ts
- src/scale.ts
> Add tickSizeRange

- site/docs/scale.md
> Correct a typo in size scales description

- src/compile/mark/tick.ts
- test/compile/mark/tick.test.ts
Fix #1276 , the problem of inverted tick orient.
> Tick mark orient inverted

- site/docs/scale.md
> Add documentation for tickSizeRange

- examples/specs/stacked_bar_opacity.json
- site/docs/encoding.md
- src/channel.ts
- src/compile/common.ts
- src/compile/mark/mark.ts
- src/compile/scale.ts
- src/compile/stack.ts
- src/encoding.ts
- src/scale.ts
> add opacity channel

- site/docs/legend.md
- src/compile/legend.ts
- src/legend.ts
- test/compile/legend.test.ts
Add some rules to legend properties.
All properties tested in editor and all worked correctly.
Working on adding unit tests and determining some matching between vega and vega-lite.
> Legend Properties

- _includes/docs_toc.md
- _layouts/plain.html
- _layouts/usage.html
- site/usage/applications.md
Quick fix of documentation site (see issue #1343)
> renamed integrations to applications. fixes #1343

- examples/specs/bubble_health_income.json
> Cite Lisa's blog article in health vs income example

- CONTRIBUTING.md
* Fix numbered list for github markdown
* Put some inline commands into code blocks
> Fix numbered list in contribution.md "Repository Setup" section

- examples/specs/line_quarter.json
- src/compile/axis.ts
- src/compile/common.ts
- src/compile/legend.ts
- src/compile/mark/text.ts
- src/timeunit.ts
- test/compile/axis.test.ts
- test/compile/common.test.ts
- test/compile/legend.test.ts
Please review and see if it works correctly.
> Use templates everywhere instead of format and formatType or template.

- src/compile/scale.ts
refactor scale -- remove multi-level condition operator. (It's impossible to add breakpoint to debug)
cc @domoritz
> refactor scale -- remove multi-level condition operator.

- examples/specs/box_plot.json
- src/compile/mark/bar.ts
- src/compile/stack.ts
- src/encoding.ts
- test/compile/mark/bar.test.ts
- test/compile/stack.test.ts
> added X2/Y2 to bar mark with tests. Added basic box plot example.

- src/spec.ts
- test/spec.test.ts
> Normalization of UnitSpec

- src/compile/mark/area.ts
- src/compile/mark/line.ts
- src/compile/mark/point.ts
- src/compile/mark/tick.ts
- src/vega.schema.ts
Addressing #1284 except for `bar`
> Refactor area, line and point in mark.

- src/mark.ts
- src/spec.ts
> Added Error Bar Composite Mark

- examples/specs/bar_yearmonth.json
- examples/specs/bubble_health_income.json
- examples/specs/layer_line_color_rule.json
- examples/specs/line.json
- examples/specs/line_color.json
- examples/specs/line_detail.json
- examples/specs/line_monotone.json
- examples/specs/line_month.json
- examples/specs/line_step.json
- examples/specs/point_dot_timeunit_color.json
- examples/specs/stacked_bar_size.json
- examples/specs/stacked_bar_weather.json
- site/docs/data.md
- src/compile/data/source.ts
- src/data.ts
- test/compile/data.test.ts
- Change formatType to be format.type
- Add topojson to format.type for geopath
- Add format.feature and format.mesh
- Update examples to adapt the new syntax
> decouple formatType to be format.type

- src/compile/axis.ts
- src/compile/common.ts
- src/compile/legend.ts
- src/compile/mark/text.ts
- src/timeunit.ts
- src/vega.schema.ts
- test/compile/common.test.ts
- test/compile/legend.test.ts
- test/compile/mark/text.test.ts
- test/compile/timeunit.test.ts
- split methods inside `text` marks
- change `formatMixins` => `numberFormat`
> Refactor text mark, timeFormat, timeTemplate

- site/docs/transform.md
- src/compile/data/filter.ts
- src/filter.ts
- test/compile/data/filter.test.ts
- test/filter.test.ts
> Remove gt,lt,gte,lte filter.

- site/docs/transform.md
- src/compile/config.ts
- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- src/compile/mark/mark.ts
- src/compile/mark/rule.ts
- src/compile/mark/tick.ts
- src/compile/scale.ts
- src/config.ts
- test/compile/config.test.ts
- tsconfig.json
With tests. 
Also contained in #1304
> Extract function to compute orientation

- src/compile/mark/area.ts
- test/compile/mark/area.test.ts
Fix broken horizontal area chart (after merging @ayush29feb's area branch) & Add more test coverage.
> Fix broken horizontal area chart

- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- test/compile/mark/area.test.ts
- test/compile/mark/bar.test.ts
Very quick fix for #1505.   @felixcodes will add unit tests later. 
@shrjain For now, can you verify if this works correctly for you?  Thanks!
> Fix bar/area for log scale and zero = false

- src/compile/mark/mark.ts
> Correctly sort line chart when the dimension axis has sort property

- src/compile/mark/area.ts
> [WIP] Simplify confusing logic for area mark

- site/docs/transform.md
The sentence was not complete before - please correct if I misinterpreted what it should be.
> Complete sentence in datetime docs

- _layouts/page_submenu.html
I was getting some annoying warnings, so I just refactored a bit
> Fix warnings in jekyll

- _config.yml
- _layouts/plain.html
> Fix broken links for "edit this page" per #1358

- src/compile/config.ts
- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- src/compile/mark/line.ts
- src/compile/mark/point.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- src/compile/mark/valueref.ts
- src/fielddef.ts
- test/compile/config.test.ts
- test/compile/mark/bar.test.ts
- tsconfig.json
(You might wanna review each commit individually)
> Refactor Marks

- examples/specs/rect_heatmap.vl.json
- examples/vl-examples.json
- site/docs/mark.md
- src/channel.ts
- src/compile/config.ts
- src/compile/layout.ts
- src/compile/mark/mark.ts
- src/compile/mark/rect.ts
- src/compile/scale.ts
- src/compile/unit.ts
- src/mark.ts
- src/scale.ts
- test/compile/layout.test.ts
- test/compile/mark/rect.test.ts
> Add Rect and Heatmap Example

- src/compile/mark/rule.ts
- src/stack.ts
- test/compile/mark/rule.test.ts
- test/stack.test.ts
> Allow Rule to be stacked (for consistency)

- examples/examples.test.ts
- package.json
- site/static/test-gallery.ts
- src/compile/axis.ts
- src/compile/config.ts
- src/compile/data/bin.ts
- src/compile/layer.ts
- src/compile/layout.ts
- src/compile/mark/bar.ts
- src/compile/mark/mark.ts
- src/compile/mark/rect.ts
- src/compile/mark/valueref.ts
- src/compile/model.ts
- src/compile/scale.ts
- src/compile/unit.ts
- src/log.ts
- src/scale.ts
- src/timeunit.ts
- src/vega.schema.ts
- test-gallery.html
- test/compile/axis.test.ts
- test/compile/scale.test.ts
- test/timeunit.test.ts
- typings/vega-lite.d.ts
- typings/vega.d.ts
- vega-lite-schema.json
Replace existing ordinal scale with the new 3 discrete scale types
- remove `points` from Scale interface
> Scale & Axis Migration MVP

- src/compile/data/bin.ts
- src/compile/data/colorrank.ts
- src/compile/data/data.ts
- src/compile/data/filter.ts
- src/compile/data/formula.ts
- src/compile/data/nonpositivefilter.ts
- src/compile/data/nullfilter.ts
- src/compile/data/source.ts
- src/compile/data/stackscale.ts
- src/compile/data/summary.ts
- src/compile/data/timeunit.ts
- test/compile/data/formula.test.ts
- test/compile/data/nonpositivefilter.test.ts
- test/compile/data/stackscale.test.ts
- test/compile/data/summary.test.ts
> Make each part of data `assemble` only takes relevant part as input

- src/channel.ts
- src/compile/scale.ts
- src/scale.ts
- test/channel.test.ts
- test/compile/scale.test.ts
- vega-lite-schema.json
> Check if a scale type is supported by a channel

- src/compile/mark/bar.ts
- src/compile/mark/point.ts
- src/compile/mark/rect.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- src/compile/mark/valueref.ts
- src/vega.schema.ts
- test/compile/mark/point.test.ts
See commits for details. 
(The latter is probably useful when we layer point scale over band scale.)
> Correct ValueRef Util for midPoint

- .travis.yml
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-supports-yarn
> Add proper yarn support for travis

- site/tutorials/explore.md
> gallery.html is 404

- src/compile/scale.ts
- src/config.ts
- src/mark.ts
- src/scale.ts
- test/compile/scale.test.ts
- vega-lite-schema.json
> Move mark-specific size scaleRange to mark specific config

- src/bin.ts
- src/compile/data/bin.ts
- src/compile/scale.ts
- src/fielddef.ts
- test/compile/data/bin.test.ts
- test/compile/data/data.test.ts
- test/compile/mark/area.test.ts
- test/compile/mark/point.test.ts
- test/compile/scale.test.ts
- vega-lite-schema.json
- Add extent transform if `bin.extent` is not specified
- Rename `div` to `divide`
- Add more JSON schema annotation
> Steps to make histogram work

- src/compile/legend.ts
- src/legend.ts
- test/compile/legend.test.ts
> Use gradient legend for continuous color scale

- examples/specs/scatter_color_zindex.vl.json
- examples/specs/scatter_connected.vl.json
- src/channel.ts
- src/compile/config.ts
- src/compile/facet.ts
- src/compile/scale/init.ts
- src/compile/scale/parse.ts
- src/compile/scale/range.ts
- src/compile/scale/type.ts
- src/compile/unit.ts
- src/encoding.ts
- src/log.ts
- src/spec.ts
- test/compile/mark/point.test.ts
- test/compile/scale/init.test.ts
- test/compile/scale/range.test.ts
- test/compile/scale/type.test.ts
- test/spec.test.ts
- vega-lite-schema.json
(Please merge #1784 and their dependencies first!)
See [branch specific diff](https://github.com/vega/vega-lite/compare/kw/scale-extract...kw/range-mixins) or see each commit for details.
> Consolidate rangeMixins to be the only one method that deals with range properties + refactor

- src/compile/data/base.ts
- src/compile/data/bin.ts
- src/compile/data/filter.ts
- src/compile/data/formatparse.ts
- src/compile/data/formula.ts
- src/compile/data/nonpositivefilter.ts
- src/compile/data/nullfilter.ts
- src/compile/data/stack.ts
- src/compile/data/timeunit.ts
- src/vega.schema.ts
- test/compile/data/filter.test.ts
(This is a follow-up to #1776 to make all data component compiler implements the same interface.)
> Rename `AbstractDataCompiler` => `DataComponentCompiler` and use it.

- src/compile/axis/parse.ts
- src/compile/axis/rules.ts
- src/compile/facet.ts
- src/compile/model.ts
- test/compile/axis/parse.test.ts
- test/compile/axis/rules.test.ts
> Split between main and grid scale + Refactor 

- src/compile/layout.ts
- test/compile/layout.test.ts
Fix #1807
The output look good now!
> Fix incorrect layout for point scales

- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- src/compile/mark/base.ts
- src/compile/mark/line.ts
- src/compile/mark/mark.ts
- src/compile/mark/point.ts
- src/compile/mark/rect.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- test/compile/mark/area.test.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/line.test.ts
- test/compile/mark/point.test.ts
- test/compile/mark/rect.test.ts
- test/compile/mark/rule.test.ts
- test/compile/mark/text.test.ts
- test/compile/mark/tick.test.ts
> MarkCompiler interface	

- package.json
- src/compile/data/stack.ts
- src/compile/unit.ts
- src/encoding.ts
- src/stack.ts
- test/stack.test.ts
- yarn.lock
> Typescript 2.1 compatible

- src/compile/common.ts
- src/compile/config.ts
- src/compile/data/pathorder.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/layout.ts
- src/compile/mark/mark.ts
- src/compile/mark/text.ts
- src/compile/model.ts
- src/compile/scale/parse.ts
- src/compile/unit.ts
- src/encoding.ts
- src/spec.ts
- src/stack.ts
Fix #1432
Please merge #1814 first!
> [Refactor] has => channelHasField

- src/compile/compile.ts
- test/compile/compile.test.ts
Fix #1813
@arvind -- FYI, this is a little redundant with what you already did in the selection PR, but we need this in order to get alpha.0 out.
> Fix facet layout by adding width and height signals to the top-level

- src/spec.ts
- vega-lite-schema.json
Towards https://github.com/vega/vega/issues/448
> Allow URL to JSON schema for this spec

- src/filter.ts
Doesn't matter right now but I'm making some changes and it will matter. Right now we just get consistency.
> Use [] instead of Array

- src/compile/axis/parse.ts
- src/compile/data/formula.ts
- src/compile/data/nonpositivefilter.ts
- src/compile/data/summary.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/legend/parse.ts
- src/compile/model.ts
- src/compile/scale/parse.ts
- src/compile/unit.ts
- src/timeunit.ts
> [Refactor] Remove `as Dict<...>`

- site/tutorials/explore.md
> Fix link to getting_started

- src/scale.ts
- typings/vega-util.d.ts
I'm not even sure whether these type annotations are still necessary.
> index scale has discrete domain.

- src/compile/axis/parse.ts
- src/compile/data/data.ts
- src/compile/scale/parse.ts
- typings/vega-util.d.ts
(We try to be as descriptive as possible to reduce cognitive load for code readers to remember type of each variable.)
> [WIP] Rename variables to be more consistent with the rest of the codebase.

- src/compile/scale/init.ts
- src/compile/scale/range.ts
- src/compile/scale/scale.ts
- src/scale.ts
as it can be reused in other project such as CQL
> Move `channelScalePropertyIncompatability` to `src/scale` 

- src/compile/data/formatparse.ts
- src/compile/data/source.ts
- src/compile/layer.ts
- src/data.ts
- vega-lite-schema.json
> Split Data Interface (Data = UrlData | InlineData)

- src/compile/layer.ts
- src/compile/scale/domain.ts
- src/compile/scale/init.ts
- src/compile/scale/parse.ts
- src/compile/scale/range.ts
- src/compile/scale/scale.ts
- src/log.ts
- src/util.ts
- src/vega.schema.ts
- test/compile/layer.test.ts
- test/compile/scale/domain.test.ts
- test/compile/scale/parse.test.ts
- test/compile/scale/range.test.ts
Fixes https://github.com/vega/vega-lite/issues/1870
> Correct Vega schema for rangeStep

- src/config.ts
- vega-lite-schema.json
(These should be just passed to Vega)
> Add Range Config to schema.

- src/aggregate.ts
- src/axis.ts
- src/compile/axis/rules.ts
- src/compile/common.ts
- src/compile/data/summary.ts
- src/compile/facet.ts
- src/compile/scale/domain.ts
- src/compile/scale/parse.ts
- src/config.ts
- src/data.ts
- src/fielddef.ts
- src/scale.ts
- src/sort.ts
- src/spec.ts
- src/stack.ts
- test/fielddef.test.ts
- test/stack.test.ts
Again, I'm so sorry for deleting and changing the pull request. I just figured out my git history tree was too messed up, so I decided to restore everything and create my own branch to start working on this. 
I have several questions regarding git:
1) How should I update the master branch into my working branch so that I always get the latest official version? Is `git rebase -i` a better option than `git merge`?
2) Should I do `git rebase -i` to clean up all of my commits every time a new namespace is removed?
> [WIP] remove string literals constant

- examples/specs/box_plot.vl.json
- examples/specs/errorbar_aggregate.vl.json
- examples/specs/errorbar_horizontal_aggregate.vl.json
- examples/specs/layer_bar_line.vl.json
- examples/specs/layer_bar_line_union.vl.json
- examples/specs/layer_histogram.vl.json
- examples/specs/layer_line_color_rule.vl.json
- examples/specs/overlay_area_full.vl.json
- examples/specs/overlay_line_full.vl.json
- src/compile/layer.ts
- src/spec.ts
- test/compile/layer.test.ts
- test/compile/model.test.ts
- test/spec.test.ts
- vega-lite-schema.json
(just like facet, concat, repeat)
> [Syntax] Layer operator should be a verb form, not plural 

- src/axis.ts
- src/compile/axis/parse.ts
- src/compile/legend/parse.ts
- src/compile/scale/init.ts
- src/legend.ts
- src/log.ts
- src/scale.ts
- vega-lite-schema.json
Fix #1781 
Added more vg3 new properties to axis/legend/scale interface.
All the new features have been manually tested.
> Added more properties for axis/legend/scale

- .travis.yml
- package.json
- scripts/check-schema.sh
I just started working on this pull request and I am stuck on how to proceed and what is the right way to fix the issue. So far I have added the `npm run schema`, but I'm not sure how I should make the test fail if the schema file is different than the committed one. Do I add another test case inside `schema.test.ts` or write a shell script to execute when the `npm run test` is called to check git status?
> [WIP] Add a Unit Test to test if the vega-lite-schema.json is up to date #1773

- src/channel.ts
- src/compile/scale/type.ts
- test/channel.test.ts
- test/compile/scale/type.test.ts
Move the rangeFunc to channel from type
> quick refactor, move rangeFunc to channel

- package.json
- src/compile/axis/encode.ts
- src/compile/data/bin.ts
- src/compile/facet.ts
- src/compile/legend/parse.ts
- src/compile/mark/area.ts
- src/compile/mark/line.ts
- src/compile/mark/mark.ts
- src/fielddef.ts
- test/compile/axis/rules.test.ts
- test/compile/data/stack.test.ts
- test/compile/data/summary.test.ts
- test/compile/mark/area.test.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/rule.test.ts
- test/compile/mark/tick.test.ts
- test/compile/scale/domain.test.ts
- test/compile/scale/parse.test.ts
- tslint.json
> Add lint for space standarization

- src/compile/mark/text.ts
- src/encoding.ts
- src/fielddef.ts
- src/mark.ts
- test/compile/mark/text.test.ts
- vega-lite-schema.json
Also remove config.text.format, Fixes #1762
> Add format for text field def

- examples/examples.test.ts
> Make example validate test check for $schema

- src/compile/unit.ts
- src/compositemark.ts
- src/mark.ts
- src/spec.ts
- src/stack.ts
- src/validate.ts
- test/compile/unit.test.ts
- vega-lite-schema.json
merge #1940 first
Fix https://github.com/vega/vega-lite/issues/1882
> Make mark property can be either mark type or mark definition

- src/compile/common.ts
- src/compile/mark/common.ts
- test/compile/mark/point.test.ts
> Remove config for fill/stroke configs + Correctly read color config

- src/compile/mark/mixins.ts
- src/compile/mark/text.ts
- src/compile/mark/valueref.ts
This is a prep for production rule (Forgot to include in the previous PR)
> Add a mixin for text channel.

- src/compile/scale/domain.ts
- src/compile/scale/init.ts
- src/scale.ts
- test/compile/scale/domain.test.ts
- test/compile/scale/parse.test.ts
- vega-lite-schema.json
> Replace scale.useRawDomain with scale.domain = ‘unaggregated’

- src/axis.ts
- src/vega.schema.ts
> `shortTimeLabels` is not VgAxisConfig

- src/axis.ts
- src/compile/axis/encode.ts
- src/config.ts
- src/legend.ts
- src/vega.schema.ts
- vega-lite-schema.json
Fix part of #1845 
Add description for new added axis/legend properties and config based on Vega docs.
> fix docs for axis/legend

- src/compile/scale/range.ts
- src/config.ts
- src/mark.ts
- src/scale.ts
- src/vega.schema.ts
- test/compile/legend/encode.test.ts
- test/compile/mark/point.test.ts
- test/compile/mark/text.test.ts
- test/compile/scale/range.test.ts
- vega-lite-schema.json
https://github.com/vega/vega-parser/blob/master/src/config.js
(Let's merge after Vega-3.0.0-beta.23 is released.)
> Update Mark Config

- build/vega-lite-schema.json
- src/compile/data/source.ts
- src/compile/model.ts
- src/data.ts
- test/compile/data/source.test.ts
Does not fully work yet because vega fails to compute layout when there is no data.  I consider that beyond the scope of this pr.
> Allow empty named data source. Fixes #1392

- examples/specs/bar_yearmonth.vl.json
- examples/specs/panzoom_scatter.vl.json
- src/channel.ts
- src/compile/facet.ts
- src/compile/mark/init.ts
- src/compile/scale/type.ts
- src/encoding.ts
- src/fielddef.ts
- src/timeunit.ts
- test/channel.test.ts
- test/compile/scale/type.test.ts
- test/fielddef.test.ts
Part of https://github.com/vega/compassql/issues/301
> FieldDef: Continuous/discrete/channelCompatibility

- examples/specs/bar_size_explicit.vl.json
- examples/specs/bar_size_explicit_bad.vl.json
- examples/specs/bar_size_fit.vl.json
- examples/specs/histogram.vl.json
- examples/specs/histogram_nospacing.vl.json
- examples/specs/layer_histogram.vl.json
- examples/specs/scatter_binned.vl.json
- examples/specs/stacked_bar_size.vl.json
- examples/specs/stacked_bar_weather.vl.json
- examples/specs/trellis_bar_histogram.vl.json
- src/encoding.ts
- src/fielddef.ts
- test/compile/data/data.test.ts
- test/compile/data/pathorder.test.ts
- test/compile/mark/area.test.ts
- test/compile/mark/point.test.ts
- test/stack.test.ts
Fix https://github.com/vega/vega-lite/issues/2015
(Yes, not important but I have 10 minute gap time)
> Support count without field = *

- .babelrc
- package.json
- site/static/main.ts
- site/tsconfig.json
- test-gallery/tsconfig.json
I don't think this is super clean but better than before.
> Use inline sourcemaps for site and test gallery

- src/channel.ts
- src/compile/mark/init.ts
- src/compile/mark/mark.ts
> Only apply opacity to bar if there is a raw level of detail channel

- src/compile/data/bin.ts
- src/compile/scale/domain.ts
- src/util.ts
- test/util.test.ts
Fix #2029
cc: @NeelMohapatra -- this is a small PR that will slightly affect your PR.
> Add varName method and apply it to bin's signal name

- examples/specs/bar_layered_transparent.vl.json
- src/compile/mark/init.ts
Fix #2027 and other relevant issues -- see commit message for details.
> Revise rules for opacity 

- build/vega-lite-schema.json
- src/axis.ts
- src/compile/axis/encode.ts
- src/compile/facet.ts
- src/compile/unit.ts
- src/config.ts
- src/vega.schema.ts
- test/compile/axis/encode.test.ts
- test/compile/facet.test.ts
- test/compile/unit.test.ts
- Remove `labelMaxLength` from VlOnlyAxisBase
- Add `labelLimit`, `titleLimit` to AxisConfig and LegendConfig
- Edit and delete related code
> remove labelMaxLength

- build/vega-lite-schema.json
- examples/vg-specs/bar.vg.json
- examples/vg-specs/bar_aggregate.vg.json
- examples/vg-specs/bar_aggregate_size.vg.json
- examples/vg-specs/bar_aggregate_vertical.vg.json
- examples/vg-specs/bar_filter_calc.vg.json
- examples/vg-specs/bar_layered_transparent.vg.json
- examples/vg-specs/bar_size_default.vg.json
- examples/vg-specs/bar_size_explicit.vg.json
- examples/vg-specs/bar_size_explicit_bad.vg.json
- examples/vg-specs/bar_size_fit.vg.json
- examples/vg-specs/bar_size_rangestep_small.vg.json
- examples/vg-specs/box_plot.vg.json
- examples/vg-specs/errorbar_aggregate.vg.json
- examples/vg-specs/errorbar_horizontal_aggregate.vg.json
- examples/vg-specs/layer_bar_line.vg.json
- examples/vg-specs/layer_bar_line_union.vg.json
- examples/vg-specs/line_slope.vg.json
- examples/vg-specs/rect_heatmap.vg.json
- examples/vg-specs/stacked_bar_h.vg.json
- examples/vg-specs/stacked_bar_h_order.vg.json
- examples/vg-specs/stacked_bar_normalize.vg.json
- examples/vg-specs/stacked_bar_population.vg.json
- examples/vg-specs/stacked_bar_sum_opacity.vg.json
- examples/vg-specs/stacked_bar_v.vg.json
- examples/vg-specs/tick_strip.vg.json
- examples/vg-specs/trellis_bar.vg.json
- examples/vg-specs/trellis_barley.vg.json
- examples/vg-specs/trellis_stacked_bar.vg.json
- src/config.ts
Fix #1935 
- Add `axisX`, `axisY`, `axisLeft`, `axisRight`, `axisTop`, `axisBottom` and `axisBand` in config.
> Add special axis config

- .travis.yml
- scripts/build-examples.sh
> [WIP] Enable parallel for build:example

- src/compile/facet.ts
- test/compile/facet.test.ts
> bring back the code to copy config.facet.axis

- build/vega-lite-schema.json
- src/bin.ts
- src/compile/data/bin.ts
- src/compile/data/data.ts
- src/compile/data/stack.ts
- src/compile/data/transforms.ts
- src/compile/layout.ts
- src/vega.schema.ts
> Add proper types for all vega transforms that we use.

- src/compile/mark/bar.ts
- src/compile/mark/point.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- src/compile/mark/valueref.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/rule.test.ts
See commits for details:
cc: @mattwchun -- The second commit should solve your problem. ;)
> Adjust behavior for 1D Bar and Rule

- src/fielddef.ts
(forgot to fix it for one condition)
cc: @NeelMohapatra -- you probably wanna rebase after we merge this too.
> Follow up for preventing side effect in fieldDef 

- build/vega-lite-schema.json
- src/encoding.ts
(From this morning's conversation.)
> Make text support boolean

- build/vega-lite-schema.json
- examples/vg-specs/histogram.vg.json
- examples/vg-specs/histogram_nospacing.vg.json
- examples/vg-specs/layer_histogram.vg.json
- examples/vg-specs/scatter_binned.vg.json
- examples/vg-specs/scatter_binned_color.vg.json
- examples/vg-specs/scatter_binned_opacity.vg.json
- examples/vg-specs/scatter_binned_size.vg.json
- examples/vg-specs/stacked_area_binned.vg.json
- examples/vg-specs/trellis_bar_histogram.vg.json
- examples/vg-specs/trellis_scatter_binned_row.vg.json
- src/bin.ts
- src/compile/data/bin.ts
- src/compile/scale/domain.ts
- src/config.ts
- src/fielddef.ts
- src/util.ts
- src/vega.schema.ts
- test/compile/data/bin.test.ts
- test/compile/data/data.test.ts
- test/compile/data/pathorder.test.ts
- test/compile/data/stack.test.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/rect.test.ts
- test/compile/scale/domain.test.ts
> [WIP] Sw/fix multi bin

- build/vega-lite-schema.json
- src/config.ts
> [WIP] Remove maxbins from config

- CONTRIBUTING.md
Updated `npm run images` to `npm run build:images`
> Update CONTRIBUTING.MD on how to render images

- src/compile/data/aggregate.ts
- src/compile/data/bin.ts
- src/compile/data/dataflow.ts
- src/compile/data/parse.ts
- src/compile/data/stack.ts
- src/compile/data/timeunit.ts
- src/compile/data/transforms.ts
- src/compile/model.ts
- src/log.ts
- test/compile/data/stack.test.ts
I make commits pretty atomic here just in case you wanna revert/drop something. 
Feel free to squash this into a part of your big commit.
> Minor Fixes for dom/transforms

- build/vega-lite-schema.json
- site/docs/bin.md
- src/bin.ts
> Revert "Enable auto-generation for bin.md"

- _includes/description.html
- _includes/docs_toc.md
- _includes/table.html
- _includes/type-anyof.html
- _includes/type.html
- build/vega-lite-schema.json
- site/docs/scale.md
- site/static/main.css
- src/scale.ts
> Enable auto-generation for scale.md and refactor doc generator

- _data/link.yml
- _includes/type.html
- build/vega-lite-schema.json
- site/docs/data.md
- src/data.ts
> Enable auto-generation for data.md

- _includes/showcase.html
- _layouts/home.html
- site/demo.html
- site/index.md
- site/static/main.css
- site/tutorials/gettings_started.md
> Updated colors of Header

- _includes/type-anyof.html
- _includes/type.html
- build/vega-lite-schema.json
- site/docs/transform.md
- site/static/main.css
- src/config.ts
- src/filter.ts
Fix part of #1723 
Might still need help from ham to get the docs done:)
> Auto generate tables for transform

- site/docs/config.md
- site/docs/scale.md
Add missing property from schema file to tables
> Add missing props/config

- src/compile/data/assemble.ts
> Remove error for case that can happen.

- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/model.ts
- src/compile/unit.ts
> Clean up model properties.

- build/vega-lite-schema.json
- examples/examples.test.ts
- src/compile/compile.ts
- src/compositemark.ts
- src/spec.ts
- src/validate.ts
- test/compile/mark/text.test.ts
- test/util.ts
Update spec.ts to
- remove unnecessary declaration
- make `TopLevelExtendedSpec` more correct.  (Facet spec and layer spec should not include row, column inside.)
> Simplify Spec.ts

- examples/vl-examples.json
- site/index.md
- site/static/main.css
- site/static/main.ts
> Make Examples Pretty

- src/compile/layout/index.ts
(extracted from a larger layout removal PR)
> Move layout.ts to layout/index.ts

- _data/link.yml
- _includes/checkLink.html
- _includes/table.html
- _includes/type-anyof.html
- _includes/type.html
- site/docs/data.md
- site/docs/timeunit.md
- site/docs/transform.md
Fix some special cases for link in type.
Add more links for type.
Fix #2165
> Fix docs type errors

- site/docs/axis.md
- site/docs/config.md
- site/docs/legend.md
> Fix reference to interface  in doc

- examples/vg-specs/box_plot.vg.json
- examples/vg-specs/errorbar_aggregate.vg.json
- examples/vg-specs/errorbar_horizontal_aggregate.vg.json
- examples/vg-specs/layer_overlay.vg.json
- examples/vg-specs/overlay_area_full.vg.json
- examples/vg-specs/overlay_area_short.vg.json
- examples/vg-specs/repeat_histogram.vg.json
- examples/vg-specs/repeat_splom_cars.vg.json
- examples/vg-specs/repeat_splom_iris.vg.json
- src/compile/layer.ts
- src/compile/repeat.ts
- src/compile/scale/domain.ts
- test/compile/repeat.test.ts
> Union non-spatial scales in repeat.

- _data/link.yml
- _includes/checkLink.html
- _includes/table.html
- _includes/type-anyof.html
- _includes/type.html
- build/vega-lite-schema.json
- site/docs/encoding.md
- src/encoding.ts
- src/fielddef.ts
@yuhanlu  I think we should use table generator for this page too.  Could you please take over this PR?
I split it into a bit more sections, which would fit better with your table generator.
Thanks
> encoding docs

- build/vega-lite-schema.json
- examples/specs/overview_detail.vl.json
- examples/vg-specs/bar_grouped.vg.json
- examples/vg-specs/overview_detail.vg.json
- src/compile/axis/rules.ts
- src/compile/common.ts
- src/compile/concat.ts
- src/fielddef.ts
- src/spec.ts
- test/compile/concat.test.ts
- test/fielddef.test.ts
- test/util.ts
I implemented only vconcat for now because I think we have to have a conversation about what general layouts we want to support.
> Implement concat operator.

- site/docs/mark.md
> Add mark def to mark.md

- _includes/description.html
- _includes/table.html
> Auto generate required tag

- build/vega-lite-schema.json
- src/fielddef.ts
> Add note for field in FieldDef

- build/vega-lite-schema.json
- package.json
- scripts/check-schema.sh
> Replace Generic interface in schema

- examples/vg-specs/scatter_binned_opacity.vg.json
- src/bin.ts
- test/bin.test.ts
> Changed default maxbins for opacity and color to 6

- test/bin.test.ts
I thought tslint takes care of this
> Removed unnecessary imports from bin.test.ts

- build/vega-lite-schema.json
- examples/specs/trellis_column_year.vl.json
- examples/vg-specs/bar_grouped.vg.json
- examples/vg-specs/bar_grouped_horizontal.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/line_quarter.vg.json
- examples/vg-specs/text_scatter_colored.vg.json
- examples/vg-specs/trellis_anscombe.vg.json
- examples/vg-specs/trellis_bar.vg.json
- examples/vg-specs/trellis_bar_histogram.vg.json
- examples/vg-specs/trellis_barley.vg.json
- examples/vg-specs/trellis_column_year.vg.json
- examples/vg-specs/trellis_row_column.vg.json
- examples/vg-specs/trellis_scatter_binned_row.vg.json
- examples/vg-specs/trellis_stacked_bar.vg.json
- src/compile/common.ts
- src/compile/data/bin.ts
- src/compile/facet.ts
- src/compile/layout/header.ts
- src/compile/mark/valueref.ts
- src/fielddef.ts
- src/filter.ts
- test/compile/common.test.ts
- test/compile/facet.test.ts
- test/compile/mark/text.test.ts
Please see different commits for different clean up performed.
> Clean up formatting

- src/fielddef.ts
> Correct FieldDef generic type

- src/compile/mark/mark.ts
- src/compile/model.ts
- src/compile/scale/domain.ts
> Rename getDataname => requestDataName

- examples/vg-specs/overview_detail.vg.json
- examples/vg-specs/repeat_histogram.vg.json
- examples/vg-specs/repeat_histogram_flights.vg.json
- examples/vg-specs/repeat_splom_cars.vg.json
- examples/vg-specs/repeat_splom_iris.vg.json
- src/compile/concat.ts
- src/compile/repeat.ts
Let's wait for arvind's change so we don't cause conflict since this is pretty minor
> Correct size signal reference for @domoritz

- examples/specs/faceted_selections.vl.json
- examples/specs/interactive_splom.vl.json
- examples/vg-specs/brush.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/interactive_splom.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/panzoom_scatter.vg.json
- examples/vg-specs/trellis_column_year.vg.json
- src/compile/compile.ts
- src/compile/concat.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/model.ts
- src/compile/repeat.ts
- src/compile/selection/interval.ts
- src/compile/selection/selection.ts
- src/compile/selection/single.ts
- src/compile/selection/transforms/project.ts
- src/compile/selection/transforms/scales.ts
- src/compile/selection/transforms/translate.ts
- src/compile/selection/transforms/zoom.ts
- src/compile/unit.ts
- test/compile/selection/inputs.test.ts
- test/compile/selection/interval.test.ts
- test/compile/selection/layers.test.ts
- test/compile/selection/single.test.ts
- test/compile/selection/translate.test.ts
- test/compile/selection/zoom.test.ts
> Support selections in repeated views

- examples/specs/concat_selections.vl.json
- examples/vg-specs/concat_selections.vg.json
- src/compile/concat.ts
> Support selections in concatenated views

- build/vega-lite-schema.json
- examples/specs/layered_crossfilter.vl.json
- examples/vg-specs/brush.vg.json
- examples/vg-specs/concat_selections.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/interactive_splom.vg.json
- examples/vg-specs/layered_crossfilter.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/overview_detail.vg.json
- examples/vg-specs/paintbrush.vg.json
- examples/vg-specs/panzoom_scatter.vg.json
- examples/vg-specs/query_widgets.vg.json
- src/compile/compile.ts
- src/compile/data/formatparse.ts
- src/compile/data/transforms.ts
- src/compile/mark/mixins.ts
- src/compile/selection/selection.ts
- src/compile/unit.ts
- src/filter.ts
- src/transform.ts
- test/compile/data/formatparse.test.ts
- test/filter.test.ts
This commit also removes the Filter[] support.
> Add selection filter support.

- src/compositemark/boxplot.ts
- src/compositemark/errorbar.ts
- src/compositemark/index.ts
- src/spec.ts
- test/compositemark.test.ts
- test/spec.test.ts
> switch parameter for GenericUnitSpec

- test/spec.test.ts
> remove any

- build/vega-lite-schema.json
- examples/specs/layer_box_plot_circle.vl.json
- examples/vg-specs/layer_box_plot_circle.vg.json
- src/compile/common.ts
- src/compile/compile.ts
- src/compile/concat.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/repeat.ts
- src/compile/unit.ts
- src/spec.ts
- test/util.ts
> Make layer adopts parent's width/height.

- examples/vg-specs/bar_grouped.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/line_quarter.vg.json
- examples/vg-specs/trellis_anscombe.vg.json
- examples/vg-specs/trellis_column_year.vg.json
- examples/vg-specs/trellis_row_column.vg.json
- examples/vg-specs/trellis_scatter.vg.json
- examples/vg-specs/trellis_stacked_bar.vg.json
- src/compile/data/formatparse.ts
- src/compile/data/nullfilter.ts
- src/compile/facet.ts
- src/fielddef.ts
- src/timeunit.ts
- test/compile/facet.test.ts
> Support field names with -.

- build/vega-lite-schema.json
- site/docs/encoding.md
- src/channel.ts
- src/compile/mark/area.ts
- src/compile/mark/bar.ts
- src/compile/mark/line.ts
- src/compile/mark/mixins.ts
- src/compile/mark/point.ts
- src/compile/mark/rect.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/encoding.ts
- src/fielddef.ts
- test/channel.test.ts
- test/compile/mark/mark.test.ts
> Add support for tooltips

- build/vega-lite-schema.json
- scripts/rename-schema.sh
- site/docs/encoding.md
> add stack to encoding.md and make changes to new named interface

- examples/specs/bubble_health_income.vl.json
- examples/specs/layer_single_color.vl.json
- examples/specs/layer_single_mean.vl.json
- examples/specs/layered_falkensee.vl.json
- examples/specs/line.vl.json
- examples/specs/line_color.vl.json
- examples/specs/line_detail.vl.json
- examples/specs/line_monotone.vl.json
- examples/specs/line_month.vl.json
- examples/specs/line_step.vl.json
- examples/specs/overlay_area_full.vl.json
- examples/specs/overlay_area_short.vl.json
- examples/specs/overlay_line_full.vl.json
- examples/specs/overlay_line_short.vl.json
- examples/specs/point_dot_timeunit_color.vl.json
- examples/specs/stacked_bar_size.vl.json
- examples/specs/stacked_bar_weather.vl.json
- examples/vg-specs/layer_single_color.vg.json
- examples/vg-specs/layer_single_mean.vg.json
- examples/vg-specs/layered_falkensee.vg.json
- site/docs/layer.md
> Documentation for Layer in Docs

- examples/vg-specs/text_scatter_colored.vg.json
- src/compile/axis/encode.ts
- src/compile/common.ts
- src/compile/legend/encode.ts
- src/compile/mark/valueref.ts
- src/fielddef.ts
- src/timeunit.ts
- test/compile/common.test.ts
- test/timeunit.test.ts
> Use utcFormat when scale type is utc

- package.json
- scripts/rename-schema.sh
> Fix json-e file caused by sed

- examples/vg-specs/brush.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/point_ordinal_color.vg.json
- examples/vg-specs/scatter_color_ordinal.vg.json
- examples/vg-specs/scatter_color_ordinal_custom.vg.json
- examples/vg-specs/stacked_area_ordinal.vg.json
- src/compile/scale/type.ts
- test/compile/scale/parse.test.ts
> Use sequential color scale by default for ordinal color

- build/vega-lite-schema.json
- src/compile/axis/rules.ts
- src/compile/scale/domain.ts
- src/datetime.ts
- src/filter.ts
- test/datetime.test.ts
> [Blocked] Support utc: boolean

- src/compile/compile.ts
- src/compile/concat.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/model.ts
- src/compile/projection/init.ts
- src/compile/projection/parse.ts
- src/compile/scale/type.ts
- src/compile/unit.ts
- src/config.ts
- src/encoding.ts
- src/fielddef.ts
- src/projection.ts
- src/spec.ts
- src/type.ts
- src/vega.schema.ts
- test/compile/projection/init.test.ts
- test/compile/projection/parse.test.ts
Add projection support for geo
> Geo Projection

- build/vega-lite-schema.json
- examples/specs/bar_sort_by_count.vl.json
- examples/vg-specs/bar_sort_by_count.vg.json
- src/sort.ts
- test/compile/scale/domain.test.ts
> Modify sort that if aggregation is count, field will not be required.

- src/compile/data/aggregate.ts
- test/compile/data/assemble.test.ts
> Add basic dataflow to data source generation test

- examples/vg-specs/overlay_area_short.vg.json
- src/compile/mark/mark.ts
- test/compile/mark/mark.test.ts
> Set role for path marks as well. cc @sorenmacbeth

- examples/specs/normalized/trellis_row_column_normalized.vl.json
- examples/specs/trellis_row_column.vl.json
- examples/vg-specs/trellis_row_column.vg.json
- src/compile/facet.ts
- src/compositemark/boxplot.ts
- src/vega.schema.ts
- test/compile/facet.test.ts
- tslint.json
> Fix facet with multiple dims

- build/vega-lite-schema.json
- examples/specs/repeat_independent_colors.vl.json
- examples/vg-specs/repeat_independent_colors.vg.json
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/repeat.ts
- src/resolve.ts
- src/spec.ts
> Resolve for repeat

- build/vega-lite-schema.json
- examples/vg-specs/layer_histogram.vg.json
- examples/vg-specs/layered_crossfilter.vg.json
- src/compile/concat.ts
- src/compile/data/assemble.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/legend/parse.ts
- src/compile/repeat.ts
- src/compile/scale/domain.ts
- src/compile/scale/parse.ts
- src/resolve.ts
- src/spec.ts
- src/vega.schema.ts
- test/compile/facet.test.ts
- test/compile/scale/domain.test.ts
> Implement resolve for facet and concat

- site/docs/axis.md
- site/docs/config.md
- site/docs/legend.md
> add missing property

- _includes/docs_toc.md
- build/vega-lite-schema.json
- examples/specs/output_utc_scale.vl.json
- examples/specs/output_utc_timeunit.vl.json
- examples/specs/parse_local_time.vl.json
- examples/specs/parse_utc_time.vl.json
- examples/specs/parse_utc_time_format.vl.json
- examples/vg-specs/output_utc_scale.vg.json
- examples/vg-specs/output_utc_timeunit.vg.json
- examples/vg-specs/parse_local_time.vg.json
- examples/vg-specs/parse_utc_time.vg.json
- examples/vg-specs/parse_utc_time_format.vg.json
- site/docs/data.md
- site/docs/scale.md
- site/docs/timeunit.md
- src/data.ts
- src/scale.ts
> Add docs for utc time

- _data/link.yml
- build/vega-lite-schema.json
- site/docs/transform.md
- src/fielddef.ts
- src/transform.ts
> add doc for BinTransform, TimeUnit Transform and AggregateTransform

- src/compile/scale/domain.ts
- src/log.ts
- test/compile/scale/domain.test.ts
> Ignore scale.domain when binned

- build/vega-lite-schema.json
- src/config.ts
- src/vega.schema.ts
> Add title config

- site/docs/config.md
@kanitw I pushed my update too late
> Add config docs

- src/compile/mark/mark.ts
- src/compile/mark/mixins.ts
- src/compile/selection/interval.ts
- src/compile/selection/multi.ts
- src/compile/selection/selection.ts
- src/compile/selection/single.ts
- src/compile/selection/transforms/inputs.ts
- src/compile/selection/transforms/nearest.ts
- src/compile/selection/transforms/toggle.ts
- src/compile/selection/transforms/translate.ts
- src/compile/selection/transforms/zoom.ts
- src/compositemark/boxplot.ts
- test/compile/selection/layers.test.ts
- test/compile/selection/nearest.test.ts
- tslint.json
Feel free to add this after your PRs have been merged.
> Allow only one variable per declaration.

- src/compile/mark/mixins.ts
- src/compile/model.ts
- src/compile/scale/assemble.ts
- src/compile/selection/interval.ts
- src/compile/selection/transforms/scales.ts
- src/filter.ts
so that both of them can have strong return type
This will be very helpful for refactoring that I need to do to make scale merging work correctly. 
(As strong type will warn me if I forget to correct something.)
> Separate getScale/SelectionComponent 

- site/docs/axis.md
> Moved label* to labels

- examples/specs/line_color_binned.vl.json
- examples/vg-specs/line_color_binned.vg.json
- src/compile/mark/mark.ts
> Fix line grouping when the line is grouped by binned field	

- build/vega-lite-schema.json
- scripts/rename-schema.sh
(Since this is only used for selection, this should be a better name for Altair)
> Fix #2486 Rename LogicalOperand/And/Or/Not to Selection*

- examples/specs/normalized/trellis_barley_normalized.vl.json
- examples/specs/trellis_barley.vl.json
- examples/vg-specs/trellis_barley.vg.json
- src/compile/compile.ts
Fix https://github.com/vega/vega-lite/issues/2326
> Do not generate unnecessary top-level width/height signals for layout-based models

- src/bin.ts
- src/compile/data/aggregate.ts
- src/compile/data/bin.ts
- src/compile/data/formatparse.ts
- src/compile/data/nonpositivefilter.ts
- src/compile/data/nullfilter.ts
- src/compile/data/timeunit.ts
- src/encoding.ts
- test/compile/selection/parse.test.ts
> Object.keys => keys

- src/compile/facet.ts
- src/compile/legend/encode.ts
- src/compile/mark/point.ts
- src/compile/model.ts
- src/compile/unit.ts
- src/vega.schema.ts
- test/compile/mark/line.test.ts
- test/compile/mark/mixins.test.ts
- test/compile/mark/point.test.ts
- test/compile/selection/predicate.test.ts
> Add `VgEncodeChannel` and `VgEncodeEntry` and fix their references

- build/vega-lite-schema.json
- package.json
- yarn.lock
@kanitw Can you generate the yarn.lock file for me?
> Upgrade schema gen

- .travis.yml
- scripts/build-examples.sh
> Fix Travis Not Running Parallel

- src/channel.ts
- src/compile/data/stack.ts
- src/compile/legend/encode.ts
- src/compile/model.ts
- src/compile/selection/interval.ts
- src/compile/selection/selection.ts
- src/compile/selection/transforms/scales.ts
- src/stack.ts
and update type accordingly
- Note that I change  `ProjectComponent`'s `encoding` to be only `ScaleChannel` as the rest of the code only support it for scale channel anyway.
> Correct getScaleComponent's signature

- .travis.yml
> Test node 8, switch back to npm run from yarn run.

- src/compile/selection/selection.ts
- test/compile/selection/interval.test.ts
- test/compile/selection/predicate.test.ts
> Ensure selection and signal names are legal JavaScript identifiers.

- examples/specs/bar_distinct.vl.json
- examples/vg-specs/bar_distinct.vg.json
- src/aggregate.ts
- src/compile/data/formatparse.ts
- src/compile/data/nullfilter.ts
- src/fielddef.ts
- src/log.ts
- test/compile/data/formatparse.test.ts
- test/fielddef.test.ts
> Support valid, distinct, missing aggregate

- build/vega-lite-schema.json
- site/docs/scale.md
- src/compile/model.ts
- src/compile/scale/domain.ts
- src/compile/scale/parse.ts
- src/fielddef.ts
- src/scale.ts
- test/compile/scale/domain.test.ts
- test/compile/scale/parse.test.ts
> Add scale.reverse, fix sort: "descending"

- src/compile/axis/parse.ts
> Follow-up for axis merge -- we shouldn't make shared axis

- src/compile/split.ts
- src/log.ts
- test/compile/scale/parse.test.ts
Also relax type for `propertyOf` param
> [Refactor] `mergeConflictingScaleProperty` => `mergeConflictingProperty`

- .travis.yml
- scripts/build-examples.sh
- scripts/generate-images.sh
> Install a stable version of parallel

- examples/specs/layered_color_legend_left.vl.json
- examples/specs/point_colorramp_size.vl.json
- examples/vg-specs/layered_color_legend_left.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/point_colorramp_size.vg.json
- examples/vg-specs/stacked_bar_weather.vg.json
- src/compile/axis/parse.ts
- src/compile/common.ts
- src/compile/concat.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/legend/assemble.ts
- src/compile/legend/component.ts
- src/compile/legend/parse.ts
- src/compile/model.ts
- src/compile/repeat.ts
- src/compile/split.ts
- src/compile/unit.ts
- src/legend.ts
- test/compile/legend/assemble.test.ts
- test/compile/legend/parse.test.ts
> Correctly merge legend properties & legend of the same field

- src/compositemark/boxplot.ts
- test/compositemark.test.ts
@mattwchun  I think I better help a bit so we can get this done soon.
please review these changes (commit by commit) and merge it into your branch.
> Fixes + Refactor for Box Plot IQR

- _data/versions.yml
- _includes/docs_toc.md
- _layouts/docs.html
- examples/specs/bar_tooltip.vl.json
- package.json
- site/docs/tooltip.md
- site/static/main.ts
- yarn.lock
- I'll submit another PR to fix the CSS table style
> add tooltip docs and structure to overview

- package.json
- site/static/main.ts
- typings/vega-embed.d.ts
- yarn.lock
* Vega-embed was not upated correctly
* the tooltips didn't work because the typings were not available
> Fix use of embed and tooltips

- examples/vg-specs/bar_tooltip.vg.json
- examples/vg-specs/layer_text_heatmap.vg.json
- examples/vg-specs/line_color_binned.vg.json
- examples/vg-specs/scatter_binned_color.vg.json
- examples/vg-specs/trellis_scatter_binned_row.vg.json
- src/compile/common.ts
- test/compile/data/bin.test.ts
- test/compile/mark/text.test.ts
Fix https://github.com/vega/vega-lite/issues/2579
> Fix `format` to use `''` instead of `null`

- examples/vg-specs/brush.vg.json
- examples/vg-specs/concat_selections.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/interactive_splom.vg.json
- examples/vg-specs/layered_crossfilter.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/overview_detail.vg.json
- src/compile/selection/interval.ts
- test/compile/selection/interval.test.ts
This accounts for JS Date objects.
> Coerce interval extents to numbers for scale trigger test.

- CONTRIBUTING.md
- site/examples/gallery.md
Supersedes https://github.com/vega/vega-lite/pull/2590
> Add community examples to gallery

- site/docs/transform.md
I quickly put some scaffolding here, but you can take it from here.
> [WIP] Scaffolding for transform.md

- site/static/main.css
> add css for sidebar

- site/usage/compile.md
> added custom logger info in compile.md

- CONTRIBUTING.md
- README.md
- _includes/preview
- _includes/showcase.html
- _layouts/plain.html
- site/index.md
- site/tutorials/getting_started.md
> Change all URLs to point to the new react based editor.

- build/vega-lite-schema.json
- examples/specs/stacked_area.vl.json
- examples/vg-specs/stacked_area.vg.json
- examples/vg-specs/stacked_area_binned.vg.json
- examples/vg-specs/stacked_area_normalize.vg.json
- examples/vg-specs/stacked_area_ordinal.vg.json
- examples/vg-specs/stacked_area_stream.vg.json
- package.json
- src/compile/axis/component.ts
- src/compile/axis/encode.ts
- src/compile/data/bin.ts
- src/compile/data/nonpositivefilter.ts
- src/compile/data/stack.ts
- src/compile/mark/mixins.ts
- src/compile/mark/valueref.ts
- src/compile/repeat.ts
- src/compositemark/boxplot.ts
- src/compositemark/errorbar.ts
- src/fielddef.ts
- src/spec.ts
- src/timeunit.ts
- src/vega.schema.ts
- test/compile/axis/encode.test.ts
- test/compile/axis/parse.test.ts
- test/compile/data/stack.test.ts
- test/compile/legend/encode.test.ts
- test/compile/scale/type.test.ts
- test/spec.test.ts
- yarn.lock
Thanks to stronger typings, I found a large number of small bugs. You can see that I kept fixes in separate commits. Please do not squash.
> Typescript 2.4 and a lot of fixes. 

- src/compile/model.ts
- src/compile/selection/selection.ts
- src/log.ts
- test/compile/selection/predicate.test.ts
> Better error messaging for unrecognized selection names.

- src/compile/selection/transforms/zoom.ts
> Ensure that x/y channels exist for zoom anchor

- examples/specs/interactive_splom.vl.json
- examples/vg-specs/brush.vg.json
- examples/vg-specs/bubble_health_income.vg.json
- examples/vg-specs/concat_selections.vg.json
- examples/vg-specs/dashboard_europe_pop.vg.json
- examples/vg-specs/faceted_selections.vg.json
- examples/vg-specs/interactive_splom.vg.json
- examples/vg-specs/layered_crossfilter.vg.json
- examples/vg-specs/layered_selections.vg.json
- examples/vg-specs/overview_detail.vg.json
- examples/vg-specs/panzoom_scatter.vg.json
- examples/vg-specs/timeunit_selections.vg.json
- src/selection.ts
- test/compile/selection/parse.test.ts
- test/compile/selection/zoom.test.ts
This PR ensures that the page does not accidentally scroll when the user means to zoom the brush or scales.
> Consume wheel events to prevent accidental scrolling.

- build/vega-lite-schema.json
- src/mark.ts
> Add docs that changing role can change plot appearance 

- examples/specs/point_2d_array_named.vl.json
- examples/vg-specs/point_2d_array_named.vg.json
- src/compile/compile.ts
- src/compile/layout/assemble.ts
- src/compile/model.ts
Fix https://github.com/vega/vega-lite/issues/2668
Please merge https://github.com/vega/vega-lite/pull/2676 first!
> Merge the top-level spec's width/height signal with the top-level model

- src/compile/axis/parse.ts
- src/compile/legend/parse.ts
- test/compile/legend/parse.test.ts
> Fix logic for legend merging

- examples/compiled/bar_1d.vg.json
- examples/compiled/bar_1d_rangestep_config.vg.json
- examples/compiled/minimal.vg.json
- examples/compiled/parse_local_time.vg.json
- examples/compiled/parse_utc_time_format.vg.json
- examples/compiled/point_1d.vg.json
- examples/compiled/point_1d_array.vg.json
- examples/compiled/point_1d_bin.vg.json
- examples/compiled/point_color.vg.json
- examples/compiled/point_dot_timeunit_color.vg.json
- examples/compiled/point_overlap.vg.json
- examples/compiled/stacked_bar_1d.vg.json
- examples/compiled/tick_dot.vg.json
- examples/compiled/tick_dot_thickness.vg.json
- examples/compiled/tick_sort.vg.json
- src/compile/mark/bar.ts
- src/compile/mark/point.ts
- src/compile/mark/rule.ts
- src/compile/mark/text.ts
- src/compile/mark/tick.ts
- src/compile/mark/valueref.ts
- src/compile/model.ts
- test/compile/mark/bar.test.ts
- test/compile/mark/point.test.ts
- test/compile/mark/rule.test.ts
- test/compile/mark/text.test.ts
- test/compile/mark/tick.test.ts
- Also make `model.getLayoutSize` return actual number if possible (this is a prep for a subsequent PR). 
Fix #2742
> Make model.width/height return a signal ref

- _data/examples.json
- examples/specs/layer_candlestick.vl.json
- examples/vg-specs/layer_candlestick.vg.json
> Added a candlestick example

- build/vega-lite-schema.json
- src/compile/compile.ts
- src/compile/concat.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/model.ts
- src/compile/repeat.ts
- src/spec.ts
- src/title.ts
- src/vega.schema.ts
- test/compile/compile.test.ts
> Basic support for title

- src/fielddef.ts
- src/log.ts
- test/compile/data/aggregate.test.ts
- test/compile/scale/parse.test.ts
- test/fielddef.test.ts
Fix #2773
(@domoritz -- making type optional is an orthogonal issue, I would not do it here.)
> Enforce binned field to be quantitative type

- examples/compiled/bar_grouped.vg.json
- examples/compiled/bar_grouped_horizontal.vg.json
- examples/compiled/facet_column_facet_column_point.vg.json
- examples/compiled/facet_column_facet_row_point.vg.json
- examples/compiled/facet_cross_independent_scale.vg.json
- examples/compiled/facet_independent_scale.vg.json
- examples/compiled/facet_row_facet_row_point.vg.json
- examples/compiled/faceted_selections.vg.json
- examples/compiled/line_quarter.vg.json
- examples/compiled/trellis_anscombe.vg.json
- examples/compiled/trellis_bar.vg.json
- examples/compiled/trellis_bar_histogram.vg.json
- examples/compiled/trellis_barley.vg.json
- examples/compiled/trellis_column_year.vg.json
- examples/compiled/trellis_row_column.vg.json
- examples/compiled/trellis_scatter.vg.json
- examples/compiled/trellis_scatter_binned_row.vg.json
- examples/compiled/trellis_stacked_bar.vg.json
- src/compile/data/facet.ts
- src/compile/facet.ts
- src/compile/layout/header.ts
- test/compile/data/facet.test.ts
- test/compile/facet.test.ts
> Facet Refactor

- site/examples/gallery.md
Added an example of Multi Line Highlight using nearest selection.
> Multi-line Highlight Example

- site/examples/gallery.md
> add link to slope graph example to gallery.md

- src/compile/data/formatparse.ts
- src/logical.ts
- test/compile/data/formatparse.test.ts
> Automatically generate `parse: {field: 'date'}` for filtered field with timeUnit

- site/examples/gallery.md
- Scatter Nearest Rule
- Scatter Brush Rule
- Bar Brush Rule
> Three more examples

- src/compile/baseconcat.ts
- src/compile/compile.ts
- src/compile/data/assemble.ts
- src/compile/data/optimize.ts
- src/compile/facet.ts
- src/compile/layer.ts
- src/compile/model.ts
- src/compile/scale/domain.ts
- src/compile/unit.ts
- test/compile/data/assemble.test.ts
- test/compile/selection/identifier.test.ts
- test/compile/selection/timeunit.test.ts
Also refactored the code so we only call assemble data from the model. 
#2795
> Split dataflow optimize from assemble.

- build/vega-lite-schema.json
- src/compile/facet.ts
- src/compile/layout/header.ts
- src/facet.ts
to be consistent with FieldDef
Fix #2829
> Move Facet's sort to FacetFieldDef, not header

- build/vega-lite-schema.json
- scripts/rename-schema.sh
- src/compile/mark/valueref.ts
- src/encoding.ts
- src/fielddef.ts
- src/guide.ts
... as it over-explodes the complexity of our JSON schema.
(It's even confuses me when I try to access them for the docs, I'm sure it will confuse other people.)
> Eliminate Generic property for ValueDef

- site/docs/area.md
- site/docs/axis.md
- site/docs/bar.md
- site/docs/circle.md
- site/docs/data.md
- site/docs/facet.md
- site/docs/line.md
- site/docs/point.md
- site/docs/scale.md
- site/docs/selection.md
- site/docs/spec.md
- site/docs/square.md
- site/docs/stack.md
- site/docs/text.md
- site/docs/tooltip.md
- site/examples/gallery.md
- site/tutorials/getting_started.md
(I copy the style for "Doc Overview" from Vega --- it's better than having floating TOC.
> "Doc Overview" + Minor Mark Revision

- build/vega-lite-schema.json
- src/compile/mark/mixins.ts
- src/mark.ts
- test/compile/mark/point.test.ts
Fix #2866
Thanks @g3o2 for the bug report.
> Make mark's color mixins read fill/stroke config as well.

- src/log.ts
Fix https://github.com/vega/vega-lite/issues/2431
> Use consistent quotes in log.ts

- test/compile/data/filter.test.ts
- test/compile/data/lookup.test.ts
> fix tests structure

- site/docs/layer.md
> Fix Composition link on Layer page

- build/vega-lite-schema.json
- site/docs/scale.md
- src/scale.ts
> Hide `count` from SchemeParams as its only useful for quantize,

- typings/vega.d.ts
> Add typings in vega.d.ts

- site/examples/gallery.md
> added dot-dash plot community example

- build/vega-lite-schema.json
- src/spec.ts
> Extend docs on $schema

- test-runtime/util.ts
Follow up for this comment: https://github.com/vega/vega-lite/pull/2930#commitcomment-24009329
> Update runtime util

- src/compile/mark/bar.ts
- src/compile/mark/mixins.ts
- src/compile/mark/rect.ts
- test/compile/mark/bar.test.ts
Fix https://github.com/vega/vega-lite/issues/2941
> Make bin offset works correctly when its scale is reversed

- src/compile/mark/line.ts
- test/compile/mark/line.test.ts
Small change. Mostly to help me learn the process.
> Make 1D lines render centered in their pane. Fixes #2946

- _data/link.yml
- build/vega-lite-schema.json
- site/docs/config.md
- site/docs/selection/selection.md
- site/docs/transform/filter.md
- src/config.ts
- src/fielddef.ts
- src/scale.ts
- src/selection.ts
- src/transform.ts
Addresses the remaining todos noted by @kanitw from #2693.
> Remaining Selection Docs Revisions

- _data/examples.json
- _includes/preview.html
- site/examples/gallery.md
- site/static/main.css
You can now customize the style of any example.
> Allow styling of the gallery. Fixes #2969

- build/vega-lite-schema.json
- src/mark.ts
> Follow up docs update for the changed `continuousBandSize`

- site/index.md
- site/static/main.css
- site/static/main.ts
- test-runtime/toggle.test.ts
> Next button on homepage. Fixes #2986

- src/compile/scale/range.ts
- test/compile/scale/range.test.ts
Fix https://github.com/vega/vega-lite/issues/3019
> Make explicitly specified range explicit in the scale component

- src/scale.ts
- test/compile/scale/range.test.ts
* I can't remember the better name that Arvind proposed
> Allow customizing XY range (for horizon chart / joy plot*)

- _data/link.yml
- build/vega-lite-schema.json
- scripts/rename-schema.sh
- site/docs/encoding/field.md
- src/compile/repeater.ts
- src/compile/scale/domain.ts
- src/compile/scale/properties.ts
- src/compile/unit.ts
- src/fielddef.ts
- src/sort.ts
- src/spec.ts
- test/compile/repeat.test.ts
- test/compile/scale/domain.test.ts
@sorenmacbeth this fixes your issue.
> Support repeat in conditions and sort

- examples/compiled/stocks_nearest_index.vg.json
- src/compile/legend/encode.ts
- src/fielddef.ts
- test/compile/legend/encode.test.ts
> Make legend have non-0 value when having condition

- site/docs/config.md
- site/docs/portingguide.md
Fix https://github.com/vega/vega-lite/issues/2997
cc: @jakevdp -- this might be useful for your team.
> First draft of porting guide

- site/docs/types.md
> Add link from DateTime to where are they being used

- site/usage/applications.md
Add [django-chartflo](https://github.com/synw/django-chartflo) to the tools section of applications
> Add django-chartflo to applications tools list

- _layouts/plain.html
- site/static/main.css
CC @ellisonbg @jakevdp, we can add Altair when the new theme is online
> Add dropdown to switch between vl and vg. Fixes #3117

- examples/compiled/area_horizon.vg.json
- examples/specs/area_horizon.vl.json
> Update horizon chart example

- site/docs/encoding/legend.md
Removed a redundant semi-colon and changed "axis" to "legend" to appropriately reflect the desire of the example.
Please:
> Fixed typo in code sample for legend in config

- build/vega-lite-schema.json
- package.json
- yarn.lock
> Clean up schema with new schema generator. #2666

- src/transform.ts
Just fixing ref in documentation:
https://vega.github.io/vega-lite/docs/aggregate.html#ops
> Fix ref: supported-aggregation-operations → ops

- build/vega-lite-schema.json
- site/docs/encoding/field.md
- src/fielddef.ts
I intentionally kept it short so that users actually read it.
Follow up for https://github.com/vega/vega-lite/commit/0a68ff175c11939dcf833c61c953aca50aad8925
> Add note about escaping fields to schema.

- site/examples/index.md
I think the disaster chart should become one of our core examples: https://github.com/vega/vega-lite/issues/3232.
> Add some of my block examples

- examples/compiled/box-plot_minmax_1D_horizontal.vg.json
- examples/compiled/box-plot_minmax_1D_vertical.vg.json
- examples/compiled/box-plot_minmax_2D_horizontal.vg.json
- examples/compiled/box-plot_minmax_2D_horizontal_IQR.vg.json
- examples/compiled/box-plot_minmax_2D_horizontal_color_size.vg.json
- examples/compiled/box-plot_minmax_2D_horizontal_custom_midtick_color.vg.json
- examples/compiled/box-plot_minmax_2D_horizontal_explicit_aggregate.vg.json
- examples/compiled/box-plot_minmax_2D_vertical.vg.json
- examples/compiled/box-plot_tukey_2D_vertical.vg.json
- examples/compiled/layer_box-plot_circle.vg.json
- examples/specs/normalized/box-plot_minmax_1D_horizontal_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_1D_vertical_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_horizontal_IQR_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_horizontal_color_size_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_horizontal_explicit_aggregate_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_horizontal_normalized.vl.json
- examples/specs/normalized/box-plot_minmax_2D_vertical_normalized.vl.json
- examples/specs/normalized/box-plot_tukey_2D_vertical_normalized.vl.json
- examples/specs/normalized/layer_box-plot_circle_normalized.vl.json
- examples/specs/normalized/trellis_bar_histogram_label_rotated_normalized.vl.json
- src/compositemark/boxplot.ts
- test/compositemark.test.ts
Refers to issue #3166. 
upperwhisker = min(iqr *k + q3, max of continuous axis field)
lowerwhisker = max(q1 - iqr *k, min of continuous axis field)
> Clamps the whiskers of the Boxplot

- site/usage/applications.md
This might be a better version of https://github.com/vega/vega-lite/pull/3236
cc: @nyurik
> Update applications.md -- PoleStar is now part of Voyager 

- src/compile/layout/header.ts
> Make header `labelAngle` support `0` --

- src/compile/layout/header.ts
- src/compile/model.ts
- test/compile/layout/header.test.ts
> Make sort descending work correctly with header

- build/vega-lite-schema.json
- site/docs/projection.md
- src/compile/projection/assemble.ts
- src/compile/projection/parse.ts
- src/fielddef.ts
- src/projection.ts
- src/vega.schema.ts
> Quickfix comments, docs, and convention for geo

- build/vega-lite-schema.json
- site/docs/composition/concat.md
- site/docs/composition/repeat.md
- site/docs/encoding/condition.md
- site/docs/mark/bar.md
- site/docs/portingguide.md
- site/docs/view/size.md
- site/tutorials/explore.md
- site/tutorials/streaming.md
- src/channel.ts
- src/compile/mark/mixins.ts
- src/compositemark/boxplot.ts
- src/fielddef.ts
- src/log.ts
- src/scale.ts
- src/toplevelprops.ts
- src/transform.ts
- test/compile/scale/range.test.ts
- test/compile/scale/type.test.ts
This fixes a variety of typos in the code, the JSON schema and the documentation.
> Fix typos.

- package.json
- yarn.lock
> Update datasets to get correct zip code data

- build/vega-lite-schema.json
- src/predicate.ts
> Fix schema for range filter to allow `null`

- src/compile/data/formatparse.ts
- src/compile/data/indentifier.ts
- src/util.ts
- typings/vega-util.d.ts
In preparation for https://github.com/vega/vega-util/pull/8
> Stricter set type

- src/config.ts
> Fix type of RangeConfig for strict null checks

- build/vega-lite-schema.json
- src/fielddef.ts
- src/spec.ts
- src/transform.ts
cc @waywardmonkeys, https://twitter.com/ArmyOfBruce/status/957497229555609602
> Use absolute URLs to the docs in the schema.

- site/docs/composition/resolve.md
Small typo in the documentation
> Fix link in resolve.md

- build/vega-lite-schema.json
- site/docs/mark/mark.md
- src/compile/mark/mixins.ts
- src/compile/mark/valueref.ts
- src/mark.ts
- test/compile/mark/valueref.test.ts
> Add offset as mark properties

- src/compile/axis/parse.ts
- src/compile/legend/parse.ts
- test/compile/axis/parse.test.ts
- test/compile/legend/parse.test.ts
Fix https://github.com/vega/vega-lite/issues/3387
> Make `title=false` means title is hidden

- src/bin.ts
- src/compile/data/bin.ts
- src/compile/data/parse.ts
- test/compile/data/bin.test.ts
> Use varName to replace . with _ in bin signals. 

- site/docs/transform/bin.md
> Change Bin Transform Description

- src/compile/data/aggregate.ts
> Don’t fail on empty groupby

- _data/examples.json
- site/docs/transform/aggregate.md
**In Vega-lite Doc:**
- In Aggregate page: add note about nested field issue on `argmin`/`argmax` and provide solution in the bottom of the page and link to the issue page and the example page for solution.
**In example page:**
- Add not in the description about the solution of the nested field issue on `argmin`/`argmax` and link to the issue page
> State nested field issue in argmin/argmax example description and aggregate page

- src/aggregate.ts
- src/bin.ts
- src/compile/axis/properties.ts
- src/compile/common.ts
- src/compile/data/formatparse.ts
- src/compile/repeater.ts
- src/compile/scale/domain.ts
- src/compile/selection/interval.ts
- src/compile/selection/multi.ts
- src/compile/selection/selection.ts
- src/compile/selection/single.ts
- src/compile/selection/transforms/inputs.ts
- src/compile/selection/transforms/scales.ts
- src/compile/selection/transforms/zoom.ts
- src/config.ts
- src/datetime.ts
- src/encoding.ts
- src/fielddef.ts
- src/mark.ts
- src/predicate.ts
- src/scale.ts
- src/stack.ts
- src/util.ts
- src/validate.ts
- src/vega.schema.ts
- test/compile/scale/parse.test.ts
**Re-exports from utils removed**
- The functions re-exporting from utils are removed.
- The inconsistency of using same functions from utils or vega-utils fixed.
Fixes #3433.
> Re-exports from utils removed

- site/static/main.ts
- site/tsconfig.json
- typings/vega.d.ts
> remove embed from main.ts in site and use Vega View

- site/examples/index.md
Adds a bar chart example with negative values with the axis in the middle.
> Add bar chart example with Negative values (#1418)

- _data/examples.json
- site/docs/composition/repeat.md
**Adding example: Concat and Repeat**
- All examples of concat and repeat from docs are added to the gallery.
- Link to the interactive version of SPLOM is added to docs.
Solves #3469.
> Adding example: Concat and Repeat

- src/compositemark/boxplot.ts
> Refactor markdef in boxplot

- build/vega-lite-schema.json
- src/aggregate.ts
- src/compile/data/aggregate.ts
- src/compile/data/facet.ts
- src/compile/facet.ts
- src/fielddef.ts
- src/log.ts
- src/sort.ts
- src/transform.ts
- src/vega.schema.ts
- test/stack.test.ts
`stderr` is added into `aggregate`.
> Add stderr to Aggregate

- .gitignore
**Update .gitignore for yarn logs**
- This PR updates `.gitignore` to ignore logs files generated by yarn.
> Update .gitignore for yarn logs

- src/compile/data/geojson.ts
- src/compile/data/geopoint.ts
- src/compile/data/parse.ts
> [Refactor] geopoint/geojson should be created only for UnitModel

- build/vega-lite-schema.json
- scripts/build-examples.sh
- scripts/check-examples.sh
- scripts/check-schema.sh
- scripts/deploy-gh.sh
- scripts/deploy-schema.sh
- scripts/deploy.sh
- scripts/pre-deploy.sh
- scripts/rename-schema.sh
- scripts/update-version.sh
- scripts/version.sh
- src/spec.ts
- test/compile/compile.test.ts
- test/compile/mark/text.test.ts
- test/compile/scale/parse.test.ts
- test/spec.test.ts
> Some top level specs require data. Fixes #3489

- src/compositemark/index.ts
Fix https://github.com/vega/vega-lite/issues/3453
> More graceful error for invalid mark type

- src/compile/mark/mixins.ts
> Make mark property support defined falsy value

- examples/specs/layer_bar_annotations.vl.json
- examples/specs/layer_error_bars.vl.json
- examples/specs/layer_error_bars_dev.vl.json
- src/compile/axis/component.ts
- src/compile/legend/component.ts
- src/compile/projection/component.ts
- src/compile/scale/component.ts
- src/compile/split.ts
Merge https://github.com/vega/vega-lite/pull/3522 first!
> Simplify layer examples
