vega/vega-lite

.jshintrc, README.md, editor/editor.js, src/Encoding.js, src/compile/aggregate.js, src/compile/layout.js, src/compile/sort.js, src/compile/stack.js, src/data.js, src/enc.js, src/field.js, src/schema/schema.js, test/Encoding.spec.js, test/compile/axis.spec.js, test/compile/sort.spec.js, test/compile/stack.spec.js, test/compile/time.spec.js, test/fixtures.js, test/schema.spec.js
fixing #436 
~~`aggregate: 'avg'` => `aggregate: ‘average’`~~ — We will change this once we migrate to Vega2.
=> Syntax Refactor

.gitignore, .travis.yml, README.md, gulp/tests.js, package.json
Now we can look at test coverage online at https://coveralls.io/r/uwdata/vega-lite.  
Right now, we’re at 63% — quite low, but honestly surprisingly high given how much test we wrote. 
I am figuring out about local/offline line coverage reporter.
=> Test coverage using istanbul

bower.json, package.json, src/Encoding.js, src/compile/aggregate.js, src/compile/axis.js, src/compile/bin.js, src/compile/compile.js, src/compile/filter.js, src/compile/legend.js, src/compile/scale.js, src/compile/sort.js, src/compile/stack.js, src/compile/time.js, src/field.js, src/schema/schema.js, test/compile/aggregate.spec.js, test/compile/axis.spec.js, test/compile/bin.spec.js, test/compile/marks.spec.js, test/compile/scale.spec.js, test/compile/sort.spec.js, test/compile/stack.spec.js, test/compile/time.spec.js
- remove `’.data’` and rely on `vl.field.fieldRef`
- stop throwing the whole `spec` around in `compile.js`
- re-order/re-group `compile.js` (so we can decouple things in the next PR)
- add some more tests
A small step toward #276 and preparing for #459 
Note that a `encoding._vega2` flag will be introduced during the transition (and eliminated entirely after the migration).  
**Please merge #457 first**
=> Refactor compile

src/Encoding.js
This is why toggle sort was broken.
=> toggleSort still uses the old `enc:`

src/schema/schema.js
Revising the code, I just realized that this `grid` property hasn’t been used at all.
Both `ROW` and `COL` already include `axisMixins`, so these few lines are bogus.
=> remove bogus `grid` property in `rowMixIn`

src/Encoding.js, src/compiler/axis.js, src/compiler/layout.js, src/compiler/legend.js, src/compiler/scale.js
@domoritz   
I kinda feel annoy to have helpers in `encoding` for every single property of a field.   
That said, we still need some of them.  So I'm not sure if we should do this.  
That said, I created this branch on the plane, so would love to know what you think.
=> Eliminate redundant help in encoding.

src/compiler/marks.js, src/compiler/scale.js, src/schema/schema.js, test/compiler/scale.spec.js
fixes #475 
To support reading across chart in Voyager, we need an option to use RAW table as the data source for a scale’s domain.  
**TODO**
Should we find some way to align scale for `COUNT`
=> Feeding scale with raw data for supporting aligning axis with same domain 

gallery/gallery.js, src/compiler/scale.js, test/compiler/scale.spec.js, test/compiler/stack.spec.js, test/field.spec.js
- fixes #454 by setting `sort:true` for binned axis and always set `range:'width/height'` for ordinal scale
- Fixes #505 -- feed bin scale's domain with all the bin value
=> Sorted bin scale

editor/editor.js, gallery/gallery.js, package.json, src/Encoding.js, src/compiler/axis.js, src/compiler/compiler.js, src/compiler/layout.js, src/compiler/marks.js, src/compiler/scale.js, src/compiler/time.js, src/data.js, src/schema/schema.js, test/compiler/axis.spec.js, test/compiler/scale.spec.js, test/compiler/stack.spec.js, test/compiler/time.spec.js, test/field.spec.js
Please merge #507 first.  [See Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/useRawDomain-config...kw/axisLabelOffset)
- make better offset for timeAxis 
- `month`/`day`
- for raw time —  take `timeFormat` into account
- Q
- special case for ordinal based on number
- remove redundant `numberFormat` config in axis and add `format` to textMixin
- add `dayScaleLabel`, `monthScaleLabel`
- refactor `time.js`
- refactor layout.offset
- add `vl.data.stats`
- add some tests
=> Axis label offset

gallery/gallery.js, src/compiler/compiler.js, src/compiler/facet.js, src/compiler/marks.js, src/compiler/template.js
- Remove `mdef` from `scales.def` and  `facet`
- fixes missing text tables
- simplify marks.def
=> Fix Missing text tables, simplify a few things

src/Encoding.js, src/compiler/axis.js, src/compiler/compiler.js, src/compiler/facet.js
It’s actually very simple so I can’t resist to just kill them.
=> eliminate axis.names(), axis.defs()

src/logger.js, src/util.js
Current logger function, which follow [vega-logging](https://github.com/vega/vega-logging)’s pattern does NOT show the right line number which is not particularly useful.  
Borrowing some ideas from stack overflow and some blog posts, this is a simple logger wrapper that still output the correct line number when `log`, `warn`, `error`, `info` or `debug` are called.  
cc: @arvind
=> A simple logger that preserves line number

src/compiler/axis.js, src/compiler/legend.js, src/schema/schema.js, test/compiler/axis.spec.js, test/compiler/legend.spec.js
See https://github.com/uwdata/vega-lite/issues/181.
Needed these for a project:
- had a computer-generated field with an ugly title that we didn't want in the legend, so added `legend.title`
- date labels were hard to read vertically so we wanted to force them horizontal, so added `axis.labelAngle`
Feedback welcome. Should maintain compatibility with existing specs.
=> Add legend.title property and axis.labelAngle property

src/compiler/compiler.js, src/schema/schema.js
@osnr   Since you need it, I’m adding this as a config.    
Note that your PR #557 does not work because we declare sort properties to be `Array` type in the [JSON schema](https://github.com/uwdata/vega-lite/blob/master/src/schema/schema.js#L215) and therefore it can’t be `Boolean`.  
Please let me know if this works for you.  
Note that this is subject to change once we migrate to Vega 2.
=> allow disabling auto-sort for line

editor/bower.json, gallery/bower.json, src/Encoding.js, src/compiler/axis.js, src/compiler/data.js, src/compiler/scale.js, src/compiler/sort.js, src/compiler/time.js, src/field.js, test/compiler/data.spec.js, test/compiler/marks.spec.js, test/compiler/scale.spec.js, test/compiler/sort.spec.js, test/compiler/stack.spec.js
Let’s create a set of small PRs to merge to 0.8 so we can easily review changes.  
(And merge `0.8` to `master` when we are done with migration)
- update vega dependency in editor and gallery
- removed `_vega2` flag ~~turn on `_vega2` flag (let’s keep it for now, but we should eventually remove it)~~  
- replace `d.data` with `datum` in filter
- add `datum.` option to fieldRef and use it in time transform and filter non-positive value when log are presented when `encoding._vega2` is `true`
- eliminate `data.` from test.  
- eliminate outdated fieldRef options
- only use field.name where applicable
=> First step to migrate to Vega 2

src/compiler/compiler.js, src/compiler/facet.js, src/compiler/scale.js, src/compiler/subfacet.js
- use the new `name` mark property in groups
- fix incorrect fieldRef call
Please merge #602 first.  See branch specific diff [here](https://github.com/vega/vega-lite/compare/kw/filter-null...kw/vg2-more)
=> More small modifications for vega2 migration

src/compiler/data.js, src/schema/schema.js, test/compiler/data.spec.js
Fixes #588  Move filter to data.filter and use Vega expression.
Now filter simply accepts a string, which should be a Vega expression.  
Please merge #596 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/vg2-more...kw/588-data.filter))
=> Move filter to data.filter and use Vega expression.

src/compiler/legend.js, src/schema/schema.js
Fixes #131  
- set legend's orient to right by default (similar to Vega)
- remove outdated comment regarding multiple legends. (This is automatically fixed when we migrate to vega 2)
=> Remove outdated legends error log, set default legends orient

gallery/gallery.js, src/compiler/compiler.js, src/compiler/stack.js, src/compiler/subfacet.js
Fixes #412  and part of #459
- Use vega2 stack's parameter and rename it to `<field_name>_start|end`, remove the need to add facet transform before stacking
- Add a stacked bar chart example 
- Make facet comes after stack for stacked area chart  (This makes stacked area chart looks almost right but still looks weird due to #307 – see [example screenshot] (https://www.evernote.com/l/AAi8LLKSH3lDgZYIOTW39BQDzY4As6Vy2hk))
Please merge #617 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/scale-refactor...kw/vg2-stack))
=> Migrate Stack to Vega 2

editor/editor.js, gallery/gallery.js, src/Encoding.js, src/schema/schema.js, test/Encoding.spec.js, test/fixtures.js
Fixes #448, Fixes #611, Related #620 
- `avg` => `mean`
- add all supported aggregation in Vega 2
Please merge #615 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/vg2-stack...kw/448-aggregate-fn))
~~TODO~~
```
Error: Cannot find module 'through'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/Users/kanitw/Documents/_code/_idl/_visrec/vega-lite/node_modules/vega/scripts/strip-schema.js:8:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```
=> Update Aggregate Function List to be similar to Vega 2

src/Encoding.js, src/compiler/compiler.js, src/compiler/data.js, src/compiler/facet.js, src/compiler/marks.js, src/compiler/scale.js, src/compiler/stack.js, src/compiler/subfacet.js, test/compiler/scale.spec.js
#276
- move stack’s stacked data transform to `data.stack`
- add `encoding.stack` so we do not have to pass `stack` around
- TODO in future PRs 
- consider caching stack as encoding’s property to avoid redundant computation
- remove `stack.js` and move the same logic to `marks.js` to reduce side effect
- consider if there is a way to avoid creating stacked data, which perform redundant calculation with scales in each facet.  (maybe signal could work)
=> Simplify stack code

src/compiler/facet.js, src/compiler/marks.js
Fixes #459 (replacing #638)
- eliminate `keys.0` reference
- add `datum.` in template reference
After merging this to `0.8`, we should test this with voyager a bit and consider releasing `0.8.1`.
=> Fix remaining basic migration issues

src/compiler/axis.js, src/compiler/facet.js, src/compiler/stack.js, test/examples.js
Fixes #640
- add `band:true` to `properties.grid` (I originally omitted this as `band:true` was grid's default)
- do not produce `undefined` in the spec.
- Make stack transform's `groupby,sortby` an array
All examples now pass vega's schema validator!
=> Fixing validation errors 

src/Encoding.js, src/compiler/stack.js, src/schema/schema.js
Make `stack` either boolean or object and accept `reverse` and `offset` properties.  -- fixes #634
=> Make `stack` either boolean or object

src/compiler/scale.js, src/encdef.js
- extract `scale._useRawDomain()` to simplify the code and refer to field correctly when `useRawDomain` is activated.
- add `noAggregate` option for `vl.field.fieldRef` and simplify the method
This fixes the broken `MEAN` bug in voyager https://github.com/vega/voyager/issues/207.
=> Fix incorrect field reference when scale.useRawDomain is activated

docs/Encoding-Mapping.md, src/compiler/scale.js, src/schema/schema.js, test/compiler/scale.spec.js
Fixes #663 
- now `sort` property can be either `undefined`, a __String__ or an __Object__
- `undefined` - the field is unsorted.
- (as __String__) `'ascending'` or `'descending'` – the field is sort by the field's value in ascending or descending order.
- (as __Object__ — for ordinal/nominal fields only) A sort field object - for sorting the field by an aggregate calculation (`sort.op`) over a specified sort field (`sort.field`) in a specified order (`sort.order`)
- add `scale.sort` that correct determine `sort` output
- add `scale.reverse` and determine the value from `sort`
- update docs regarding `sort`
=> Make `sort` support `undefined`, String (for all types), or Object (for ordinal/nominal only) 

src/Encoding.js, src/compiler/scale.js, src/schema/schema.js
- remove Encoding.toggleSort and migrate to vega-lite-ui
- only output vega `scale.reverse` when it is `true`
- Make sure that If sort by aggregation of a specified sort field,  use RAW table so we can aggregate value for the scale independently from the main aggregation. 
Please merge #670, #671, #672 first!
=> Migrate `Encoding.toggleSort` to `vega-lite-ui` and fix domain when sort by aggregation of a sort field.

src/compiler/axis.js, src/schema/schema.js
- correctly makes grid working by referring to `field: 'data'` -- fixes #660
- Add `cellGridOffset` and make it equals to Vega’s default `tickSize` by default
- use `strokeOpacity` instead of `opacity` (Address a follow up concern in #661)
=> Make Grid works correctly + add cellGridOffset

docs/Encoding-Mapping.md, src/compiler/axis.js, src/schema/schema.js
Fixes #378
If `grid` is unspecified, the default value is `true` for ROW and COL. For X
and Y, the default value is `true` for quantitative fields and `false`
otherwise.
=> Make `grid` value automatically determined

gallery/examples.js, src/compiler/stack.js, src/schema/schema.js, test/compiler/scale.spec.js
- Make encoding definition `sort=‘ascending’` by default  — closes #663.
- No longer add `’-‘` to `sortby` in the output `stack` transform by default
=> Change default values for sort and stack

gallery/examples.js, src/compiler/data.js, src/compiler/marks.js, src/compiler/scale.js, src/compiler/time.js, src/encdef.js, src/schema/schema.js, test/compiler/data.spec.js, test/compiler/marks.spec.js, test/compiler/scale.spec.js, test/compiler/stack.spec.js
- Reimplement binning to use linear scale instead of ordinal scale based on @jheer’s example in https://github.com/vega/vega/pull/388 using - use the new bin transform’s `bin_end`
- Make `scale.zero` automatically determined rather than always `true`
- always returns `false` for bin and time
- Otherwise, return true for `X`, `Y` and `SIZE`
- use `bin_mid` instead
=> Reimplement bin using `bin_start`, `bin_end`

docs/Encoding-Mapping.md, src/Encoding.js, src/compiler/layout.js, src/compiler/marks.js, src/compiler/scale.js, src/schema/schema.js, test/compiler/marks.spec.js
- Add all of vega's scale properties that should be supported #181 
- add scale property to `row`, `column` and `shape`
- remove `encDef.band`
- `band.size` => `scale.bandWidth`
- `band.padding` => `scale.padding`
- add `encoding.padding()` helper
- Add separate methods for 'bandWidth', 'nice', 'padding', 'points', 'range', 'reverse', 'round', ‘zero’
- revise default valus for `nice`, `points` and `zero`
- revise `useRawDomain` to support only aggregate functions that produces values ranging in the domain of the source data (`'mean'`, `'average'`, `'stdev'`, `'stdevp'`, `'median'`, `'q1'`, `'q3'`, `'min'`, `'max'`)
- rename
- `bandSize` => `bandWidth`
- `scale.sort()` => `scale.domain.sort()`
=> Major scale revision

src/compiler/scale.js, src/schema/schema.js
(I didn’t include `outerPadding` when I refactor axis because it’s not in the Vega document so I thought it doesn’t affect anything, but I was wrong.)
=> Fix facet misalignment due to the missing outerPadding

src/Encoding.js, src/compiler/axis.js, src/compiler/compiler.js, src/compiler/layout.js, src/compiler/marks.js, src/schema/schema.js
- Eliminate stats from numberFormat #648
- remove `largeNumberFormat`, `smallNumberFormat` and `maxSmallNumber` from config.
=> Eliminate stats from numberFormat #648

src/compiler/axis.js, src/schema/schema.js, test/compiler/axis.test.js
- All produced properties that have special rules are organized in methods with the following patterns: `axis.<propertyName>` and `axis.properties.<propertyGroup>`
- #181 now support explicit specification of all Vega’s __axis properties__ (`'format', 'grid', 'offset', 'orient', 'tickSize', 'ticks', 'title', ‘titleOffset', 'layer', 'tickPadding', 'tickSize', 'tickSizeMajor', 'tickSizeMinor', 'tickSizeEnd',
'values', ‘subdivide’`) and __property groups__ (`'axis', 'grid', 'labels', 'title', 'ticks', 'majorTicks', 'minorTicks’`)
- Output spec should remain the same except
- `titleOffset` is set to `undefined` (auto) for `x` and `y` — so we can just rely on the [new Vega’s axis auto title offset](https://github.com/vega/vega/pull/421) — __This mean we need to wait until Vega releases new …
=> Refactor axis to minimize side effects

src/compiler/scale.js, test/compiler/scale.test.js
Fixes #697, Better fix for #719 
(Looks like @jpocom  needs this, so I fix it first although we’re in the mid of TS investigation)
=> Use ordinal scale when using bin with row, column.

src/compiler/axis.js
As @jpocom reported, that this spec
```
{
"encoding": {
"row": {
"name": "Year",
"type": "T",
"timeUnit": "year",
"axis": {
"orient": "right"
}
},
"text": {
"name": "*",
"aggregate": "count",
"type": "Q",
"displayName": "Number of Records"
},
"color": {
"name": "*",
"aggregate": "count",
"type": "Q",
"displayName": "Number of Records"
}
},
"marktype": "text",
"data": {
"formatType": "json",
"url": "data/cars.json"
}
}
```
produces:
With this fix, now it is slightly better:
=> A step toward making row's `axis.orient = 'right'` correct

docs/Documentation.md, src/compiler/compiler.ts, test/compiler/stack.test.ts
Make compiler return an object containing spec rather than just the spec. -- fixes #727
=> Make compiler return an object containing spec rather than just the spec.

src/schema/schemautil.ts
fix `schemautil.subtract`, so that vega-lite code in polestar is not weirdly verboseand thus we can easily copy output from polestar
fixes https://github.com/vega/polestar/issues/307
=> fix schemautil.subtract, so that vega-lite code in polestar is not weirdly verbose

bin/vl2vg, docs/Config.md, docs/Encoding-Mapping.md, gallery/gallery.js, src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/data.ts, src/compiler/scale.ts, src/compiler/stack.ts, src/schema/config.schema.ts, src/schema/encoding.schema.ts, src/schema/fielddef.schema.ts, src/spec.ts, test/compiler/data.test.ts
__Please merge #764 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/model...kw/stack))__
Fixes #683 
- move `stack` property from `color`/`detail` to `config`
- make `stack` config supports an array of fields. 
- make stack uses descending by default 
- update `vl.spec.isStack()`
- add StackDef interface
- calculate `_stack` only once in model 
- Add docs for stack in `Config.md` 
——
=> Fix stack 

src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/data.ts, src/compiler/facet.ts, src/compiler/legend.ts, src/compiler/marks.ts, src/compiler/scale.ts, test/compiler/axis.test.ts, test/compiler/data.test.ts
Note that I leave `facet`, `layout`, `stack`, `style`, `subfacet`, and `time` since these will be further refactored to simplify flow (#276) and some of them might be removed so I don’t want to waste time refactoring them now.
=> Replace def(), defs() with compileXXX() methods and remove export default where it’s not necessary 

src/vl.ts
=> Do not pollute `vl.` with util methods by moving them to `vl.util`.

src/compiler/compiler.ts, src/compiler/facet.ts, src/compiler/marks.ts, src/marktype.ts, test/compiler/marks.test.ts
- Make `marks.ts` far less confusing 
- refactor the weird pattern on the top
- `e` => `model`
- Use `update` instead of `enter` for root 
- Use `{group: "width|height"}` for cell if there is no facet
=> Make marks.ts far less confusing + Use Update instead of enter for root 

src/compiler/compiler.ts, src/compiler/facet.ts, src/compiler/marks.ts
#276	
- introduce “root” group, which appears in all visualization.  This is a preparation for eliminating stats.
- only include “cell” group for small multiples 
- refactor facet
- avoid creating shared axes groups when they are not necessary
=> refactor facet and compiler -- reduce side effects

gallery/examples.js, src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/facet.ts, test/compiler/axis.test.ts
This removes logic for automatically putting x-axis on top if y has high cardinality.
We should move this logic to `vlplot.js` so it’s still applied in both voyager and polestar.
=> remove stats from axis

src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/data.ts, src/compiler/facet.ts, src/compiler/layout.ts, src/compiler/legend.ts, src/compiler/marks.ts, src/compiler/scale.ts, src/compiler/stack.ts, src/compiler/time.ts, src/data.ts, src/encoding.ts, src/fielddef.ts, src/shorthand.ts, src/spec.ts, test/compiler/time.test.ts, typings/datalib.d.ts
Formerly the helper method for vega’s field is called `fieldRef` since `field` in Vega-Lite used to refer to what we currently call `fieldDef`.  Since now `field` in Vega-Lite refers to the same thing as Vega, there is no reason to name the method differently.  
Also moved field() from `fieldDef.ts` to `model.ts` since it’s internal only.  
Please merge #804 first !  (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/refactor...kw/field))
=> Rename fieldRef => field

src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/data.ts, src/compiler/facet.ts, src/compiler/layout.ts, src/compiler/legend.ts, src/compiler/marks.ts, src/compiler/scale.ts, src/schema/config.schema.ts, src/schema/encoding.schema.ts, src/schema/scale.schema.ts, test/compiler/axis.test.ts, test/compiler/marks.test.ts
Most important part of #666 for 0.9.0 — still left a few to be removed/added later.  
- remove `single/cell Width/Height`, always use `cell.width|height`
- remove unused `gridColor`, `gridOpacity`
- remove `config.bandWidth|padding` and `model.bandWidth|padding()` and set different default values for different channels instead!
- remove config.useRawDomain
- group configs for a particular part
- `config.cell`
- move `cell` configs to be under `cell`:  `width`, `height`, `padding`, `gridColor`, `gridOpacity`, `gridOffset`
- add group marks properties to `config.cell`: `fill`, `fillOpacity`, `stroke`, `strokeWidth`, `strokeOpacity`, strokeDash, strokeDashOffset`
- `config.marks`
- move `baseline`, `font`, `fontStyle`, `fontWeight` from `encoding.text` to `config.marks`
- …
=> Revise config 

src/compiler/legend.ts, src/compiler/scale.ts, src/schema/sort.schema.ts
If you can't type check the interface object, check if it's not the primitive and you can get away with it without introducing complex `isX` methods
=> Simplify type checking

src/compiler/data.ts
- Take cardinality from domain if a field has custom scale domain — otherwise, we get incorrect cardinality by calculating count distinct.  
- and do not calculate distinct and waste computation cycle
=> Take cardinality from domain if a field has custom scale domain

docs/encoding.md, src/compiler/scale.ts, src/compiler/time.ts
I think we should extract “transformation”, “axis”, “scale” and “legend” as their own page in a later PR.
=> scale documentation and minor refactor

README.md, package.json
- swap order of `npm run watch:all`, so that `npm start` can run `npm run watch` without being too slow. 
- rename dev=>test + update README.md.
=> Make `npm start` working sensible

src/schema/schema.ts, tsconfig.json, typings/vega.d.ts
so that we don't get "exported external package typings file cannot contain triple slash references" error when importing vega-lite into compass.
=> Remove `vega.d.ts` and  triple slash reference 

docs/encoding.md, src/compiler/axis.ts, src/schema/axis.schema.ts
+ `shortTimeName` => `shortTimeLabel`
+ Adding `tickSizeMajor, tickSizeMinor, tickSizeEnd, values` to axis's schema and docs 
+ reorder values alphabetically
Fixes #796
=> Add missing axis properties, rename shortTimeName => shortTimeLabel

src/compiler/facet.ts
- Fixes #873 by making sure that `transform` in x-axes and y-axes groups are arrays.
- re-order property using extend
- add `spec.name()` as prefix for group’s name if specified
=> Ensure that `transform` in axes group are arrays + refactor

src/compiler/facet.ts
Do `aggregate` transform for x-axes group and y-axes group instead of `facet` because it should leave smaller memory footprint
=> Replace facet transform with aggregate for axes group

src/compiler/Model.ts, src/compiler/stack.ts
=> Support stacked charts with both detail and color

src/compiler/data.ts, src/compiler/facet.ts, src/schema/config.cell.schema.ts
- Total Width Height should be `(cellWidth|Height + cellPadding) * cardinality` instead of  `(cellWidth|Height + cellPadding) * cardinality - cellPadding`
- avoid negative offset in trellis’s subgroups, which makes the group not start from (0,0)
fixes #828
=> Correctly calculate total width/height and offset for trellis plot

package.json
Fixes #881
cc @arvind with this change, you can simply `require('vega-lite')` and use browserify.
=> Change the main file to vl.js

src/compiler/Model.ts, src/compiler/legend.ts, src/compiler/marks.ts, src/schema/config.marks.schema.ts, test/compiler/marks.test.ts, test/fixtures.ts
- make `config.marks.filled` applied to other applicable mark types (`bar` and `area`) 
- consolidate rules for determining default config values. 
fixes #812.
=> make `config.marks.filled` applied to other applicable mark types

docs/config.md, src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/compiler.ts, src/compiler/facet.ts, src/compiler/marks.ts, src/compiler/scale.ts, src/schema/config.cell.schema.ts, src/schema/config.marks.schema.ts, src/schema/config.schema.ts, src/schema/encoding.schema.ts, src/schema/fielddef.schema.ts, test/compiler/axis.test.ts
Fixes #871, #901, #771
- remove scale and sort from detail	
- make sure we don’t produce a scale for detail in the output	
- add `config.mark.sortBy` and move `config.sortLineBy` to `config.mark.sortLine`.
- Add properties for hiding facet's rules/grid and docs for all `cell.facet/grid` properties (still need to determine how should we call these properties though) – addresses #896
- Allow hiding axis
=> remove scale and sort from detail, add / reorganize config 

src/compiler/compiler.ts, test/compiler/stack.test.ts, test/fixtures.ts
- simplify and export `compileRootGroup`
- correctly write unit test for stack without calling the whole `compile` method
=> Refactor Stack Test

src/compiler/Model.ts, src/compiler/data.ts, src/compiler/stack.ts, src/encoding.ts, src/fielddef.ts, src/schema/encoding.schema.ts, test/compiler/data.test.ts
Fixed #864 
- bring back `vl.fieldDef.field()` so we can use it with detail array 
- replace `stackChannels` with `stackFields` in StackProperties (so we can have multiple fields for details)
- modify methods in `model.ts` to check if `encoding[channel]` is an array
=> Support Multiple Detail

src/compiler/Model.ts, src/compiler/data.ts, src/compiler/scale.ts, src/compiler/stack.ts, src/encoding.ts, src/fielddef.ts, src/schema/encoding.schema.ts, test/compiler/data.test.ts
Determine `date`, `year`, `second`, `minute`'s scale type based on mark type and orientation.
(For dimension channel of `bar` or `tick` mark, use `ordinal` scale. Otherwise, use `linear` scale.)
Fixes #398
__Please merge #904 first!__ (See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/multi-detail...kw/timeUnit-scaleType))
=> Determine `date`, `year`, `second`, `minute`'s scale type based on mark type and orientation.

docs/config.md, src/compiler/legend.ts, src/compiler/marks.ts, src/schema/config.marks.schema.ts
- add `fill`, `fillOpacity`, `stroke`, and `strokeOpacity`
- add ColorMode
- refactor `colorMixins` to `applyColorAndOpacity`
- apply fill and stroke config for all marks
- apply fill and stroke config
=> refactor marks.ts and legend.ts

src/compiler/data.ts, src/compiler/scale.ts, src/data.ts, test/compiler/scale.test.ts, test/compiler/stack.test.ts
- Rename STACKED to STACKED_SCALE to avoid confusion since the data source sums data for scale while the actual stack layout is applied inline.
- Remove the unnecessary max calculation in STACKED_SCALE since scale would automatically calculate max anyway.  
@arvind @domoritz
=> Refactor STACKED_SCALE (originally STACKED)

src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/facet.ts, src/compiler/legend.ts
- `model.axisDef` => `model.axis()`
- spec always refers to input
- def generally refers to output except `fieldDef`, which is too late to change.
- part of #276
=> Refactor to avoid overloading the term spec / def.

src/compiler/Model.ts, src/compiler/data.ts, src/compiler/scale.ts
- correctly check isDimension
- take `mark` as param instead of `model` in `scale.type`
=> 	simplify `scale.type`

src/compiler/Model.ts, src/compiler/config.ts, src/compiler/legend.ts, src/compiler/marks.ts, src/compiler/scale.ts, src/compiler/stack.ts, src/encoding.ts, src/fielddef.ts, tsconfig.json
- extract `compileStackProperties` to stack.ts
- add `compileMarkConfig` and remove `model.markConfig()`
- fix `fieldDef.isDimension|Measure` and use it entirely in `model`
Please merge #926 first!  
(See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/scale.type...kw/markConfig))
=> `model.markConfig()` => `compileMarkConfig` & extract `compileStackProperties`

docs/config.md, docs/encoding.md, src/compiler/marks.ts, src/schema/config.marks.schema.ts
- Use `xc` and `yc` for ticks so we don’t have to add offset
- add offset for vertical dot plot with tick
- `config.mark.tickSize` => `config.mark.thickness`
- make `size.value` works with `tick` and `bar` mark – fixes #931
=> Refactor Tick and Bar Marks

docs/config.md, docs/encoding.md, src/compiler/Model.ts, src/compiler/marks.ts, src/schema/config.marks.schema.ts
- `mark.size` => `model.sizeValue()`
- `TEXTMARKS` => `TEXTMARK`
Please merge #933 first!  
(See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/tick...kw/refactor))
=> Follow up refactor for #933

examples/temp_histogram.json, examples/temp_histogram_bar.json, examples/vlexamples.json, src/compiler/Model.ts, src/compiler/axis.ts, src/compiler/data.ts, src/compiler/legend.ts, src/compiler/scale.ts, src/compiler/time.ts, src/schema/axis.schema.ts, src/schema/config.schema.ts, src/timeunit.ts, test/compiler/Model.test.ts, test/compiler/axis.test.ts, test/compiler/data.test.ts, test/compiler/scale.test.ts
Addresses parts of #145
* Adds additional time units such as `yearmonth`, `yearmonthday`, `hoursminutes`, ...
* Use timestamps internally for temporal data even if the data is being aggregated.
* When time unit is `month`, `day`, `hours`, `minutes`, or `seconds`, vl automatically adds missing points to the domain. Previously the domain was set directly. Now, vl creates a new data source. 
* Allow customization of time format.
=> More time units

docs/config.md, src/compile/Model.ts, src/compile/axis.ts, src/compile/data.ts, src/compile/facet.ts, src/compile/mark-area.ts, src/compile/scale.ts, src/schema/config.cell.schema.ts
- Apply `axis.grid` of `row` and `column` to our customized grid built by a rule mark group instead of passing it to the row’s scale. Also remove the redundant `config.cell.gridShow`.  Fixes #943
- Apply `scale.padding` of `row` and `column` to our cell padding layout calculation & remove the redundant `config.cell.padding`. Fixes #917
- Set ROW and COLUMN’s padding to 0 if Y and X are not mapped respectively. Fixes #822
=> Revise cell config

src/compile/scale.ts
`bandWidth` would override `range` anyway; therefore, make `bandWidth` a part of range mix-ins.
=> Do not output range when we output bandWidth already

src/compile/mark-point.ts, src/compile/util.ts, test/compile/mark-point.test.ts
- consolidate point-based marks
- make square & circle support `config.mark.filled`  fixes #963
- unit-test scaffolding (left as an exercise for our junior team members)
=> consolidate point-based marks + make square & circle support `config.mark.filled`

examples/trellis_scatter.json, src/schema/config.schema.ts, test/compile/Model.test.ts
With this change, by default we don't see the legend label issues from #497.
=> By default, don’t pass a number format to vega.

docs/index.md
The <title> tag is required by the W3C HTML5 validator at https://validator.w3.org/nu/
=> Added <title> tag to example pages

docs/index.md
Mark page shows 'circle', 'square' and 'tick' as possible mark types but the table in the main documentation page leaves it out.
=> Missing supported mark types in documentation page

src/channel.ts, src/compile/mark.ts, src/compile/scale.ts, src/schema/config.marks.schema.ts, src/schema/encoding.schema.ts, src/schema/fielddef.schema.ts
- Make `detail.sort` the way to sort mark layer order  (documentation will follow later)  part of #993
- Correct the schema
- `path` and `detail` should have `sort`
- `text` (and future `label`) should not have sort
- consolidate positionalField
(More schema refactor will follow this PR)
=> Make `detail.sort` the way to sort mark layer order + Correct the schema 

site/docs/config.md, site/docs/encoding.md, src/compile/Model.ts, src/compile/legend.ts, src/compile/mark-point.ts, src/compile/util.ts, src/schema/config.marks.schema.ts, src/schema/encoding.schema.ts, test/compile/mark-point.test.ts
- Migrate
- `color.value` => `config.mark.color`
- `size.value` => `config.mark.size|barWidth|tickWidth|fontSize`
- `shape.value` => `config.mark.shape`
part of #1029
@domoritz  I also rebase!  (Now that I realize that github works fine with rebase if we force push -- I re-read about it one more time and will try to give it a shot!)
=> Replace value with config since value should be in the data domain rather than visual domain

site/docs/encoding.md, src/compile/Model.ts, src/compile/legend.ts, src/compile/mark-point.ts, src/compile/util.ts, src/schema/fielddef.schema.ts, test/compile/mark-point.test.ts
I add separate case for value instead of using `||` with config because in the future, value might refer to parent.  
Fixes  #1029.  (For `datum`, I'm adding #1051 for doing later with composition)
=> Bring back `encoding.<channel>.value`

src/compile/Model.ts, src/compile/layout.ts, src/compile/mark-point.ts, src/compile/mark-text.ts, src/compile/mark-tick.ts, src/compile/scale.ts, src/schema/config.schema.ts, src/schema/fielddef.schema.ts, test/compile/mark-point.test.ts
- Make `x`'s `bandWidth` 90 if `mark` = `text` and `x` is ordinal scale by default  (otherwise `bandWidth` = `21` for `x` and `y`)
- Do not refer to x&y's `bandWidth` when it doesn't exist.  (And add TODO refer to the future `config.scale.bandWidth` / `config.scale.textBandWidth`)
- Remove `config.textCellWidth`, which is out of place
Fix #724
=> Flexible x-scale's `bandWidth` for text on ordinal + remove `config.textCellWidth`

src/compile/compile.ts, test/compile/compile.test.ts, tsconfig.json
Fixes bug in #992 where non-ordinal marks are incorrectly set to use layout as a data source in the root group
=> Fix incorrect assignment of layout as a data source (Issue #992)

examples/docs/scatter_aggregate_detail.json, examples/docs/scatter_color.json, examples/docs/scatter_color_order.json, examples/docs/stacked_bar_h_order.json, examples/scatter_connected.json, site/docs/encoding.md
It is worth noting that using `detail` doesn't make much sense without labeling / tooltips.   (No way to know which mark represent which group).  Similarly, we don't know which part of the connected scatter plot is the beginning of the path.  
So I don't know if actually should hide the docs for these until we ship either labeling or tooltips?
=> Add missing examples to encoding.md + Minor Editing

src/compile/scale.ts
I was reading all references of `scaleType` and try to understand and found this weird line.
=> Change condition that temporal field has linear scale to time scale

site/docs/scale.md
Note: 
For ordinal ramp, I think the scale type in the API should still be `ordinal` but we can have another property called `ramp` (boolean) for distinguishing between ordinal ramp and ordinal mapping to discrete values.
=> Write scale's intro, type, and domain.  Also reorder things a bit.

src/compile/axis.ts, src/compile/data.ts, src/compile/facet.ts, src/schema/config.cell.schema.ts
- Drawing grid for facet inside each cell and draw border around each cell.  Fix #920 
- Add extra rule mark to the manually drawn grid to close the table when faceting without inner x/y axis. Fix #803
- always add offset to facet's axis
- Don't use band of row/column scales to make sure the border of the cell works correctly
=> Facet Styling

src/compile/Model.ts, src/compile/data.ts, src/compile/facet.ts, src/compile/scale.ts, src/compile/stack.ts, test/compile/scale.test.ts
- add `model.scale()`
- always refer to scale via `model.scale()` rather than via fieldDef
This is a refactor for 
(1) preparing to split scale's from encoding in the model  (for composition)
(2) enable declaration of different channelDefs -- some of them do not have scales. 
I have run x-compile and x-diff to see that all output from the examples still remain the same.
=> Refactor: add `model.scale()`  and always use it rather than fieldDef

src/compile/Model.ts, src/compile/data.ts, src/compile/facet.ts, src/compile/scale.ts, src/compile/stack.ts, src/compile/util.ts, src/schema/encoding.schema.ts, src/schema/fielddef.schema.ts, src/schema/sort.schema.ts, test/compile/scale.test.ts
- Add interfaces for different types of channelDefs 
- Refactor sort typings.
- Refer to sort via `model.sort()` and remove it from FieldDef
- remove `legend` from FieldDef, add `config.legend` and initialize it correctly
Please merge #1106 first!  
(See [Branch Specific Diff](https://github.com/uwdata/vega-lite/compare/kw/scale...kw/channelDef))
=> Add interfaces for different types of channelDefs + Refactor 

src/compile/config.ts, src/compile/legend.ts, src/compile/mark-line.ts, src/compile/mark-point.ts, src/compile/mark-tick.ts, src/compile/util.ts, test/compile/mark-point.test.ts
My further fix for your #1113.  Please merge this into #1113 and feel free to merge #1113 to master. 
-  Correct Color Field/Value/Config precedence -- fixes #1114
The precedence is now: color field > color value > fill/stroke config > color config
- eliminate the complicated COLOR_MODE
- Only exclude either fill or stroke config for legend + refactor
=> Correct Color Field/Value/Config precedence + Refactor

examples/specs/scatter_color_custom.json, examples/specs/scatter_color_ordinal.json, examples/specs/scatter_color_ordinal_custom.json, examples/specs/scatter_color_quantitative.json, site/docs/scale.md, src/compile/Model.ts, src/compile/scale.ts, src/compile/time.ts, src/schema/scale.schema.ts
- Refactor scale property signature & check if the property is applicable to a scaleType
- Remove unused `outerPadding`  (We never use band scale, so `outerPadding` is never used.)
- `scale.nice` using smallest timeUnit for time scale
- 	Do not allow customized range for x, y, row & column
- Update Scale's docs
=> Revise scale properties rules & Refactor & Scale Docs

_layouts/docs.html, _layouts/page_submenu.html, site/static/main.css
- Increased click area
- added `break` instead of empty sidebar item
=> Quick-fixes to docs (sidebar)

bin/vl2png, bin/vl2svg, bin/vl2vg, scripts/generate-images.sh
A follow-up to #1188, where the goal is to get usable CLI tools after running `npm install -g vega-lite`.
This fixes two search-path issues that made `vl2svg` and `vl2png` work only when run from the Vega-Lite source directory. As suggested by @domoritz, I tried to avoid breaking any scripts that clearly *want* to run from inside the source directory, without a global install. Namely, `npm run build:images` still works.
Please let me know if I broke anything else!
=> Make vl2svg and vl2png scripts actually work when installed

examples/specs/stacked_bar_h_order.json
I was reading the docs and thought the `type` of `yield sum` should be `quantitative` instead of `nominal` in the `stacked bar horizontal order` example.
=> Correct type for stacked bar horizontal order example

src/config.ts
Vega's strokeDashOffset is a number (or signal), not an array of numbers.
=> Make strokeDashOffset a number

src/channel.ts, src/compile/scale.ts, src/compile/unit.ts, test/compile/scale.test.ts
- refactor scale,  remove scaleType as a parameter since we already pass `scale` around.  
- fix incorrect test for bin scale 
- correct `parseMainScale`, `parse...`
(A step toward #1214 – but let's review this separately first)
=> refactor scale

src/vl.ts
An external tool would like to be able to access default spec config via `vl.config.defaultConfig`
=> Export config

examples/examples.test.ts
This doesn't really serve a purpose other than semantics, but I am debugging a breaking test and its nice to know which compilation is breaking. This asserts validation for both vl and the compiled vg.
=> Seperate tests for schema validation

site/docs/encoding.md
At least we should have a reference to not confuse people about why we did not put it there. This can be reverted once we have composition.
=> Add row/column to the encoding docs

src/compile/common.ts, src/compile/time.ts, src/timeunit.ts
Export `timeunit.format(timeUnit, abbreviated)` because tooltip needs to translate VL timeUnit to the time string specifier.
=> Export timeunit.format() for VgTooltip

site/docs/timeunit.md
=> Document time units. Fixes #1277

src/compile/scale.ts, test/compile/scale.test.ts
Fix #1244
Now the following no longer throws error
```js
{
"encoding": {
"x": {"field": "Horsepower","type": "quantitative"},
"size": {"field": "Origin","type": "ordinal"}
}
}
```
=> Read bandSize config if the scale does not exist

src/config.ts
The interpolate values of "basis-closed", "bundle", and "cardinal-closed" are not valid in the vega spec (despite being valid D3 interpolations).
Should interpolate be an enum? I can implement that if you like.
=> Create LineInterpolation with valid interpolation options

examples/specs/stacked_bar_size.json, src/compile/stack.ts
Fix #1243 
Enable stack for size channel
stack now behaves correctly with size channel
=> Size support stack

site/docs/axis.md, site/docs/config.md, src/axis.ts, src/compile/axis.ts, test/compile/axis.test.ts
Support more properties for axis
=> Axis properties

src/compile/config.ts, test/compile/mark/bar.test.ts, test/compile/mark/tick.test.ts
Fix #1347 
Bug is the default orient should be vertical, instead of horizontal.
Now this spec will give the following output correctly.
```
{
"description": "Shows the relationship between horsepower and the numbver of cylinders using tick marks.",
"mark": "tick",
"encoding": {
"x": {"field": "Horsepower", "type": "quantitative"},
"y": {"field": "Cylinders", "type": "ordinal"}
}
}
```
=> fix bug tick orient inverted

src/compile/common.ts, src/compile/legend.ts, test/compile/legend.test.ts
Fix #1314 
Now legend won't take `strokeDash` and `strokeDashOffset` from config for all marks.
the following spec create the correct legend symbol now.
```
{
"data": {"url": "data/stocks.csv", "formatType":"csv"},
"mark": "line",
"encoding": {
"x": {"field": "date", "type": "temporal"},
"y": {"field": "price", "type": "quantitative"},
"color": {"field": "symbol", "type": "nominal"}
},
"config": {
"mark": {
"strokeWidth": 1,
"strokeDash": [ 24, 20 ] ,
"strokeDashOffset": 24
}
}
}
```
=> Disable default strokeDash for legend

site/docs/config.md
Fix the first part of #1237 
The problem of cannot change the color of the facet grid is because there's a mismatching in documentation, where `gridColor` should be `color`, where `gridOpacity` should be `opacity` and `gridOffset` should be `offset`. 
Now the following spec gives the correct output.
```
{
"mark": "text",
"encoding": {
"row": {"field": "Origin","type": "ordinal"},
"column": {"field": "Cylinders","type": "ordinal"},
"color": {
"aggregate": "mean",
"field": "Horsepower",
"type": "quantitative"
},
"text": {
"aggregate": "count",
"field": "*",
"type": "quantitative"
}
},
"config": {
"grid": true,
"mark": {"applyColorToBackground": true},
"facet": {
"cell": {"stroke": "blue","strokeWidth": 4},
"grid": {"color": "red","opacity": 0.5,"offset": …
```
=> Fix mistaching in documentation for facet grid

examples/specs/bubble_health_income.json, examples/vl-examples.json
Add gapminder health vs income example to vega-lite test gallery and site gallery.
test gallery look:
site gallery look:
=> Add gapminder health vs income example to galleries

src/compile/axis.ts, test/compile/axis.test.ts
Fix the second part of #1237.
Now the spec below generate the right output.
```
{
"data": {
"values": [
{"a": "A","b": 28,"c": "x"}, {"a": "B","b": 55,"c": "x"}, {"a": "C","b": 43,"c": "x"},
{"a": "A","b": 28,"c": "y"}, {"a": "B","b": 55,"c": "y"}, {"a": "C","b": 43,"c": "y"}
]
},
"mark": "square",
"encoding": {
"column": {
"field": "c", 
"type": "ordinal"
},
"x": {
"field": "a", 
"type": "ordinal",
"axis": {
"grid": true,
"layer": "front",
"properties": {
"labels": {
"fill": { "value": "red" }
},
"grid": {
"stroke": { "value": "red" },
"strokeWidth": { "value": 5 }
}
}
}
},
"y": {
"field": "b", 
"type": "quantitative",
"axis": {
"grid": true,
"layer": "front",
"properties": {
"labels": {
"fill": { "value": "green" }
},
"grid": {
"stroke": { "value": "green" },
"strokeWidth": { "value": 5 …
```
=> Facet generates customized grid

src/compile/mark/point.ts, src/config.ts, src/fielddef.ts
Refactor Point 
- Eliminate `model.has()`
- Split `properties()` into multiple methods that takes `fieldDef`, `scaleName`, `config` (and possibly `scale`) as input that returns Vega's `ValueRef`.    (TODO: declare interface)
=> Refactor point by splitting properties into multiple methods

src/compile/data/nullfilter.ts
Fix #1411
Question
- Should we only filter this for date field?
- Should we rename `filterNull` to `filterInvalidValues` since it's no longer just null? 
Now temporal line chart sorts correctly!
=> Also filter NaN values

examples/specs/overlay_area_full.json, examples/specs/overlay_area_short.json, examples/specs/overlay_line_full.json, examples/specs/overlay_line_short.json, src/compile/config.ts, src/config.ts, src/spec.ts, src/util.ts, test/spec.test.ts
Fix #508   (Don't squash -- multiple things included)
- add pick, omit method 
- Also change area's default opacity to 0.6 (Inspired by Tableau and many other toolkits)
```
{
"description": "Google's stock price over time.",
"data": {"url": "data/stocks.csv", "format": {"type": "csv"}},
"transform": {"filter": "datum.symbol==='GOOG'"},
"mark": "line",
"encoding": {
"x": {"field": "date", "type": "temporal"},
"y": {"field": "price", "type": "quantitative"},
"color": {"field": "symbol", "type": "nominal"}
},
"config": {"overlay": {"line": true}}
}
```
is equivalent to 
```
{
"layers": [
{
"description": "Google's stock price over time.",
"data": {"url": "data/stocks.csv","format": {"type": "csv"}},
"transform": {"filter": "datum.symbol==='GOOG'"},
"mark": "line",
"encoding": {
"x": …
```
=> [WIP] Add pick method & overlay shortcut

src/compile/data/filter.ts, src/filter.ts, test/filter.test.ts
Separate `CompareFilter` from `RangeFilter` so that we can satisfy `oneOf` condition in the JSON schema.
Note that we need either https://github.com/YousefED/typescript-json-schema/issues/46
or https://github.com/YousefED/typescript-json-schema/issues/47 to
support combination of lt/lte and gt/gte in the schema.  (The logic works fine but those combo will fail to validate)
For now, let's support non-combo version for `CompareFilter`.
=> Separate `CompareFilter` from `RangeFilter`

site/docs/transform.md, src/compile/data/nullfilter.ts, src/transform.ts
Fix #1426 using @arvind's suggestion.
=> rename `filterNull` to `filterInvalid` since we also filter NaN values

src/scale.ts
Correct `scale.domain` schema: it can only be a number[] or string[], but not string.
=> Correct scale.domain schema: it can only be a number[] or string[], but not string.

src/timeunit.ts, test/timeunit.test.ts
Adds the `timeunit.convert` method, which takes in a date and timeunit and returns a date that only has the specified timeunits from the provided date. Example:
convert('yearmonth', '2000-12-04 07:58:14') -> '2000-12-00 00:00:00'
=> Add timeunit date conversion method

src/compile/data/filter.ts, src/filter.ts, test/compile/data/filter.test.ts, test/filter.test.ts
Fix #1491 
- Move src/compile/data/filter.ts's getFilterExpression to be expresssion in src/filter.ts
- Move src/compile/data/filter.ts's valueExpr to src/filter.ts (method is required by expression)
=> Move `getFilterExpression` method from src/compile/data/filter.ts to src/filter.ts as `expression`

examples/specs/scatter_shape_custom.json, site/docs/config.md, site/docs/encoding.md, site/docs/legend.md, src/compile/legend.ts, src/config.ts, src/encoding.ts, src/legend.ts, test/compile/legend.test.ts
Vega now permits custom shapes: https://github.com/vega/vega/wiki/Custom-Shapes
They work with vega-lite "out of the box":
```json
{
"description": "A scatterplot with custom star shapes.",
"encoding": {
"x": {"field": "Horsepower","type": "quantitative"},
"y": {"field": "Miles_per_Gallon","type": "quantitative"},
"size": {"field": "Cylinders", "type": "quantitative"}
},
"config": {
"mark": { 
"shape": "M0,0.2L0.2351,0.3236 0.1902,0.0618 0.3804,-0.1236 0.1175,-0.1618 0,-0.4 -0.1175,-0.1618 -0.3804,-0.1236 -0.1902,0.0618 -0.2351,0.3236 0,0.2Z"
}
}
}
```
However, this spec does not pass schema validation, since the SVG path is not one of a fixed set of enums. This PR removes the shape enum constraint so that custom SVG paths will pass …
=> Un-constrain shape from a fixed enum for custom shapes

src/compile/data/data.ts, src/compile/data/nullfilter.ts, test/compile/data.test.ts
- Only add `NaN` filter for quantitative and temporal fields
- Don't add filters for `*` (of count fields)
cc: @domoritz  I'll merge this as this solves problem in https://github.com/uwdata/voyager2/issues/82, but feel free to send a follow up comment.
=> Fix bugs in `filterInvalid`

src/compile/legend.ts
- Remove incorrect line added in #1446 
This is not the most ideal fix.  We should refactor it before the next major release but at least it's removing the bug.   
Fix #1500
Now the same spec in #1500 looks okay like this:
=> Filled Incorrect Color Legend for Point Mark Chart

src/compile/data/source.ts, test/compile/data.test.ts
Fix #1453, Fix #1485
cc: @domoritz  turns out this is a 1-line quick fix for now but you'll have to make sure that it still works correctly in your layering branch, which completely rewrites this part of logic.
=> Make `nullFilter` comes after `formula` transform

src/fielddef.ts, src/spec.ts, src/util.ts, test/fielddef.test.ts
Remove unused `vl.fieldDef.cardinality`, `vl.spec.alwaysNoOcclusion`, `vl.spec.getCleanSpec`
and relevant methods (which should be migrated to be a part of CompassQL's `Schema`)
=> Remove unused `vl.fieldDef.cardinality` and relevant method

src/compile/common.ts, src/compile/data/colorrank.ts, src/compile/legend.ts, src/compile/mark/bar.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, test/compile/scale.test.ts, test/compile/timeunit.test.ts
This way we always get the type correctly.
=> For specific channel (e.g. x) use `model.encoding().x` instead of `model.fieldDef(X)`

src/timeunit.ts
The domain should be [0,1,2,3] instead of [0,3,6,9] since the output dateTimeExpr multiplies the quarter value by 3
Fix #1531, Fix #1532
I haven't inspected each individual value in the plot as we don't have tooltip in the editor yet, but the output seems correct to me.  (cc: @zeningqu)
Thanks @willium for hinting
=> Correct quarter's domain to produce correct month

package.json, src/vl.ts
This pulls the version directly from `package.json` and removes the need for a transform to enable better compatibility with build tools like browserify and webpack. Note webpack users will still need to have the [json-loader](https://github.com/webpack/json-loader) enabled. 
This is related to vega/vega#369 in the overall goal of improving compatibility with the javascript ecosystem.
Please:
=> Remove browserify-versionify to fix webpack/browserify compatibility

src/compile/data/filter.ts, src/compile/data/formatparse.ts, src/compile/data/formula.ts, src/compile/data/nullfilter.ts, src/compile/model.ts, test/compile/data.test.ts
- Make filterInvalid read from parent to make sure that we always correctly filter invalid values.
- Fix #1534 – apply filterInvalid for inner spec of a faceted plot
- Replace `model.transform()` with `model.calculate|filter|filterInvalid()` to avoid calling filterInvalid directly
=> Make filterInvalid read from parent to make sure that we always correctly filter invalid values.

src/timeunit.ts
thus we automatically include February 29th.
I believe this is the correct behavior.
Fix #1557
=> Add month-date back since we use year 0 

examples/specs/point_custom_time_domain_values.vl.json, site/docs/axis.md, site/docs/legend.md, site/docs/scale.md, src/axis.ts, src/compile/axis.ts, src/compile/legend.ts, src/compile/scale.ts, src/datetime.ts, src/legend.ts, src/scale.ts, test/compile/axis.test.ts, test/compile/legend.test.ts, test/compile/scale.test.ts, test/datetime.test.ts
Fix #1516 
Please see each commit for details.  (Don't squash -- they are atomic!)
=> DateTime support for scale.domain, axis.values, legend.values

src/compile/common.ts, src/spec.ts, test/spec.test.ts
=> [WIP] Get fieldDefs for for LayerSpec, FacetSpec, ExtendedFacetSpec

site/docs/config.md, src/aggregate.ts, src/compile/config.ts, src/compile/unit.ts, src/spec.ts, src/stack.ts, test/stack.test.ts
(You can review each atomic commit individually.)
- Disable stack when the aggregated axis is a non-linear scale.
- Use opacity = 0.7 for unstacked bar with color/detail/size  (This will make it clearer that the output is a layered bar chart.) 
- Only automatically enable stacking if the aggregation op is summative
Fix #1582
=> Adjust Stack Rules

examples/specs/diverging_color_points.vl.json, site/docs/scale.md
Provide example for #449 
Modified doc for scale to include this example
=> Add example for diverging color

.gitignore, .npmignore, package.json, scripts/deploy.sh, site/static/main.ts, src/compile/data/bin.ts, src/compile/data/formatparse.ts, src/compile/data/formula.ts, src/compile/data/nullfilter.ts, src/compile/data/source.ts, src/compile/data/timeunit.ts, src/compile/data/timeunitdomain.ts, src/compile/legend.ts, src/compile/model.ts, src/datetime.ts, src/validate.ts, src/vega.schema.ts, src/vl.ts, test/util.ts, tsconfig.json
Consuming `vega-lite` as a commonjs package via the typescript compiler was difficult/impossible, as, rather than shipping with generated type definition files, it shipped with the original source typescript. This caused issues where compiler setting mismatches (`noImplicitAny`, `strictNullChecks`, and so on) would expose issues in `vega-lite`'s implementation as part of a consumer's build, which is undesirable.
Turning on declaration emit (and fixing declaration visibility errors), allows the compiler to automatically generate declaration files for the project, which make the project easy to use by a typescript consumer.
=> Enable declaration emit

src/compile/facet.ts, src/compile/layer.ts, src/compile/model.ts, src/compile/scale.ts
Use `model.name()` during scale parsing to name scale
and make `model.scaleName()` only return values if the scale exists.
This is a good preparation for supporting projection.
I don't think I'll do projection now given how much that changes in Vega 3,
but since I have already done this part and it does no harm to the current code. 
Let's merge this part first.  
I have checked that all vega output of example specs remain the same.
=> Only return scaleName if the scale exists

README.md, package.json, scripts/deploy.sh
- Bump version  
- use "pre" tag with `npm publish`
- do not push to gh-pages
=> Kick Off 2.0 Development

src/compile/mark/area.ts, src/compile/mark/bar.ts, src/compile/mark/line.ts, src/compile/mark/point.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, src/compile/mark/valueref.ts, src/compile/scale.ts, src/fielddef.ts, test/compile/mark/area.test.ts, test/compile/mark/bar.test.ts, test/compile/mark/line.test.ts
Fix #1284
Common methods are in `src/compile/mark/valueref.ts`.
Mark's code is now cut by roughly half (-711, +376)
More details in each (atomic) commit.
=> Extract common methods for marks

src/compile/common.ts, src/compile/data/bin.ts, src/compile/data/summary.ts, src/compile/mark/mark.ts, src/compile/mark/valueref.ts, src/fielddef.ts, src/vega.schema.ts, test/compile/data/bin.test.ts, test/compile/mark/bar.test.ts, test/compile/mark/mark.test.ts
Get rid of formula transform for `bin_mid` and use inline signal instead
Fix #1681
=> Get rid of formula transform for `bin_mid` and use inline signal instead

site/docs/data.md
Fixing incorrect links to two anchors. These are explicitly defined on the same page, so only one markdown file is affected.
=> Dead links to anchors

examples/specs/trellis_barley.vl.json
Now the aggregation function, sorting order, and scale (not starting from zero) are similar to the original plot!
cc: @jakevdp -- I saw that you use this example in Altair example too. You might want to consider updating.  (Btw, Happy Thanksgiving!)
We should cherry pick this to 1.x if we were to update the github pages too.
=> Correct our reproduction of becker's barley

package.json
See https://github.com/danvk/source-map-explorer/blob/master/README.md#generating-source-maps
Now we can generate
=> Correctly generate source maps for minified file.

src/compile/scale.ts, src/scale.ts, test/compile/scale.test.ts, vega-lite-schema.json
Address part of #1711 (Still haven't test stuff related to legend, but it's not in the scope of this PR)
- Scale's `zero` should be true by default for `size`
- Break size's range calculation into sizeRangeMin and sizeRangeMax
- `sizeRangeMin` depends on scale.zero
- `sizeRangeMax` depends on scale.bandSize (rangeStep)
- Replace scale configs `bar/font/rule/tick/pointSizeRange` with `minBar/Tick/Rule/Point/TextSize` (and `max...`) such as `minBarSize`
Questions:
- I think we should consolidate mark-specific mark config `config.mark.barXXX,tickXXX` with the `config.scale.{min/max}{Bar/Tick/Rule/Point/Text}Size` above?
- For example, we could have `config.bar.size` (if size is not mapped) and `config.bar.sizeRangeMin/Max` (or shorter `config.bar.min/maxSize`). This will make configs way …
=> [WIP] Add rule for using quantitative field with size

site/docs/scale.md, src/compile/scale.ts, src/scale.ts, test/compile/scale.test.ts, vega-lite-schema.json
=> Only apply `config.scale.round` for x, y, row, column

src/compile/config.ts, src/compile/layout.ts, src/compile/mark/mark.ts, src/compile/mark/rect.ts, src/compile/mark/valueref.ts, src/compile/model.ts, src/compile/scale.ts, src/compile/unit.ts, src/scale.ts, test/scale.test.ts
Fix #1753. 
The current way we change `isContinuous()` in #1746 will cause bug due to terminology mismatch as described in #1753.  This will make things correct and you can use `hasContinuousDomain()` in #1746 instead of `isContinuous()`. 
- Add test that a scale should either hasContinuousDomain or hasDiscreteDomain.
Please merge this and I'm happy to resolve conflicts in #1746 for you.
=> Distinguish between `isContinuousToContinuous()` and `hasContinuousDomain()` + rename `isDiscreteScale()` => `hasDiscreteDomain()`

examples/specs/bar_filter_calc.vl.json, examples/specs/bar_grouped.vl.json, examples/specs/bar_grouped_horizontal.vl.json, examples/specs/bar_layered_transparent.vl.json, examples/specs/stacked_bar_normalize.vl.json, examples/specs/stacked_bar_population.vl.json, examples/specs/stacked_bar_sum_opacity.vl.json, examples/specs/text_scatter_colored.vl.json, examples/specs/trellis_bar.vl.json, src/axis.ts, src/compile/axis.ts, src/compile/facet.ts, src/scale.ts, test/compile/facet.test.ts, vega-lite-schema.json
Now we can get reasonable facet.
Note that we will to handle the following issues later:
- `paddingOuter` for point doesn't make (may need to just output `padding` if we don't wanna change vega https://github.com/vega/vega/issues/679
- The grid line is too long.
- Need to deal with axis grid layer
- If there is null value, the layout is still incorrect for both facet and non-facet plot. (This should be fixed in Vega https://github.com/vega/vega/issues/678)
cc: @domoritz
=> Facet clean up and a few more fixes 

examples/specs/scatter_color_zindex.vl.json, examples/specs/scatter_connected.vl.json, src/channel.ts, src/compile/config.ts, src/compile/unit.ts, src/encoding.ts, src/spec.ts, test/spec.test.ts, vega-lite-schema.json
Note that unlike VL1, now Vega 3 has zindex properties. Thus layer order can be mapped to a scale (haven't implemented yet) while stack order and path order cannot.
Thus, I think it makes sense to consolidate  `order` channel for sorting line order / stack order and have zindex as a separate channel that supports scale. As a result, we can free up `path` for geopath.
(Forked from #1776 -- Please merge #1776 first.)
=> Remove `path` channel as we can use `order` channel for sorting line order instead

src/compile/common.ts, src/compile/data/data.ts, src/compile/data/pathorder.ts, src/compile/data/stack.ts, src/vega.schema.ts, test/compile/data/datatestutil.ts, test/compile/data/pathorder.test.ts
(Replacing the original inline sort transform that serves the same purpose)
Before:
After:
=> Add pathOrder data component to support sorting line

src/compile/data/data.ts, src/compile/data/stack.ts, test/compile/data/data.test.ts, test/compile/data/stack.test.ts
1. Make pathOrder's collect transform always included in the last data source (can be raw/summary/stacked)
2. Make stack's `impute` and `stack` transforms always include both binned field's start and end
Fix #1805
=> Make stacked area chart with imputation render correctly.

src/compile/compile.ts, src/compile/model.ts, src/config.ts, src/spec.ts, test/compile/compile.test.ts, vega-lite-schema.json
(as suggested by Jeff)
Fix #1822
=> Add top-level `padding` and make it = 5 by default

src/channel.ts, src/compile/facet.ts, src/compile/unit.ts, src/fielddef.ts, src/log.ts, src/type.ts, test/fielddef.test.ts, test/type.test.ts
- Consolidate `fieldDef.normalize(), defaultType()`
- No longer automatically adding `aggregate: 'min'` to order and path (I don't think it's a good default anymore, not sure why I added it back then.
- Make `type.getFullName()` return undefined if the input type is invalid + add more tests
- Remove unnecessary `SHORT_TYPE` and `TYPE_FROM_SHORT_TYPE` dictionary in `type.ts`
Fix #1651
=> Add warning if type is missing and augment default type

src/compile/mark/point.ts, src/compile/scale/range.ts, src/config.ts, src/mark.ts, vega-lite-schema.json
(Config for `circle` and `square` should not include `shape` and `shapes` properties)
=> Distinguish between PointConfig and SymbolConfig.

src/compile/common.ts, src/compile/facet.ts, src/compile/layer.ts, src/compile/mark/area.ts, src/compile/mark/bar.ts, src/compile/mark/base.ts, src/compile/mark/line.ts, src/compile/mark/point.ts, src/compile/mark/rect.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, src/compile/model.ts, src/compile/unit.ts, src/vega.schema.ts
Also, use `e` as variable name instead of `p` (from the old name "properties")
(Prepare for @yuhanlu to add VgEncodeEntry as a part of #1278)
=> Add any `VgEncodeEntry` type and refer to it

src/compile/common.ts, src/compile/config.ts, src/compile/facet.ts, src/compile/legend/encode.ts, src/compile/mark/bar.ts, src/compile/mark/line.ts, src/compile/mark/point.ts, src/compile/mark/rect.ts, src/compile/mark/text.ts, src/compile/mark/valueref.ts, src/compile/scale/init.ts, src/compile/scale/type.ts, src/compile/unit.ts, src/encoding.ts, src/facet.ts, src/fielddef.ts, src/legend.ts, src/mark.ts, src/stack.ts, vega-lite-schema.json
Fix #1861 
`ChannelDef = FieldDef | ValueDef`
Rename `*ChannelDef` / `ChannelDef*` => `*FieldDef`
- `ChannelDefWithScale` => `ScaleFieldDef`
- `PositionChannelDef` => `PositionFieldDef`
- `ChannelDefWithLegend` => `LegendFieldDef`
- `OrderChannelDef` => `OrderFieldDef`
=> Make interfaces and schema for `FieldDef`, `ValueDef` more precise

src/axis.ts, src/compile/axis/encode.ts, src/compile/axis/parse.ts, test/compile/axis/encode.test.ts
- Remove unnecessary default config
- Don't output labels.text = ''  simply use `label` flag
- Correct the code for checking if part of axis is enabled. 
cc: @YuhanLu this refactor will simply your task a bit :)
=> Refactor Axis

src/compile/scale/init.ts, src/compile/scale/type.ts, src/scale.ts, src/type.ts, test/compile/scale/type.test.ts
Instead of taking a whole FieldDef and specified Scale, only take parts that matter.  
(for easier usage in CompassQL)
=> Refactor scale/type to take more minimalist input

src/compile/mark/area.ts, src/compile/mark/bar.ts, src/compile/mark/base.ts, src/compile/mark/line.ts, src/compile/mark/mark.ts, src/compile/mark/point.ts, src/compile/mark/rect.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, test/compile/mark/area.test.ts, test/compile/mark/bar.test.ts, test/compile/mark/line.test.ts, test/compile/mark/point.test.ts, test/compile/mark/rect.test.ts, test/compile/mark/rule.test.ts, test/compile/mark/text.test.ts, test/compile/mark/tick.test.ts
so that we can leverage Vega mark config for marks that are not Vega marks
=> Add mark role to the output  + refactor mark compiler's vgMark

src/compositemark.ts, src/mark.ts, src/spec.ts, src/vl.ts, vega-lite-schema.json
- Provide API for registering new type of CompositeMark
- Remove AnyMark as "any mark" can be any string as long as the string is a primitive mark or a  registered composite mark
- Add isPrimitiveMark() instead of isCompositeMark()
=> Separate CompositeMark from (primitive) Mark

examples/specs/area.vl.json, examples/specs/bar_grouped.vl.json, examples/specs/bar_grouped_horizontal.vl.json, examples/specs/line_month.vl.json, examples/specs/stacked_area.vl.json, examples/specs/stacked_area_normalize.vl.json, examples/specs/stacked_area_stream.vl.json, src/axis.ts, src/compile/axis/encode.ts, src/compile/axis/parse.ts, src/compile/axis/rules.ts, src/compile/common.ts, src/compile/facet.ts, src/compile/legend/encode.ts, src/compile/mark/text.ts, src/compile/unit.ts, src/vega.schema.ts, test/compile/axis/encode.test.ts, test/compile/axis/parse.test.ts, test/compile/axis/rules.test.ts, test/compile/common.test.ts, test/compile/facet.test.ts, test/compile/unit.test.ts, vega-lite-schema.json
Update Axis Properties and Config.  (Part of #1845)
- Rename `axisWidth` to `domainWidth`, `axisColor` to `domainColor`, `tickLabelColor` to `labelColor`, `tickLabelFont` to `labelFont`, `tickLabelFontSize` to `labelFontSize`, `tickPadding` to `labelPadding`, `titleOffset` to `titlePadding`
- Separate Axis from AxisConfig. Make these properties only available as `Axis` properties:  `domain `, `grid `, `labels `, `labelMaxLength `, `labelPadding `, `maxExtent`, `minExtent`, `offset `, `position `, `shortTimeLabels `, `ticks `, `tickCount `, `tickSize`, `titleMaxLength`, `titlePadding`, `zindex`
- Remove `labelAlign`, `labelBaseline`, `subdivide`, `tickSizeMajor`, `tickSizeMinor`, `tickSizeEnd` from Axis Config
- Remove related code for Vega Axis config as Vega parser will handle these …
=> Audit Axis Config

src/mark.ts
This reverts commit f895054a0dd611e3ffed347a96dddcaf74fa1c32.
cc: @willium turns out we actually use this everywhere in CompassQL... removing it will be a disaster --- sorry for merging conflicts
=> Revert "Remove unnecessary Mark namespace"

src/axis.ts, src/compile/facet.ts, src/compile/unit.ts
(It should be *Base as labelMaxLength is an Axis property too.)
Also rename one local variable for consistency
cc: @Yuhanlu
(Please use the same format for `VlOnlyLegendBase`)
I think we should also ask Jeff if he wanna add `labelMaxLength` and `titleMaxLength` to Axis/Legend and their config in Vega.  (Maybe we can get rid of `VlOnlyAxis/LegendBase` and complicated code cause by it.)
=> Rename VlOnlyAxisConfig => VlOnlyAxisBase

src/compile/mark/mixins.ts, src/compile/selection/selection.ts, src/encoding.ts, src/fielddef.ts, test/compile/selection/predicate.test.ts, vega-lite-schema.json
(Merge #1970 first)
@arvind I just added scaffolding code for generating a Vega production rule from our conditional encoding syntax.  
I'll let you take over and add code for how to generate `"test"` property for selection. 
Since we no longer have to deal with how it interacts with transform, I think we're pretty close to have selection really working!
=> Support conditional encoding

src/compile/legend/encode.ts, src/compile/unit.ts, src/legend.ts, src/vega.schema.ts, test/compile/legend/encode.test.ts, test/compile/legend/parse.test.ts, test/compile/unit.test.ts, vega-lite-schema.json
Update Legend Properties and Config. (Part of #1845)
- Add `symbolType`
- Remove `margin`, `symbolShape` from Legend Config
- Separate Legend from LegendConfig. Make these properties only available as Legend properties: `entryPadding`, `orient`, `offset`, `padding`, `tickCount`, `zindex`
- Remove related code for Vega Legend configs
=> Legend Properties/Config refactor

examples/specs/brush.vl.json, examples/specs/paintbrush.vl.json, examples/specs/panzoom_scatter.vl.json, examples/specs/query_widgets.vl.json, examples/vl-examples.json, src/selection.ts, vega-lite-schema.json
Four interactive examples to kick us off:
1. Rectangular brush:
2. Paintbrush
3. Pan & Zoom a Scatterplot
4. Dynamic query widgets -- this one would greatly benefit from `zindex` support (#1684).
=> Initial interactive examples.

build/vega-lite-schema.json, src/compile/mark/area.ts, src/compile/mark/bar.ts, src/compile/mark/base.ts, src/compile/mark/line.ts, src/compile/mark/mark.ts, src/compile/mark/point.ts, src/compile/mark/rect.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, src/config.ts, src/mark.ts, test/compile/common.test.ts
This will be useful for composite marks.  For example, box plot may use bar to implement upper and lower boxes, but config.bar.* should not be applied to these boxes as they represent semantically different things.
Instead, users should able to use role config such as `config.box, config.upperBox, config.lowerBox, config.whisker, config.upper/lowerWhisker` for customizing parts of composite marks.
cc: @mattwchun
=> Allow users to customize role

package.json
This will prevent us from having failed test due to leftover files (e.g., https://github.com/vega/vega-lite/issues/2049)
=> Always clean compiled ts files when we run tsc

src/compile/facet.ts, test/compile/facet.test.ts
Fix #1664 
```
{
"data": {"values": [
{"a": "A","b": 28, "c": "A"}, 
{"a": "B","b": 55, "c": "A"}, 
{"a": "C","b": 43, "c": "A"}
]},
"mark": "bar",
"encoding": {
"x": {
"field": "b", "type": "quantitative", "axis": false
},
"y": {
"field": "a", "type": "nominal", "axis": false
},
"row": {
"field": "c", "type": "nominal",
"axis": {
"title": "", "labelAngle": 0
}
}
}
}
```
=> Fix the bug labelAngle cannot be applied when labelAngle == 0

src/scale.ts
Fix #1922 
Now interpolate support `linear`, `bin-linear`, `log`, `pow`, `sqrt` scale type.
=> correct `interpolate` to support more scale type

src/compile/scale/type.ts, src/log.ts, test/compile/scale/type.test.ts
Fix #1885 
Enable checking on scale type if is supported by data type
=> Enable checking on scale type if is supported by data type

.travis.yml, scripts/build-examples.sh
Fix part of #2068 
If user have GNU parallel installed on their own, build:examples should work in parallel now
=> fix bug parallel build

src/aggregate.ts, src/fielddef.ts, src/log.ts, test/fielddef.test.ts
cc: @mattwchun -- this will allow you to make `aggregate: AggregateOp | 'box plot'` in encoding.ts without causing any bugs
=> make `fieldDef.normalize` drops invalid aggregate

site/docs/axis.md, site/docs/config.md
@YuhanLu  I make further edits to axis.md page.  
I think we reduce the number of heading levels a bit.  The `## Customizing Axis` part isn't really necessary and is, in fact, redundant with the page's intro.
Could you please double check this apply a similar change to `legend.md`.  
Btw, you might find grammarly.com useful as a spell checker.
=> [WIP] Edit Axis Docs

_includes/type-anyof.html, build/vega-lite-schema.json, site/docs/config.md, src/config.ts, src/mark.ts, src/scale.ts, src/toplevelprops.ts, src/vega.schema.ts
Fix part of #1723 
Enable auto generation for config.md
But I have some properties not sure if they are removed. `viewport`, `stacked`, `format`, `shortTimeLabels`.
And there might be some help with adding missing properties for this doc as well. #2114
=> enable auto-generation for config.md

examples/specs/layered_selections.vl.json, examples/vg-specs/box_plot.vg.json, examples/vg-specs/errorbar_aggregate.vg.json, examples/vg-specs/errorbar_horizontal_aggregate.vg.json, examples/vg-specs/layer_bar_line.vg.json, examples/vg-specs/layer_bar_line_union.vg.json, examples/vg-specs/layer_histogram.vg.json, examples/vg-specs/layer_line_color_rule.vg.json, examples/vg-specs/layer_overlay.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/overlay_area_full.vg.json, examples/vg-specs/overlay_area_short.vg.json, examples/vg-specs/overlay_line_full.vg.json, examples/vg-specs/overlay_line_short.vg.json, examples/vg-specs/scatter_connected.vg.json, src/compile/layer.ts, src/compile/mark/mixins.ts, src/compile/model.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/scales.ts, src/compile/selection/transforms/transforms.ts, src/compile/unit.ts, test/compile/selection/layers.test.ts
Fixes #2146. The following spec demonstrates selections defined in both layers and used across them. 
```json
{
"description": "Drag out a rectangular brush to highlight points.",
"layer": [{
"selection": {
"grid": {
"type": "interval", "bind": "scales",
"translate": "[mousedown[!event.shiftKey], mouseup] > mousemove"
}
},
"encoding": {
"x": {"field": "Horsepower", "type": "quantitative"},
"y": {"field": "Miles_per_Gallon", "type": "quantitative"},
"color": {
"condition": {"selection": "brush", "value": "grey"},
"field": "Cylinders", "type": "ordinal"
},
"size": {"value": 100}
}
}, {
"mark": "square",
"selection": {
"brush": {
"type": "interval",
"on": …
```
=> Support selections with layered specs

build/vega-lite-schema.json, examples/specs/faceted_selections.vl.json, examples/vg-specs/brush.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/panzoom_scatter.vg.json, src/compile/facet.ts, src/compile/selection/interval.ts, src/compile/selection/multi.ts, src/compile/selection/selection.ts, src/compile/selection/single.ts, src/compile/selection/transforms/inputs.ts, src/compile/selection/transforms/scales.ts, src/compile/selection/transforms/toggle.ts, src/compile/unit.ts, src/selection.ts, src/spec.ts, test/compile/selection/interval.test.ts, test/compile/selection/layers.test.ts
Follows #2160. Here's a test spec:
```json
{
"description": "Anscombe's Quartet",
"data": {"url": "data/anscombe.json"},
"mark": "circle",
"selection": {
"brush": {
"type": "interval", "resolve": "global",
"encodings": ["x"]
}
},
"encoding": {
"column": {"field": "Series","type": "nominal"},
"x": {
"field": "X",
"type": "quantitative",
"scale": {"zero": false}
},
"y": {
"field": "Y",
"type": "quantitative",
"scale": {"zero": false}
},
"size": {
"value": 100,
"condition": {"selection": "brush","value": 250}
}
},
"config": {"mark": {"opacity": 1}}
}
```
Things to vary:
* Resolution scheme: `global`, `independent`, `union`, `union_others`, `intersect`, `intersect_others`.
* Binding should only work with `global` resolutions.
=> Support selections with faceted specs

test/compile/facet.test.ts, test/compile/layer.test.ts, test/compile/unit.test.ts
(These are old tests from testing `isLayer`, `isFacet`, and `isUnit`.)
=> No need to test `instanceof`.

build/vega-lite-schema.json, package.json, scripts/check-schema.sh
Replaced `UnitSpec<Encoding, …>`   => `UnitSpec` and `UnitSpec<EncodingWithFacet, …>`  => `FacetedUnitSpec`
Got rid of <Field>
=> Fix schema

src/channel.ts
This makes `"nominal"` the default `type` for `text` and `tooltip`
Fix #2335
=> Correct rangeType for text, tooltip and x2/y2.

site/docs/mark.md
The anchor links in the mark docs don't work because they all have the `-mark` suffix at the moment.
Thank you for this awesome project! I'm enjoying working with it a lot!
=> Fix anchor links in mark documentation

src/compile/mark/init.ts, src/compile/scale/init.ts, src/compile/scale/type.ts, src/fielddef.ts, src/timeunit.ts, test/compile/scale/init.test.ts, test/compile/scale/type.test.ts, test/fielddef.test.ts
After the discussion with @kanitw, we agree on:
read input data as utc behavior should remain mostly the same as https://github.com/vega/vega-lite/pull/2345 Only difference is for input time data in ISO format, we will parse the data in utc.
To have user output in utc, we need to let user specify either one of:
1) utc timeunit when you have input data in local time, or 
2) utc scale type when you have input data in utc time
to have the correct output in utc time. But not **both** of utc timeunit and utc scale type since that will cause a trouble by shifting the output twice in vega.
Fix #2048 
The reason for why the #2048 output is wrong is that the input data is in ISO format and we will parse it in utc time automatically. So we need to be consistent to have data output in utc or in …
=> Bring back the code to let utc timeunit and utc scale not be consistent

build/vega-lite-schema.json, site/docs/axis.md, site/docs/legend.md, src/vega.schema.ts
Fix #2342
Add `labelPadding`, `tickExtra`, `titleAlign`, `titleAngle` to Axis Properties
Add `bandPosition`, `titleX`, `titleY` to Axis Config
Add `fillColor`, `titleAlign`,   to Legend Properties
Add `cornerRadius`, `strokeColor`, `strokeDash`, `strokeWidth`, `titleBaseline`, `gradientLabelBaseline`, `gradientLabelLimit`, `gradientLabelOffset` to Legend Config
=> add missing axis/legend config

build/vega-lite-schema.json, scripts/rename-schema.sh, src/compile/mark/init.ts, src/compositemark/boxplot.ts, src/compositemark/index.ts, src/mark.ts, src/spec.ts, test/compositemark.test.ts
Allow the use of aggregate and or orient to determine box plot orientation.
Refers to issue: #2303 
This is the updated version of the boxplot pr in a new branch and pr because of weird merging in the #2313 pr.
=> Boxplot Orient

package.json, src/compile/selection/interval.ts, test/compile/selection/interval.test.ts, test/compile/selection/layers.test.ts, yarn.lock
None of the examples that used a brush worked in the example gallery because we passed the generated Vega spec with undefined properties directly to Vega. It caused issues like
This PR fixes that.
=> Don't output undefined properties to fix brush

src/compile/layer.ts, src/compile/selection/selection.ts
`LayerModel`'s children can be `LayerModel` as well (not just `UnitModel`).
By correcting the type, I notice that `assembleLayerSelectionMarks` previously didn't handle when LayerModel's child is not a UnitModel.  
@arvind could you please verify if my change below is right. If not, please correct it.
=> Correct types for layer's `children`

examples/specs/interactive_splom.vl.json, examples/vg-specs/brush.vg.json, examples/vg-specs/concat_selections.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/interactive_splom.vg.json, examples/vg-specs/layered_crossfilter.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/overview_detail.vg.json, examples/vg-specs/panzoom_scatter.vg.json, src/compile/selection/interval.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/scales.ts, src/compile/selection/transforms/translate.ts, src/compile/selection/transforms/zoom.ts, src/vega.schema.ts, test/compile/selection/interval.test.ts, test/compile/selection/layers.test.ts, test/compile/selection/translate.test.ts, test/compile/selection/zoom.test.ts
~~Please merge after #2376.~~  Done
This PR should address the issues with interval selections identified in ~~#2148~~, ~~#2284~~, ~~#2288~~, and ~~#2315~~ (once vega/vega-parser#32 is merged). Interval selections now generate separate signals in pixel and data space. 
One todo remains before this PR can be reviewed: unbound intervals (i.e., brushes) do not yet update when bound intervals (i.e., panning & zooming) are modified. This results in the behaviour shown here whereby points do not recolour when panning/zooming the grid:
=> Break apart pixel and data signals for interval selections

examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/paintbrush.vg.json, examples/vg-specs/query_widgets.vg.json, src/compile/selection/multi.ts, src/compile/selection/single.ts, src/compile/selection/transforms/project.ts, test/compile/selection/multi.test.ts, test/compile/selection/single.test.ts
Please merge after #2441. 
This PR includes two fixes when using selections across multiview displays:
* For binned fields, point selections store the bin extents which is tested by the corresponding predicate function (vega/vega-parser#35). Fixes #2320.
* For timeUnit fields, the selection is constructed using the derived (not raw field). This assumes we're able to resolve #2448 accordingly.
=> Fixes for selections over binned/timeUnit fields

examples/vg-specs/layered_crossfilter.vg.json, src/compile/selection/interval.ts
=> Only add a scale listener if appropriate, rather than producing an empty array

examples/vg-specs/line_quarter_legend.vg.json, src/compile/scale/type.ts, test/compile/scale/type.test.ts
=> Use ordinal scale for discrete timeUnit

examples/specs/query_widgets.vl.json, examples/vg-specs/query_widgets.vg.json
The odd color scale/legend behaviour is being tracked in vega/vega-scale#4.
=> Layer query_widgets example to better highlight occluded points.

build/vega-lite-schema.json, examples/specs/brush.vl.json, examples/specs/interactive_splom.vl.json, examples/specs/layered_selections.vl.json, examples/specs/query_widgets.vl.json, examples/vg-specs/brush.vg.json, examples/vg-specs/interactive_splom.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/query_widgets.vg.json, scripts/rename-schema.sh, src/compile/mark/mixins.ts, src/compile/selection/selection.ts, src/fielddef.ts, src/filter.ts, src/logical.ts, src/util.ts, test/compile/selection/predicate.test.ts
This PR resolves #2322 by allowing structured logical composition of selections in both the `condition` and selection `filter`. A general purpose `logicalComposition` utility (and associated type definitions) has been introduced for future use with the filter transform as well.
=> Support structured logical composition of selections

build/vega-lite-schema.json, examples/vg-specs/overview_detail.vg.json, src/compile/scale/assemble.ts, src/compile/scale/parse.ts, src/compile/selection/interval.ts, src/compile/selection/multi.ts, src/compile/selection/selection.ts, src/compile/selection/single.ts, src/scale.ts, src/selection.ts, src/vega.schema.ts, test/compile/scale/parse.test.ts, test/compile/selection/scales.test.ts
In 77ff32c, we introduced a hack to allow scale domains to be parameterized by selections. The motivation for the hack still persists: scales are parsed before selections, but we need selections to be parsed in order to find their component in the model tree. 
However, rather than polluting our type/interface definitions, this PR resolves #2470 by piggybacking off `scale.domainRaw` using a special key (`SELECTION_DOMAIN`). If this key is found during scale assembly, it is replaced with the correct expression function. 
(The circular dependency issue we experienced in 77ff32c seems to have resolved itself, phew!). 
Because this is still somewhat hacky, I've also added tests to ensure that the correct things are happening at both scale parsing and assembly.
=> Cleaner approach for SelectionDomain

build/vega-lite-schema.json, scripts/rename-schema.sh, src/compile/data/transforms.ts, src/filter.ts, src/transform.ts, test/filter.test.ts
#2471 introduced structured composition of logical operators but only applied it to composition of selection predicates. This PR extends it to support all `Filter` operators. 
~Note: the previously requested changes to parenthesis (11fa46e) were buggy. This PR fixes this bug as well -- parentheses should wrap the base operand as well as group operands that are and'd/or'd together.~
=> Support structured composition of Filters

build/vega-lite-schema.json, scripts/rename-schema.sh, site/docs/axis.md, src/axis.ts, src/compile/axis/parse.ts, src/compile/legend/parse.ts, src/guide.ts, src/legend.ts, src/vega.schema.ts
Part of #1874 
~~This doesn't work yet as the json schema generator doesn't support [Mapped Types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html) for the following lines yet:~~
```
+export type AxisEncoding = {
+  [k in keyof VgAxisEncode]?: GuideEncodingEntry;
+};
```
=> Define axis/legend.encoding for using Vega's axis/legend.encode

examples/vg-specs/brush.vg.json, examples/vg-specs/concat_selections.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/interactive_splom.vg.json, examples/vg-specs/layered_crossfilter.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/overview_detail.vg.json, package.json, src/compile/selection/interval.ts, test/compile/selection/interval.test.ts, yarn.lock
As described in #2493, the switch to a linear scale in #2492 revealed an infinite loop when interval selections filter datasets that back scales in its view (e.g., cross filtering). The specific flow is interaction events fire `modify` calls to the selection's backing store. These updates trigger reevaluations of the selection predicate applied to the source/raw dataset. This in turn marks scale functions as modified, which would loop back to keep brushes in sync with scale changes. 
This PR instead proxies the final part of that cycle. Instead of having the brush signals react directly to scale changes, a new `scale_trigger` signal is introduced. This new signal reacts to scale changes and determines if the brush coordinates should change. If they should, propagation continues and the …
=> Proxy scale reactions to prevent infinite loop w/interval selection filters

package.json, site/static/main.ts, site/static/streaming.ts, site/tsconfig.json, site/tutorials/getting_started.md, site/tutorials/streaming.md, site/usage/compile.md, site/usage/embed.md
Updated some pages of the site to use new Vega-Embed. 
My major concern of this PR is about `streaming.ts`. I changed the code of it under an assumption that we're going to use Vega-Embed with the promise feature which is not released yet. When testing, I linked Vega-Embed to the current master branch of Vega-Embed.
=> Updated Vega-Embed on the site

examples/vg-specs/brush.vg.json, examples/vg-specs/concat_selections.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/interactive_splom.vg.json, examples/vg-specs/layered_crossfilter.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/overview_detail.vg.json, src/compile/selection/interval.ts, test/compile/selection/interval.test.ts
This prevents a glitch observed when brushing and panning within the same unit view. If triggers are registered as listeners to multiple scales, the brush will appear to "drift" as one scale registers and
fires an update before the other.
=> Triggers should register as scale dependencies not listeners.

build/vega-lite-schema.json, examples/vg-specs/bar_grouped.vg.json, examples/vg-specs/bar_grouped_horizontal.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/line_quarter.vg.json, examples/vg-specs/trellis_anscombe.vg.json, examples/vg-specs/trellis_bar.vg.json, examples/vg-specs/trellis_bar_histogram.vg.json, examples/vg-specs/trellis_barley.vg.json, examples/vg-specs/trellis_column_year.vg.json, examples/vg-specs/trellis_row_column.vg.json, examples/vg-specs/trellis_scatter.vg.json, examples/vg-specs/trellis_scatter_binned_row.vg.json, examples/vg-specs/trellis_stacked_bar.vg.json, scripts/generate-images.sh, src/compile/facet.ts, src/compile/layout/header.ts, src/facet.ts, test/compile/facet.test.ts
Fix #2553 
(As a future work, I think we should allow user to sort facet as they want.)
=> Sort facet values in ascending order as default

site/usage/applications.md
Include links to both the site, and the markdown documentation.
=> Add data.world as a tool in site

site/usage/applications.md
Just realized that the link to [mondrian-rest-ui](https://github.com/jazzido/mondrian-rest-ui), an application that I maintain, is wrong.
This PR corrects it.
Thanks!
=> Fix link to mondrian-rest-ui

build/vega-lite-schema.json, src/compile/selection/interval.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/nearest.ts, src/compile/selection/transforms/toggle.ts, src/compile/selection/transforms/translate.ts, src/compile/selection/transforms/zoom.ts, src/selection.ts, test/compile/selection/inputs.test.ts, test/compile/selection/interval.test.ts, test/compile/selection/nearest.test.ts, test/compile/selection/toggle.test.ts, test/compile/selection/translate.test.ts, test/compile/selection/zoom.test.ts
This PR introduces a `mark` property that can be defined on interval selections (and interval selection configs) to customize the appearance of the generated brush mark. The supported style properties include `fill`, `fillOpacity`, `stroke`, `strokeWidth`, `strokeOpacity`, `strokeDash`, and `strokeDashOffset`.
(I also made the type definitions more precise, which should help make Altair's selection API cleaner).
E.g., 
```json
{
"description": "Drag out a rectangular brush to highlight points.",
"selection": {
"brush": {
"type": "interval",
"mark": {
"fill": "red",
"fillOpacity": 0.75,
"stroke": "green",
"strokeWidth": 4,
"strokeDash": [10, 5],
"strokeDashOffset": 3,
"strokeOpacity": 1
}
}
}, …
```
=> Customize brush style using "mark" property

examples/specs/bubble_health_income.vl.json, examples/vg-specs/brush.vg.json, examples/vg-specs/bubble_health_income.vg.json, examples/vg-specs/concat_selections.vg.json, examples/vg-specs/faceted_selections.vg.json, examples/vg-specs/interactive_splom.vg.json, examples/vg-specs/layered_crossfilter.vg.json, examples/vg-specs/layered_selections.vg.json, examples/vg-specs/overview_detail.vg.json, examples/vg-specs/panzoom_scatter.vg.json, src/compile/axis/parse.ts, src/compile/axis/rules.ts, src/compile/selection/transforms/translate.ts, src/compile/selection/transforms/zoom.ts, test/compile/selection/translate.test.ts, test/compile/selection/zoom.test.ts
This PR updates the translate and zoom selection transforms to use corresponding expression functions (rather than embed the necessary calculation within the signal update function). We added these functions in vega/vega-parser@4d82d86 to support smoother panning/zooming of log and pow scales. Consequently, I've also added pan/zooming to the gapminder example!
=> Use pan/zoom expression functions

examples/specs/dashboard_europe_pop.vl.json, examples/vg-specs/dashboard_europe_pop.vg.json, src/compile/selection/interval.ts
#2589 coerced interval extents to numbers to support time scales. However, this [breaks with `band`](https://github.com/vega/vega-lite/issues/2635#issuecomment-313534244) (and presumably other discrete scale types). Thus, this PR only coerces for continuous scale types.
=> Fix scale trigger coercion to only occur for continuous scales.

examples/specs/timeunit_selections.vl.json, examples/vg-specs/timeunit_selections.vg.json, src/compile/data/assemble.ts, src/compile/data/bin.ts, src/compile/data/optimizers.ts, src/compile/data/timeunit.ts, src/compile/data/transforms.ts, src/compile/model.ts, src/compile/selection/interval.ts, src/compile/selection/multi.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/inputs.ts, src/compile/selection/transforms/project.ts, src/compile/selection/transforms/scales.ts, src/filter.ts, test/compile/data/bin.test.ts, test/compile/data/timeunit.test.ts, test/compile/selection/parse.test.ts, test/compile/selection/timeunit.test.ts
If a selection is projected over a time unit field, this PR adds necessary time unit calculations to the dataflows of secondary views that apply the selection.
Two example specs:
1. When applied as a `condition`:
```json
{
"description": "Google's stock price over time.",
"data": {
"values": [
{"date": "Sun, 01 Jan 2012 23:00:01","price": 150},
{"date": "Sun, 02 Jan 2012 00:10:02","price": 100},
{"date": "Sun, 02 Jan 2012 01:20:03","price": 170},
{"date": "Sun, 02 Jan 2012 02:30:04","price": 165},
{"date": "Sun, 02 Jan 2012 03:40:05","price": 200}
]
},
"hconcat": [{
"selection": {
"brush": {"type": "interval", "encodings": ["x"]}
},
"encoding": {
"x": {
"field": "date",
"type": "temporal",
"timeUnit": "seconds" …
```
=> Time unit selections add necessary dataflow nodes

src/compile/selection/interval.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/nearest.ts, src/compile/selection/transforms/translate.ts, src/compile/selection/transforms/zoom.ts, test/compile/selection/nearest.test.ts
This PR ensures that if a selection is projected over the x or y channels, the voronoi is appropriately aligned (see vega/vega#799). For all other projections, the voronoi continues to be computed in both dimensions. Resolves #2657.
=> Nearest/voronoi should align with spatial projections.

src/filter.ts, test/filter.test.ts
(From `inrange(datum, min, max)` to `inrange(datum, [min, max])`. )
Fix #2648
cc: @willium
=> Update inrange Vega Expression to match the new version

src/compile/facet.ts, test/compile/facet.test.ts
- Do not call assemble inside parse
- Do not need to weirdly combine markGroup that is partially generated in parseMark
=> Refactor facet

site/docs/spec.md
Fixed typo in documentation. "diverge" should be "diverse".
=> Fixed typo

src/spec.ts
Fixed to use the right config in normalize() in spec. Refers to issue #2655
=> Fix Boxplot Config Bug

examples/vg-specs/paintbrush.vg.json, examples/vg-specs/paintbrush_color.vg.json, examples/vg-specs/paintbrush_color_nearest.vg.json, examples/vg-specs/paintbrush_simple.vg.json, examples/vg-specs/rect_binned_heatmap.vg.json, examples/vg-specs/selection_insert.vg.json, examples/vg-specs/selection_project_multi.vg.json, examples/vg-specs/selection_project_single.vg.json, examples/vg-specs/selection_toggle_altKey.vg.json, examples/vg-specs/selection_toggle_altKey_shiftKey.vg.json, examples/vg-specs/selection_toggle_shiftKey.vg.json, examples/vg-specs/selection_type_multi.vg.json, examples/vg-specs/selection_type_single.vg.json, examples/vg-specs/selection_type_single_dblclick.vg.json, src/compile/data/assemble.ts, src/compile/data/parse.ts, src/compile/data/transforms.ts, src/compile/selection/selection.ts, src/selection.ts, src/vega.schema.ts, test/compile/selection/identifier.test.ts, test/compile/selection/inputs.test.ts, test/compile/selection/multi.test.ts, test/compile/selection/parse.test.ts, test/compile/selection/single.test.ts
This PR replaces #2636, adding the identifier transform via the dataflow architecture instead. 
#2636 describes our desired outcome: an identifier node added every time new tuples are derived -- i.e., at the source and after an aggregate transform (and if the two happen within the same dataset, only one identifier transform is added to reduce unnecessary computation).
Here's a simple unit spec to start testing with:
```json
{
"description": "Select multiple points with the shift key.",
"selection": {
"paintbrush": {
"type": "single"
}
},
"encoding": {
"x": {"field": "Horsepower", "type": "quantitative"},
"y": {"field": "Miles_per_Gallon", "type": "quantitative"},
"size": { …
```
=> Add identifier transform for default point selections.

src/compositemark/boxplot.ts
It's not important but I run into it and it's just one line
We could add more sophisticated support in the future, but this would at least make it more correct.
=> Basic box plot selection support -- part of #2235

src/compile/baseconcat.ts, src/compile/common.ts, src/compile/concat.ts, src/compile/data/bin.ts, src/compile/data/formatparse.ts, src/compile/data/parse.ts, src/compile/facet.ts, src/compile/layer.ts, src/compile/layout/assemble.ts, src/compile/mark/mark.ts, src/compile/model.ts, src/compile/repeat.ts, src/compile/repeater.ts, src/compile/resolve.ts, src/compile/scale/domain.ts, src/compile/scale/parse.ts, src/compile/scale/properties.ts, src/compile/scale/range.ts, src/compile/selection/selection.ts, src/compile/unit.ts, test/compile/repeat.test.ts
Note: We use type guards instead of `instanceof` as `instanceof` makes
different parts of the compiler depend on the actual implementation of
the model classes, which in turn depend on different parts of the compiler.
Thus, `instanceof` leads to circular dependency problems.
On the other hand, type guards only make different parts of the compiler
depend on the type of the model classes, but not the actual implementation.
=> Make BaseConcat to reduce redundant code + Fix Circular Dependencies

site/usage/applications.md
Adding Visdown.com as one tool to explore tools. It also has starter learning documentation on how to start playing around with vega-lite: data layer, visual layer, annotation layer, interaction layer and composition. Thank you for creating this library!
=> Added Visdown.com in Tools

build/vega-lite-schema.json, src/compile/common.ts, src/compile/layer.ts, src/compile/model.ts, src/config.ts, src/title.ts, src/vega.schema.ts, test/compile/compile.test.ts, test/config.test.ts
We need to do this so that title config do not affect header labels, which also uses title to implement.
Part of #2763
=> Redirect title config to `guide-title` and hard-code non-mark config to title.

_layouts/home.html, site/index.md
I think that better differentiates Vega-Lite v2 from v1 (and other high-level visualization grammars, e.g., ggplot2).
=> Use "Grammar of Interactive Graphics" branding.

scripts/deploy.sh
I think we should swap them because deploy github is more problematic so we better run it at the end and if it fails, we only need to re-run one thing.
=> Swap deploy schema and deploy github

site/docs/area.md
Defining `stack` is now within encoding channel in v2 vs `config.mark.stack` in v1. Edits in documentation to reflect that.
=> Updated documentation on stack

build/vega-lite-schema.json, site/docs/config.md, src/config.ts
(We still hides `title` because `title` is not well supported for plots with `layout` operator.  See https://github.com/vega/vega/issues/960.)
=> Hide title config as we still hide `title`

src/compile/baseconcat.ts, src/compile/facet.ts, src/compile/layer.ts, src/compile/model.ts, src/compile/scale/assemble.ts, src/compile/unit.ts, test/compile/concat.test.ts, test/compile/facet.test.ts, test/compile/layer.test.ts, test/compile/repeat.test.ts, test/compile/scale/assemble.test.ts
so we have less methods in models + have all assembleScale tests in one place
(We couldn't do this earlier due to circular dependencies problem.)
=> Get rid of `model.assembleScales()`

src/compile/model.ts, src/fielddef.ts, src/filter.ts, src/log.ts, src/logical.ts, src/timeunit.ts, src/transform.ts, test/fielddef.test.ts, test/timeunit.test.ts, test/transform.test.ts
(The old replacement logic is only in expression and thus generate incorrect timeFormat.)
=> Replace the invalid timeUnits with "...day" with "….date"

site/static/main.css
Fix https://github.com/vega/vega-lite/issues/2890
(Let's agree on always adding "# Documentation Overview" so we don't have floating TOC)
=> Hide first item of TOC as it will always be Documentation Overview

src/compile/scale/type.ts
Fix https://github.com/vega/vega-lite/issues/2905
=> Don't throw error when we use linear with binned x/y

src/compile/data/aggregate.ts, src/compile/data/bin.ts, src/compile/data/parse.ts, src/compile/data/timeunit.ts, src/filter.ts, test/compile/data/aggregate.test.ts, test/compile/data/bin.test.ts, test/compile/data/timeunit.test.ts
This PR should makes factory methods for the transform nodes that you need re-usable for you.
As mentioned in the email, to we convert a Vega-Lite `transform` array to a Vega `transform` array,
for each transforms, you can convert a Vega-Lite transform to Vega transform(s).
1) Use a factory method to create a node
2) call node.assemble(), which will output relevant Vega transforms
=> Make transform nodes re-useable for external modules

src/scale.ts, test/scale.test.ts
(row/column do not have scales.)
=> Remove ROW/COLUMN from `channelSupportScaleType`

site/tutorials/getting_started.md
Technically, a vega-lite specification works without out the `$schema` property. While this may not be recommended for many (albeit unmentioned) reasons, starting with `schema` in this context just breaks the flow.
As a side node: the `vega` tutorials do not mention `$schema` explicitly either.
=> remove `# $schema` from `getting_started`

site/docs/area.md, site/docs/axis.md, site/docs/bar.md, site/docs/data.md, site/docs/facet.md, site/docs/line.md, site/docs/point.md, site/docs/scale.md, site/docs/selection.md, site/docs/size.md, site/docs/spec.md, site/docs/stack.md, site/docs/tooltip.md, site/static/main.css
See https://kramdown.gettalong.org/converter/html.html#toc
This has two advantages. First, it makes it more explicit what is shown. Second, we don't even output the HTML.
=> Don’t hide toc entries via css but instead use {:.no_toc}

src/filter.ts, test/filter.test.ts
Also make upper/lower only cases correct with timeUnit
=> Allow `fieldFilterExpression` to use equality sign only (for Voyager)

build/vega-lite-schema.json, site/docs/selection/selection.md, src/selection.ts
Make selection docs have explicit section for general selection properties / subsections for single/multi/interval selections.  
I haven't fixed all the links / make glues for all sections, but just wanna propose an idea that you can take over.  
After cleaning up, this should resolve my comments in https://github.com/vega/vega-lite/pull/2968.
If you like it, please feel free to take over this.
=> Possible alternative structure for selection docs

_data/link.yml, build/vega-lite-schema.json, examples/specs/bar_grouped.vl.json, examples/specs/bar_grouped_horizontal.vl.json, examples/specs/facet_independent_scale.vl.json, examples/specs/facet_independent_scale_layer.vl.json, examples/specs/normalized/bar_grouped_horizontal_normalized.vl.json, examples/specs/normalized/bar_grouped_normalized.vl.json, examples/specs/rect_binned_heatmap.vl.json, site/docs/config.md, site/docs/spec.md, site/docs/view/size.md, src/compile/common.ts, src/compile/data/facet.ts, src/compile/facet.ts, src/compile/layoutsize/parse.ts, src/compile/mark/bar.ts, src/compile/model.ts, src/compile/scale/domain.ts, src/config.ts, src/spec.ts, test/compile/data/facet.test.ts, test/compile/layoutsize/assemble.test.ts, test/compile/layoutsize/parse.test.ts, test/compile/mark/text.test.ts, test/compile/scale/range.test.ts, test/config.test.ts
"cell" is a weird keyword that is coming from nowhere. 
Naming it "View Config" makes it fit nicely in the View Specification page. 
This is obviously a breaking change, but I strongly think we should make it right as it is the last chance.
=> Rename config.cell => config.view + Add docs.

site/docs/composition/repeat.md, site/docs/composition/resolve.md, site/docs/encoding/axis.md, site/docs/encoding/legend.md, site/docs/selection/nearest.md, src/channel.ts, src/compile/axis/encode.ts, src/compile/axis/parse.ts, src/compile/axis/properties.ts, src/compile/legend/assemble.ts, src/compile/legend/component.ts, src/compile/legend/encode.ts, src/compile/legend/parse.ts, src/compile/mark/mark.ts, src/compile/mark/mixins.ts, src/compile/resolve.ts, src/compile/selection/interval.ts, src/compile/selection/selection.ts, src/compile/selection/transforms/nearest.ts, src/compile/selection/transforms/translate.ts, src/compile/selection/transforms/zoom.ts, src/compile/unit.ts, src/compositemark/common.ts, src/encoding.ts, src/resolve.ts, src/stack.ts, test/channel.test.ts, test/compile/scale/properties.test.ts
(We use position more than spatial so let's use position.)
=> Standardize naming: Use position rather than spatial

site/usage/compile.md
=> Better wording for logger docs. We throw errors.

src/compile/axis/properties.ts
=> Make axis.labelOverlap used if specified

site/usage/applications.md
Added `marked-vega` to list of application for Vega-Lite.
`marked-vega` is a Polymer webcomponent to parse image/code markdowns into Vega or Vega-Lite charts.
=> Added marked-vega

typings/vega-util.d.ts
Removing this prevents us from accidentally using it.
=> We don’t use vega extend.

package.json, yarn.lock
See https://github.com/jupyterlab/jupyter-renderers/pull/15#issuecomment-340522499
=> Use Vega datasets from npm so it can be cached.

site/usage/applications.md
Added `gulp-marked-vega` to libraries available for Vega and Vega-Lite markdowns. 
`gulp-marked-vega` is a gulp plugin and a cli tool to replace `marked-vega` markdown syntax with base64 embedded image tags so that standard markdown parser can render the charts without any additional plugins or modification to the rendering rules.
=> Added gulp-marked-vega

build/vega-lite-schema.json, package.json, site/docs/data.md, src/compositemark/boxplot.ts, src/data.ts, yarn.lock
Needs https://github.com/vega/ts-json-schema-generator/issues/19
@jakevdp, before I merge this, can you check that this schema in this PR works for you and doesn't have unused definitions.
=> Cleaner schema

examples/compiled/bar_grouped.vg.json, examples/compiled/bar_grouped_horizontal.vg.json, examples/compiled/facet_column_facet_column_point_future.vg.json, examples/compiled/facet_column_facet_row_point_future.vg.json, examples/compiled/facet_cross_independent_scale.vg.json, examples/compiled/facet_independent_scale.vg.json, examples/compiled/facet_independent_scale_layer.vg.json, examples/compiled/facet_row_facet_row_point_future.vg.json, examples/compiled/trellis_anscombe.vg.json, examples/compiled/trellis_area.vg.json, examples/compiled/trellis_bar.vg.json, examples/compiled/trellis_bar_histogram.vg.json, examples/compiled/trellis_barley.vg.json, examples/compiled/trellis_column_year.vg.json, examples/compiled/trellis_line_quarter.vg.json, examples/compiled/trellis_row_column.vg.json, examples/compiled/trellis_scatter.vg.json, examples/compiled/trellis_scatter_binned_row.vg.json, examples/compiled/trellis_scatter_small.vg.json, examples/compiled/trellis_selections.vg.json, examples/compiled/trellis_stacked_bar.vg.json, src/compile/layout/header.ts
Fix https://github.com/vega/vega-lite/issues/3204
=> Fix bug that prevent users from using `guide-label` style to customize header labels

site/docs/encoding/sort.md
Another typo in docs, compare with
https://github.com/vega/vega-lite/blob/master/src/sort.ts#L4
=> Fix encoding/sort doc, replace "none" with "null" (as in code)

test/stack.test.ts
We don't support stacking: 'none' anymore.
=> Replace ‘none’ -> null in stacking tests.

build/vega-lite-schema.json, package.json, src/config.ts, src/fielddef.ts, src/scale.ts
Fix https://github.com/vega/vega-lite/issues/3234
=> Fix schema for `config.invalidValues`

site/usage/applications.md
Please add the Elm-Vega binding link to the list of applications in docs.
I've also corrected the broken link to the applications page as this appears to have moved from `site/applications.md` to `site/usage/applications.md`.
=> Link to Elm binding of Vega-Lite

src/compile/mark/valueref.ts, test/compile/mark/point.test.ts
For example, this spec should not get error:
```
{
"description": "Select multiple points with the shift key.",
"selection": {
"paintbrush": {
"type": "multi", "on": "mouseover",
"nearest": true
}
},
"encoding": {
"x": {"field": "Horsepower", "type": "quantitative"},
"y": {"field": "Miles_per_Gallon", "type": "quantitative"},
"size": {
"condition": {"selection": "paintbrush", "value": 300}
}
}
}
```
=> Remove an error thrown for condition-only def

src/compile/mark/init.ts, src/compile/mark/rule.ts, test/compile/mark/init.test.ts, test/compile/mark/rule.test.ts
Fix #3263
I don't think this imperfect parallel coordinate is a good example for this yet -- if you have a good idea about a good example, please feel free to submit a separate PR.
=> Fix rule mark to support arbitrary (possibly oblique) line segments

_data/link.yml, build/vega-lite-schema.json, scripts/rename-schema.sh, site/docs/transform/filter.md, src/compile/data/filter.ts, src/compile/data/formatparse.ts, src/compile/data/parse.ts, src/compile/mark/mixins.ts, src/compile/selection/selection.ts, src/predicate.ts, src/transform.ts, test/compile/selection/predicate.test.ts, test/predicate.test.ts, test/transform.test.ts
(FieldPredicate can be useful in other scenario besides filter -- e.g., for condition in https://github.com/vega/vega-lite/pull/3239 or for selecting data for annotation (@starry97's project)
cc: @starry97
=> Refactor: Distinguish between FieldPredicate and SelectionFilter

src/compile/data/index.ts, src/compile/data/optimize.ts, src/compile/data/optimizers.ts, src/compile/model.ts, src/compile/scale/domain.ts, src/compile/split.ts, src/spec.ts, test/compile/data/assemble.test.ts, test/compile/scale/parse.test.ts
=> Domain fix

site/docs/transform/transform.md
The View spec.mp differentiates between "Common Properties of Specifications" and "Top-Level Specifications".
The documentation for transform.md was updated to follow this differentiation.
=> Clarify top-level vs view-level in transform.md

site/docs/compositemark.md
Made change to the filename that was wrong in all the examples. Refers to #3150.
=> Fixed Missing Boxplot Examples

src/compile/projection/assemble.ts
[`util.error` is the deprecated predecessor to `console.error`](https://nodejs.org/api/util.html#util_util_error_strings).
As suggested in this PR, this uses `vega-util`'s error, which _will_ throw rather than erroring in the console.
Can this also get backported to the 1.x line?
=> use vega-util's error instead of util.error

src/toplevelprops.ts
`util.isString` [is deprecated](https://nodejs.org/api/util.html#util_util_isstring_object) and `vega-util` provides `isString` as well.
I'd like to get rid of all usage of node's `util` in this project (also see #3394), to make it simpler to work with webpack and conflicting definitions of browser side `util` versions. Unfun story at the moment.
I'd also love to see this change as part of the 1.x line.
=> switch from node's util to vega-util for isString

src/compile/projection/assemble.ts
**Maintain consistency for throwing error**
- All vega-util `error()` are replaced with standard `throw new Error()`.
Fixes #3406.
=> Maintain consistency for throwing error

examples/compiled/box-plot_minmax_1D_horizontal.vg.json, examples/compiled/box-plot_minmax_1D_vertical.vg.json, examples/compiled/box-plot_minmax_2D_horizontal_explicit_aggregate.vg.json, examples/compiled/box-plot_minmax_2D_vertical.vg.json, examples/compiled/layer_box-plot_circle.vg.json, src/compositemark/boxplot.ts, src/config.ts, test/compositemark/boxplot.test.ts
Refers to #3242.
Changes:
- Added to config property box a property called extent to make the default extent value to be 1.5
- Added test for boxplot mark type for tukey box plot
=> Default Boxplot to Tukey boxplot

src/compositemark/boxplot.ts
Use `isNumber` from `vega-util` instead of util`.
Fixes #3445
=> Fix Boxplot usage of deprecated isNumber

site/docs/encoding.md, src/compile/projection/parse.ts, src/compile/selection/multi.ts, src/compile/unit.ts, test/compile/mark/rect.test.ts
**Typos/Misspells Fixes**
- This PR fixes few typos/misspells which are found using [misspell](https://github.com/client9/misspell).
=> Typos/Misspells Fixes

src/encoding.ts, src/log.ts, test/compile/unit.test.ts
=> Add Invalid Encoding Channel Warning

CONTRIBUTING.md
**Link update: Testing with editor**
- This PR updates the old vega-editor's link with the new editor one in `CONTRIBUTING.md`.
=> Link update: Testing with editor

build/vega-lite-schema.json, site/docs/data.md, src/compile/compile.ts, src/compile/data/assemble.ts, src/data.ts, src/toplevelprops.ts, test/compile/data/assemble.test.ts, test/compile/selection/identifier.test.ts, test/compile/selection/timeunit.test.ts
Fixes #3268
```json
{
"description": "A simple bar chart with embedded data.",
"data": {
"name": "my_data"
},
"mark": "bar",
"encoding": {
"x": {"field": "a", "type": "ordinal"},
"y": {"field": "b", "type": "quantitative"}
},
"datasets": {
"my_data":  [
{"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
{"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
{"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
]
}
}
```
I am pretty sure that we only need to replace datasets at the top level and not inside facets. Named datasets will always be at the top level. 
cc @ellisonbg
=> Top level datastore

build/vega-lite-schema.json, src/compile/mark/mark.ts, src/encoding.ts, test/compile/mark/mark.test.ts
=> Support `sort` for non-path marks + consolidate redundant code

build/vega-lite-schema.json, examples/compiled/boxplot_minmax_1D_horizontal.vg.json, examples/compiled/boxplot_minmax_1D_vertical.vg.json, examples/compiled/boxplot_minmax_2D_horizontal.vg.json, examples/compiled/boxplot_minmax_2D_horizontal_IQR.vg.json, examples/compiled/boxplot_minmax_2D_horizontal_color_size.vg.json, examples/compiled/boxplot_minmax_2D_horizontal_custom_midtick_color.vg.json, examples/compiled/boxplot_minmax_2D_horizontal_explicit_aggregate.vg.json, examples/compiled/boxplot_minmax_2D_vertical.vg.json, examples/compiled/boxplot_tukey_2D_vertical.vg.json, examples/compiled/layer_boxplot_circle.vg.json, examples/specs/boxplot_minmax_2D_horizontal_custom_midtick_color.vl.json, examples/specs/normalized/boxplot_minmax_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_IQR_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_explicit_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_tukey_2D_vertical_normalized.vl.json, examples/specs/normalized/layer_boxplot_circle_normalized.vl.json, site/docs/compositemark.md, src/compositemark/boxplot.ts, src/config.ts, test/compositemark/boxplot.test.ts, test/config.test.ts
"Mid" can't be a noun but "center" can so I like center better.  
~~We should merge https://github.com/vega/vega-lite/pull/3454 first.~~
=> Rename  Boxplot's `mid` to `median`

examples/examples.test.ts, package.json, src/compile/buildmodel.ts, src/compile/compile.ts, src/spec.ts, test-runtime/util.ts, test/spec.test.ts, test/util.ts
cc: @jakevdp  
The name `TopLevelExtendedSpec` is a bit too much, so we're simplifying it.
=> Rename `Spec` => `NormalizedSpec`, `TopLevelExtendedSpec` => `TopLevelSpec`

site/docs/mark/area.md, site/docs/mark/bar.md, site/docs/mark/circle.md, site/docs/mark/line.md, site/docs/mark/mark.md, site/docs/mark/point.md, site/docs/mark/rect.md, site/docs/mark/rule.md, site/docs/mark/square.md, site/docs/mark/text.md, site/docs/mark/tick.md
- List all mark-specific properties (and config) in their corresponding pages.
Fix #3487
=> Restructure mark documentation

site/docs/encoding/scale.md
I believe that there is a typo in the documentation.
Based on the defaults listed in the [vega-parser](https://github.com/vega/vega-parser/blob/master/src/config.js#L188) it looks like categorical scales use the `tableau10 ` color scheme by default. 
```
// defaults for scale ranges
range: {
category: {
scheme: 'tableau10'
},
```
=> DOC: Change default nominal scheme reference

examples/compiled/window_mean_difference.vg.json, examples/compiled/window_mean_difference_by_year.vg.json, examples/specs/window_mean_difference.vl.json, examples/specs/window_mean_difference_by_year.vl.json
Updated to filter null in the examples `window_mean_difference` and  `window_mean_difference_by_year`
=> Fix Window Examples for Mean and Mean by Year

site/examples/index.md
* Add "community examples" link to my ObservableHQ [Tutorial](https://medium.com/enigma-engineering/exploring-new-york-city-event-permits-with-vega-lite-f83178ff9a8d) on using Enigma Public's API with Vega-Lite
=> Add Enigma Public Tutorial to Examples

src/util.ts, test/util.test.ts
The method deleteNestedProperty is used when merging legends. This method has been changed to reduce the number of times it iterated through the objects in order to remove nested elements.  Recursion is now used.  Unit tests were added before the code was changed in order to ensure the new code was equivalent.
-------------------------------------------------------------
Please:
- Please add new commit(s) when addressing comments, so we can see easily the new changeset (instead of the whole changeset).  
=> Improve deleteNestedProperty from O(n^2) to O(n+1) -- fix issue #2957

package.json
As when we run test, we're more concerned about test and should see the results are correct first.
=> `yarn test` should run test before `lint`

site/usage/applications.md
Add note of more fully featured Clojure library oz (fork of vizard) to docs, as suggested here: https://github.com/metasoarous/oz/issues/11
=> Add oz to list of libs in docs

src/spec.ts
(We will properly do that later in https://github.com/vega/vega-lite/issues/3702)
=> For mark overlays, do not apply selection to the augmented layers yet.

src/compile/scale/type.ts, src/scale.ts, src/type.ts, test/scale.test.ts
Fix #3725 
Expose method `getSupportedScaleType` that returns the valid scaleTypes given an encoding channel, FieldDef type, and optional bin parameter. Function calls generated index for pre-computed valid scale types.
=> Add Index for supported Scale Types given encoding channels

CONTRIBUTING.md
cc: @invokesus @domoritz @swojit @sirah -- make sure you know about this.
=> Add notes about building examples

_data/link.yml, build/vega-lite-schema.json, site/docs/encoding/sort.md, site/docs/transform/window.md, src/compile/scale/domain.ts, src/compile/scale/properties.ts, src/compile/unit.ts, src/fielddef.ts, src/sort.ts, src/transform.ts, test/compile/scale/domain.test.ts
Rationale: WindowSortField will be used in Stack too and this is like a more general version of SortField while the encoding one is specific to one place.  
(Note that I opt for this simpler change that we discussed earlier as SortField are used in many places and they are not exactly the same thing anyway.)
=> Rename `SortField` => `EncodingSortField`, `WindowSortField` => `SortField`

examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_explicit_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json, examples/specs/normalized/layer_boxplot_circle_normalized.vl.json, src/compositemark/boxplot.ts, test/compositemark/boxplot.test.ts
(so if the dimension is binned, the tick direction is still correct)
=> Make boxplot output tick orient consistent with the box plot

src/compile/axis/parse.ts, src/compile/common.ts, src/compile/legend/parse.ts, test/compile/axis/parse.test.ts
Fix https://github.com/vega/vega-lite/issues/3742
=> Do not ignore x2's title

build/vega-lite-schema.json, src/axis.ts, src/compile/axis/parse.ts, src/compile/axis/properties.ts, test/compile/axis/properties.test.ts
- `tickStep` will auto-generate:
- `tickCount` = `"signal": "(domain('channel')[1] - domain('channel')[0]) / tickStep + 1"`
- `values` = `"signal": "sequence(domain('channel')[0], domain('channel')[1] + 1, 2)"`
=> implement tickStep and update unit tests

build/vega-lite-schema.json, src/compile/data/parse.ts, src/compile/data/stack.ts, src/transform.ts, test/compile/data/stack.test.ts
=> Add Stack Transform

examples/specs/normalized/line_shape_overlay_normalized.vl.json, src/spec.ts, src/util.ts
Also make omit use shallow duplication.  (It's actually not used elsewhere.)
=> Drop shape from overlay line output

src/compile/data/aggregate.ts, src/compile/data/window.ts, src/compile/scale/domain.ts, src/fielddef.ts, test/compile/data/window.test.ts
`_field` was wrong as multiple fields can have the same aggregate op
=>  Fix logic for window’s default as

build/vega-lite-schema.json, src/compile/data/assemble.ts, src/compile/data/fold.ts, src/compile/data/parse.ts, src/transform.ts, src/vega.schema.ts, test/compile/data/fold.test.ts, test/compile/data/parse.test.ts
=> Add Fold Transform

site/docs/tooltip.md
Fixed a little typo in the documentation.
_examle_ -> example
=> typo on tooltip.md

build/vega-lite-schema.json, src/vega.schema.ts
Moving Cursor and VerticalAlign into export types reduces the redundant definitions in vega-lite-schema.json and knocks about 5k off of the resulting schema file.
=> Move Cursor and VerticalAlign into export types

build/vega-lite-schema.json, src/config.ts, src/mark.ts, src/vega.schema.ts
Issue #3266:
Questions:
1. Should `strokeJoin` and `strokeMiterLimit` be in the list `STROKE_CONFIG` on line 124 of mark.ts? `strokeDash` and `strokeDashOffset` are there but `strokeCap` is not.
2. I added `cornerRadius` to the view config in `config.ts`, but it looks strange when used because the axes do not curve while the inner rectangle does. Is there a way to fix this?
TODO: Update documentation
=> Add missing mark properties

site/docs/encoding.md, site/docs/mark/mark.md, src/compile/mark/init.ts, test/compile/mark/init.test.ts
Updating documentation language, need to see if href is a mark config and should be considered and if baseEncodeEntry should be considered
=> More fixes to href cursor

build/vega-lite-schema.json, examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_explicit_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json, examples/specs/normalized/layer_boxplot_circle_normalized.vl.json, src/compositemark/boxplot.ts, src/compositemark/common.ts, test/compositemark/boxplot.test.ts
Refractor the Box Plot so that it uses `makeCompositeAggregatePartFactory` to make the code shorter like in the Error Bar.
=> Refractor Box Plot

site/index.md
Rather than third party communityinviter.com as we did previously.
=> Use official Slack join link

build/vega-lite-schema.json, src/mark.ts, src/spec.ts, src/util.ts
Support complete mark defs in the line and point overlays. Also correctly
inherit all properties from the main mark def. Fixes #3927
=> Revise overlay mark defs

.vscode/settings.json
Caveat: it will introduce braces on save -- l saw that this will be [fixed in the next version of VSCode](https://github.com/Microsoft/vscode/issues/47654)
=> Use latest VSCode's organize import on save

build/vega-lite-schema.json, src/compile/data/assemble.ts, src/compile/data/impute.ts, src/compile/data/parse.ts, src/fielddef.ts, src/impute.ts, src/transform.ts, src/vega.schema.ts, test/compile/data/impute.test.ts, test/compile/data/parse.test.ts
=> Impute VL-specific features

src/compile/data/impute.ts, test/compile/data/impute.test.ts
- Always impute with `null` 
- Always add `window` with default `frame` of `[null,null]`
=> Impute with null instead of undefined

src/compile/data/impute.ts, test/compile/data/impute.test.ts
Fixes imputing with `value`s that are `falsy` like `0` or `null`
=> Fix Impute with Falsy values

site/usage/applications.md
Hi,
I've written an Extension for Visual Studio Code that enables a live preview for Vega and Vega-Lite. I've seen that you encourage a pull requests against the documentation against `applications.md` if we have something to add, so that's what I've done.
The extension is available inside Visual Studio Code or at https://marketplace.visualstudio.com/items?itemName=mdk.vega-preview
The source code is available at: https://github.com/8/vega-preview
Take care,
Martin
=> added "Vega Preview" a Visual Studio Code extension to applications.md

_includes/type.html
=> Correct doc template for array of mixed type e.g., `(null | number)[]`

_data/examples.json
Now, we are using `window` instead of `aggregate`; this example does not show a solution to the `argmin/max` issue.
=> Remove the note for argmin/max issue in CO2 example

src/compile/scale/range.ts
Tiny fix for a tiny (but very impactful) typo. This import from `util` instead of `vega-util` means that vega is able to pass tests in Node, but the UMD builds for the upcoming 3.x series are broken, because they declare a dependency on `util` for the `isArray` function.
I'm pretty close to certain that the fix is to import from vega-util, which also provides isArray, instead of util. That's what this PR does.
---
Please:
=> Use vega-util, not util, for isArray

src/compositemark/boxplot.ts, src/compositemark/errorbar.ts, test/compositemark/boxplot.test.ts, test/compositemark/errorbar.test.ts
combine transform from outer spec with transform from composite mark before return to prevent overwriting.
issue #4140
=> Fix overwritten transform in composite mark

site/docs/selection/selection.md
Documentation fix.
Current behavior:
- changing the selector from "all" to "none" does not change the example visualization
https://vega.github.io/vega-lite/docs/selection.html#conditional-encodings
- console error: `GET https://vega.github.io/vega-lite/examples/specs/paintbrush_simple_none.vl.json 404`
Expected behavior:
the spec is reloaded to point to interactive_paintbrush_simple_none.vl.json instead of interactive_paintbrush_simple_all.vl.json
It looks like the source file was renamed at some point and was not updated in the markdown. This change updates the links.
=> Fix "Conditional Encodings" example in selection documentation

src/fielddef.ts, test/fielddef.test.ts
We already show Using discrete channel "shape" to encode "ordinal" field can be misleading as it does not encode order. Ref #3208
=> Don’t warn about using ordinal with shape.

src/encoding.ts, test/encoding.test.ts
From this issue #4188 
Problem: extractTransformFromEncoding drops axis after extracting encoding.
=> Fix axis customization issue of composite mark

.travis.yml
We are now testing Node 6, 8, and 10. We only run linting, check and fix, and coverage reports on node 10 since there is no need to do this for all node versions. I also removed the slack integration.
=> Only run all tests and scripts in the latest node version

build/vega-lite-schema.json, examples/examples.test.ts, src/compile/compile.ts, src/spec.ts, src/toplevelprops.ts, test/compile/compile.test.ts
Move datasets from top level props to top level spec since it cannot be in config. Add support for user meta. Fixes #3610
=> Use meta + top level props fix

src/compile/common.ts, test/compile/common.test.ts
Fixes #4195
Drop `{"title" : null}` when merging titles
=> Drop falsy title when merge

src/compile/data/aggregate.ts
cc: @Saba9 @domoritz @arvind 
We should do #4322 to prevent this.
=> Don't import util from vega directly.  Otherwise our users can no longer use `vega-lib`.

src/compile/mark/mixins.ts
Ignoring it when markDef.fill/stroke  or encoding.fill/stroke are specified makes it very confusing. 
Part of #4326
=> Only ignore `config.color` when `config.mark.fill` or `config.mark.stroke` is specified.

examples/compiled/concat_bar_layer_circle.vg.json, examples/compiled/interactive_bar_select_highlight.vg.json, examples/compiled/interactive_concat_layer.vg.json, examples/compiled/interactive_layered_crossfilter_discrete.vg.json, examples/compiled/interactive_multi_line_tooltip.vg.json, examples/compiled/interactive_paintbrush_color.vg.json, examples/compiled/interactive_paintbrush_simple_all.vg.json, examples/compiled/interactive_paintbrush_simple_none.vg.json, examples/compiled/interactive_seattle_weather.vg.json, examples/compiled/selection_insert.vg.json, examples/compiled/selection_project_multi.vg.json, examples/compiled/selection_project_multi_cylinders.vg.json, examples/compiled/selection_project_multi_cylinders_origin.vg.json, examples/compiled/selection_project_multi_origin.vg.json, examples/compiled/selection_project_single.vg.json, examples/compiled/selection_project_single_cylinders.vg.json, examples/compiled/selection_project_single_cylinders_origin.vg.json, examples/compiled/selection_project_single_origin.vg.json, examples/compiled/selection_toggle_altKey.vg.json, examples/compiled/selection_toggle_altKey_shiftKey.vg.json, examples/compiled/selection_toggle_shiftKey.vg.json, examples/compiled/selection_type_multi.vg.json, examples/compiled/selection_type_single.vg.json, examples/compiled/selection_type_single_dblclick.vg.json, examples/compiled/vconcat_flatten.vg.json, src/compile/selection/multi.ts, test/compile/selection/multi.test.ts, test/compile/selection/single.test.ts
Even if the current selection does not have the "nearest" transformation, a sibling selection in the same unit (or a sibling unit within the same layer) might. Fixes #4298 and #4271.
=> Discrete selections should always test for voronoi marks.

build/vega-lite-schema.json, src/fielddef.ts
Note: I still keep bin property for lat long, but make it support `null` only for simplicity of the codebase
=> Make `type` optional for LatLongFieldDef 

src/channel.ts, src/compile/legend/parse.ts, src/compile/unit.ts, test/compile/legend/parse.test.ts
Also refactor `getLegendDefWithScale`
Temporary solution for https://github.com/vega/vega/issues/1513
cc: @marcprux
=> Disable legend for `fill/strokeOpacity` and `strokeWidth`

_data/link.yml, build/vega-lite-schema.json, site/docs/composition/layer.md, site/docs/spec.md, src/compile/baseconcat.ts, src/compile/compile.ts, src/compile/facet.ts, src/compile/layer.ts, src/compile/model.ts, src/compile/unit.ts, src/config.ts, src/spec/base.ts, src/spec/layer.ts, src/spec/toplevel.ts, src/spec/unit.ts
Fix https://github.com/vega/vega-lite/issues/4025
Note that we can't add `view` to concat/facet/repeat yet due to https://github.com/vega/vega/issues/1523
Also:
- Remove redundant `assembleLayoutSize` in `unit.ts`
- Update & improve docs
=> Add `view` as a property for Layer and Unit specs for customizing view background

build/vega-lite-schema.json, examples/compiled/trellis_barley.vg.json, examples/compiled/trellis_barley_layer_median.vg.json, examples/compiled/window_top_k.vg.json, src/compile/data/facet.ts, src/compile/data/windowfacet.ts, src/compile/facet.ts, src/compile/scale/domain.ts, src/sort.ts, test/compile/data/facet.test.ts, test/compile/scale/domain.test.ts
Fix https://github.com/vega/vega-lite/issues/1489
I think this will resolve a common error that many novice users run into.  While this may introduce a slightly different problem (namely that people may not specify op: 'mean' even when they want to), I think the benefits outweight the cons in this case. 
FWIW, the lack of default sort op has confused so many users already.
=> Make sort op optional and make `"mean"` the default op

site/docs/selection/selection.md
https://vega.github.io/vega-lite/docs/selection.html select dropdown is broken due to newline between html content in markdown. This patch removes it.
=> BUG: Selection dropdown html is broken

examples/compiled/facet_independent_scale.vg.json, examples/compiled/facet_independent_scale_layer_broken.vg.json, src/compile/facet.ts, test/compile/facet.test.ts
```json
{
"$schema": "https://vega.github.io/schema/vega-lite/v3.json",
"facet": {
"row": {"field": "Cylinders","type": "ordinal"}
},
"spec": {
"mark": "bar",
"encoding": {    
"y": {"field": "Origin","type": "ordinal"},
"x": {"aggregate": "count","type": "quantitative"}
}
},
"resolve": {
"scale": {
"y": "independent"
}
}
}
```
```json
{
"$schema": "https://vega.github.io/schema/vega-lite/v3.json",
"facet": {
"column": {"field": "Cylinders","type": "ordinal"}
},
"spec": {
"mark": "bar",
"encoding": {    
"x": {"field": "Origin","type": "ordinal"},
"y": {"aggregate": "count","type": "quantitative"}
}
},
"resolve": {
"scale": {
"x": "independent"
}
}
}
```
@jheer this should make the layout in your example from today …
=> Do not align when scales are independent

build/vega-lite-schema.json, scripts/rename-schema.sh, src/encoding.ts, src/fielddef.ts, src/normalize.ts, src/spec/facet.ts, src/spec/layer.ts, src/spec/unit.ts
so that the output JSON schema does not have duplicate (with `Field` and `string | RepeatRef`)
=> Consistently re-use <Field> rather than <string|RepeatRef>

examples/specs/bar_swap_custom.vl.json, site/tutorials/getting_started.md
The default title for average aggregate was `MEAN(b)`. Now it's `Average of b`. With the new title, the [Customize your Visualization section](https://vega.github.io/vega-lite/tutorials/getting_started.html#customize-your-visualization) needs to be updated.
Before:
After:
With `yarn test`, `toggle.test.ts` fails. But it also fails at head, so I assume I can ignore.
=> Fix Customize your Visualization section of tutorial

build/vega-lite-schema.json, package.json, scripts/check-schema.sh, scripts/rename-schema.sh, src/channel.ts, src/compile/mark/mark.ts, src/compositemark/boxplot.ts, src/compositemark/common.ts, src/compositemark/errorband.ts, src/compositemark/errorbar.ts, src/compositemark/index.ts, src/encoding.ts, src/mark.ts, src/normalize.ts, src/spec/index.ts, src/spec/layer.ts, src/spec/unit.ts, src/validate.ts, test/compositemark/errorbar.test.ts
This PR simplifies #4440 and keep the number of `Encoding` declarations small. 
In the schema, there are still simply `FacetedEncoding` and `Encoding`.
=> Don't include extra encoding for composite mark in the main `Encoding`

src/util.ts
This change addresses the error from when running `tsc`:
> error TS1192: Module '"/.../node_modules/@types/clone/index"' has no default export.
=> fix: ts error clone import

build/vega-lite-schema.json, examples/compiled/facet_cross_independent_scale.vg.json, examples/compiled/trellis_cross_sort.vg.json, examples/compiled/trellis_cross_sort_array.vg.json, scripts/rename-schema.sh, src/channel.ts, src/compile/data/facet.ts, src/compile/facet.ts, src/compile/header/index.ts, src/compile/model.ts, src/compile/repeater.ts, src/compositemark/index.ts, src/encoding.ts, src/fielddef.ts, src/log.ts, src/normalize/core.ts, src/normalize/index.ts, src/spec/facet.ts, src/spec/index.ts, src/spec/layer.ts, src/spec/unit.ts, src/validate.ts, test/channel.test.ts, test/compile/data/facet.test.ts, test/compile/facet.test.ts, test/normalize/core.test.ts
This PR is already atomic :) 
Beyond this PR:
- shared axes for wrapped facet #4543
=> Facet Wrap MVP

site/docs/selection/selection.md
https://vega.github.io/vega-lite/docs/selection.html#conditional-encodings has a broken select dropdown.
Please:
=> Prevent <p> injection for select and/or

build/vega-lite-schema.json, src/compile/header/index.ts, src/compile/model.ts, src/header.ts, test/compile/header/index.test.ts
=> Redirect `titleAnchor` to the underlying `layout.titleBand` + Automatically adjusting titleAlign

src/index.ts
3% smaller build and we are not exposing the internals of Vega-Lite which we break from time to time. 
Fixes #4635
=> Remove exports

rollup.config.js
This makes sure #4679 and #4683 never happen again.
=>  Throw an error when we import node util or vega

build/vega-lite-schema.json, site/docs/mark/mark.md, src/compile/mark/mark.ts, src/mark.ts, src/util.ts
cc: @manzt 
Now 
```
mark: {type: 'line', order: null}
```
should work in addition to 
```
{
encoding: {
...,
order: {value: null}
}
}
```
=> Add `order` to mark definition and mark config

build/vega-lite-schema.json, src/axis.ts, src/compile/axis/config.ts, src/compile/axis/parse.ts
Note that I don't distinguish types for config.axis from config.axisX/Y even though orient doesn't make sense for the general axis because I don't want to make the schema too complicated, which in turn will make Altair APIs too complicated.
Also refactor getAxisConfig to use `...`. 
Fix #4648
cc: @evschen -- I was fixing similar things in header and found that this is quite easy for me to fix so I went ahead and fix it to save your time.
=> Add config.axisX/Y.orient

site/docs/composition/facet.md
`s/overrride/override/g`
`s/tou/you/g`
=> Fix typo in docstring

build/vega-lite-schema.json, src/channel.ts, src/compile/selection/parse.ts, src/compile/selection/transforms/project.ts, src/selection.ts, test/compile/selection/parse.test.ts
Addresses #4575. If no explicit projection is provided for a selection, it first looks to the initial value and _then_ uses the default configuration values. As before, the initial value first attempts to interpret initial value keys as encoding channels, and then as field names.
=> Infer selection projection from initial value if none given.

examples/specs/selection_bind_origin.vl.json
The text on https://vega.github.io/vega-lite/docs/bind.html
> With single selections, the bind property follows the form of Vega’s input element binding definition to establish a two-way binding between input elements and the selection. 
fails when 'select all' is done by clicking on the graph to unselect ie Japan.
Please:
=> Add null to make the accompanying text in sync

examples/compiled/concat_hover_filter.vg.json, examples/compiled/interactive_multi_line_tooltip.vg.json, src/compile/data/parse.ts
Add identifier only to unit/layer models that do not have layer parents
Fix #4788
Merge #4787 first
=> Avoid redundant identifier transforms 

README.md
The current logo sizing feels over large and aggressive to me. This PR updates vega/vega-lite to mirror the setup I have on vega/vega and vega/vega-lite-api, with a smaller logo placed in the upper-right corner.
Feel free to merge if you agree with the change, or delete if you don't!
=> Move VL logo to upper right corner of README.md

tsconfig.json
Even with VSCode using 3.4.1, it's still behaving weird. I think some of the plugins we use may not play nice with this mode yet
cc: @domoritz
=> Stop using `incremental` in tsconfig.json

build/vega-lite-schema.json, src/data.ts
Also consolidate the docs for `type` of `FormatType`
cc: @jheer
=> [Docs] Use default value format consistent with the rest of the language

build/vega-lite-schema.json, src/data.ts
Previously the `SequenceParams` type mistakenly had the documentation comment for `GraticuleParams`, which propagates out to the JSON schema. This PR adds a proper description for the sequence generator.
=> Fix documentation comment for sequence parameters.

examples/compiled/geo_custom_projection.vg.json, examples/compiled/geo_sphere.vg.json, src/compile/projection/assemble.ts, src/vega.schema.ts, test/compile/projection/assemble.test.ts
Changes:
- If a custom projection is specified with `scale` but not `translate`, emit a default `translate` property in the output Vega spec, set to one-half the `width` and `height` signals.
- Update unit tests.
=> Add default translate for scaled projection.

build/vega-lite-schema.json, examples/compiled/concat_hover.vg.json, examples/compiled/concat_hover_filter.vg.json, examples/compiled/interactive_bar_select_highlight.vg.json, examples/compiled/interactive_multi_line_label.vg.json, examples/compiled/interactive_multi_line_tooltip.vg.json, examples/compiled/interactive_paintbrush.vg.json, examples/compiled/interactive_paintbrush_color.vg.json, examples/compiled/interactive_paintbrush_color_nearest.vg.json, examples/compiled/interactive_paintbrush_simple_all.vg.json, examples/compiled/interactive_paintbrush_simple_none.vg.json, examples/compiled/selection_multi_condition.vg.json, examples/compiled/selection_type_single_mouseover.vg.json, examples/compiled/trellis_selections.vg.json, site/docs/selection/clear.md, src/compile/selection/parse.ts, src/compile/selection/transforms/clear.ts, src/selection.ts
This PR reverts to the original design of clearing selections: a `dblclick` event trigger. Switching to `clear: mouseout` when `on: mouseover` proved problematic for several reasons including making it difficult to support toggling multi selections on hover (#4879) and introducing a flickering behavior when using layered marks (#4306). 
Users can always opt _in_ to this behavior by specifying `clear: "mouseout"` manually as part of their specification. The `dblclick` default introduces the fewest conflicts.
=> Revert selection clear default to "dblclick".

src/compile/mark/mixins.ts
#4726 introduced a `reactiveGeom` flag to lookup tooltip values on `datum.datum` rather than `datum` for voronoi marks which use reactive geometry. This PR fixes one location that was missed in the original PR that caused the bug to recur in #4859.
=> Fix tooltip propagation for voronoi marks.

package.json
If the vega-lite source is in a directory that has a parent named "src" (in my case, `/opt/src/github/vega/vega-lite`), then the tests fail to run with the very inscrutable error:
```console
yarn run v1.15.2
$ jest test/ && npm run lint && npm run schema && jest examples/ && npm run test:runtime
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /opt/src/github/vega/vega-lite
1527 files checked.
testMatch:  - 0 matches
testPathIgnorePatterns: node_modules, /opt/src/github/vega/vega-lite/build, _site, src - 0 matches
testRegex: (/__tests__/.*|(\.|/)(test|spec))\.(jsx?|tsx?)$ - 117 matches
Pattern: test/ - 0 matches
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
shell returned 1 …
```
=> Qualify testPathIgnorePatterns

site/docs/encoding/scale.md
The `continuousPadding` scale config option referenced in the [definition of the `padding` option for continuous scales](https://vega.github.io/vega-lite/docs/scale.html#continuous) is not listed in the table of scale config padding options. I'm not sure this change will resolve the issue as I'm not familiar enough with this repo to trace down the `ScaleConfig` referenced in the include template directive.
=> Include continuousPadding in scale config

site/docs/mark/line.md
with existing anchor reference to the relevant table in the section.
=> [docs] replace non-existing interpolate property reference

src/compile/selection/interval.ts, test/compile/selection/interval.test.ts
Fixes #4951 -- our selection-signal generation code was robust to channel and field names colliding, but the brush marks for interval selections still referred to hardcoded signal names. This PR fixes the issue by referencing signal names stored on the `SelectionProjection`.
=> Interval brush marks should read signal names from projection.

_data/link.yml, build/vega-lite-schema.json, scripts/rename-schema.sh, src/bin.ts, src/channeldef.ts, src/compositemark/common.ts, src/compositemark/errorbar.ts, src/encoding.ts, src/spec/facet.ts, src/transform.ts, test/compile/mark/bar.test.ts
- Remove non-null `bin` from `SecondaryFieldDef` / `LatLongFieldDef`
- Remove "binned" from `FacetFieldDef`
- Consolidate `ColorField/ValueDef` as `StringField/ValueDef`
- Consolidate `TextValueDef` as `ValueDef`
- `FieldDef` in the schema => `FieldDefWithoutScale`
=> [Fix Schema] 

build/vega-lite-schema.json, src/channeldef.ts, src/compile/data/bin.ts, src/compile/data/stack.ts, src/compile/mark/valueref.ts, src/data.ts, src/predicate.ts, src/scale.ts, src/selection.ts, src/sort.ts, src/transform.ts
This PR externalizes strings that semantically refer to field names as a new "`FieldName`" type. In the typescript, this is just an alias to `string`, but since it is a separate `definitions` type in the JSON schema, this can help third-party tools to identify when a field reference is being sought. For example, the editor (https://github.com/vega/editor) could use this field to try to auto-complete field names from the data set associated with the spec.
This is similar to how color names are externalized to a "Color" type (https://github.com/vega/vega-lite/pull/4228).
=> Add FieldName alias to string

examples/specs/rect_mosaic_labelled_with_offset.vl.json
Remove "type" field from "x2" and "y2" since they are disallowed by the schema, so this example schema is technically invalid.
=> Remove "type" field from "x2" and "y2" 

build/vega-lite-schema.json, src/compile/unit.ts, src/config.ts, src/normalize/pathoverlay.ts, src/stack.ts, test/compile/mark/line.test.ts, test/compile/mark/point.test.ts, test/compile/mark/rule.test.ts, test/compile/mark/text.test.ts, test/compile/mark/tick.test.ts, test/compile/scale/domain.test.ts, test/stack.test.ts
Fix #4823
(In hindsight, no one should want to make stack always center / normalized, so this property is useless. Plus, it's kinda out of nowhere.)
=> Remove unnecessary `config.stack`

src/compile/data/bin.ts, src/compile/scale/domain.ts, src/compile/scale/properties.ts, src/compile/scale/range.ts, test/compile/data/bin.test.ts
CC @kobben
We now support
```json
{
"data": {
"url": "https://kartoweb.itc.nl/Vega-Lite/data/overijssel_centroids.geo.json",
"format": {
"type": "json",
"property": "features"
}
},
"projection": {
"type": "stereographic"
},
"layer": [
{
"mark": "geoshape",
"encoding": {
"color": {
"bin": true,
"field": "properties.bev_dichth",
"type": "quantitative"
}
}
}
]
}
```
=> Use common logic for naming bin signals

build/vega-lite-schema.json, src/channeldef.ts, src/compile/scale/parse.ts, src/compile/unit.ts
This simplifies our JSON schema, but we need to add `minProperties` support to the schema generator for this to remain correct. 
cc: @domoritz
=> Merge `ValueDefWithOptionalCondition` as a variant of `ConditionOnlyDef<F>`, but use minProperties = 1 instead

src/compile/common.ts, src/compile/data/joinaggregate.ts, src/compile/data/stack.ts, src/compile/data/window.ts, src/vega.schema.ts, test/compile/data/joinaggregate.test.ts, test/compile/data/stack.test.ts, test/compile/data/window.test.ts
As is, the dependentFields() method in JoinAggregateNode, StackNode, and WindowNode attempt to iterate over optional fields resulting in exceptions when these fields aren't defined. This PR fixes this by checking to see if these fields are defined before iterating over them, and adds relevant tests.
=> Fix dependentFields calculation for JoinAggregate, Stack, and Window nodes

build/vega-lite-schema.json, src/channel.ts, src/compile/mark/valueref.ts, src/encoding.ts, src/vega.schema.ts
Previously it only worked in encoding value
Here is a toy example that it works now.  (I remember having to use it another day but it didn't work.)
=> fix:  make "width" / "height" work as value in mark definition

src/channeldef.ts, src/compile/common.ts, src/compile/legend/parse.ts, test/compile/common.test.ts, test/compile/mark/mixins.test.ts
Fixes #5063.
This means that we will automatically treat ordinal and nominal as numbers when a format is present. I think that's a reasonable thing to do.
=> fix: support formatting of discrete headers.

site/docs/projection.md
Change the spelling of `azimuthalEquidistanct` to `azimuthalEquidistant` in the documentation of Projection.
=> docs: spelling mistake

build/vega-lite-schema.json, site/docs/encoding/scale.md, src/compile/scale/properties.ts, src/scale.ts
These are unnecessary properties. (I don't see why one would use them.)  Removing them will  simplify the logic and related documentation. 
BREAKING CHANGE: remove `config.scale.bar/rectBandPaddingOuter`
=> fix!: remove `config.scale.bar/rectBandPaddingOuter` 

build/vega-lite-schema.json, examples/specs/point_invalid_color.vl.json, site/docs/config.md, site/docs/mark/mark.md, src/compile/common.ts, src/compile/data/filterinvalid.ts, src/compile/mark/mixins.ts, src/config.ts, src/mark.ts, test/compile/data/filterinvalid.test.ts, test/compile/mark/point.test.ts, test/compile/mark/rule.test.ts, test/compile/mark/text.test.ts, test/compile/selection/layers.test.ts, test/compile/selection/timeunit.test.ts, test/transformextract.test.ts
This would allow us to customize how we handle null values differently for different marks
Fix #4802
BREAKING CHANGE: `config.invalidValues` no longer works
=> feat!: replace `config.invalidValues` with `mark.invalid` for mark definition and config

src/channel.ts, src/compile/data/timeunit.ts, src/encoding.ts, src/normalize/ruleforrangedline.ts
```
{
"$schema": "https://vega.github.io/schema/vega-lite/v3.json",
"data": {
"values": [
{"bin_start": 8, "bin_end": 10, "count": 7},
{"bin_start": 10, "bin_end": 12, "count": 29},
{"bin_start": 12, "bin_end": 14, "count": 71},
{"bin_start": 14, "bin_end": 16, "count": 127},
{"bin_start": 16, "bin_end": 18, "count": 94},
{"bin_start": 18, "bin_end": 20, "count": 54},
{"bin_start": 20, "bin_end": 22, "count": 17},
{"bin_start": 22, "bin_end": 24, "count": 5}
] 
},  
"mark": "line", 
"encoding": {
"x": {  
"field": "bin_start",
"bin": {
"binned": true,
"step": 2
},
"type": "quantitative"
},
"x2": {"field": "bin_end"},
"y": {
"field": "count",
"type": "quantitative"
}
}
}
```
now works
=> fix + refactor

src/encoding.ts, test/encoding.test.ts
So it's consistent with how we normally do it for internal transforms
=> fix: reorder groupby output for `extractTransformInEncoding`

src/compile/layoutsize/init.ts, src/compile/scale/parse.ts, src/compile/scale/range.ts, src/log/message.ts, src/scale.ts, test/compile/compile.test.ts, test/compile/layoutsize/init.test.ts, test/compile/scale/range.test.ts, test/util.ts
The `parseRangeForChannel` method signature is quite nightmarish, so I simplify it to take just channel and model instead. 
Merge #5138 first
=> refactor: simplify scale range parameters and tests

site/docs/transform/impute.md
Missed some properties of `impute` in the impute transform docs.
=> Add missing properties of impute transform

src/compile/data/optimizers.ts, test/compile/data/optimize.test.ts, test/compile/data/optimizers.test.ts
We had a potential bug where we may ignore a field because it has a conflict but then add it back again.
=> fix: parse optimizer should keep track of conflicting fields

build/vega-lite-schema.json, src/projection.ts, src/vega.schema.ts
=> fix: correct projection `precision`'s type to number (not string)

src/compile/data/stack.ts, test/compile/data/stack.test.ts
This is especially important for temporal in a follow up PR (#5096).
=> fix: use `0.5*a + 0.5*b` for stack mid formula instead of `(a+b)/2` to avoid overflow

build/vega-lite-schema.json, site/docs/view/size.md, src/channel.ts, src/compile/buildmodel.ts, src/compile/compile.ts, src/compile/concat.ts, src/compile/facet.ts, src/compile/layer.ts, src/compile/layoutsize/init.ts, src/compile/layoutsize/parse.ts, src/compile/model.ts, src/compile/repeat.ts, src/compile/scale/range.ts, src/compile/unit.ts, src/log/message.ts, src/spec/toplevel.ts, test/compile/compile.test.ts, test/compile/layoutsize/init.test.ts, test/compile/scale/range.test.ts, test/util.ts
=> Implement fit-x and fit-y

src/log/message.ts, test/compile/scale/parse.test.ts
* Use sentences that end in .
* Single space between sentences.
=> refactor: consistent error messages

examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_not_aggregate_normalized.vl.json, examples/specs/normalized/layer_boxplot_circle_normalized.vl.json, src/compile/mark/init.ts, src/compositemark/boxplot.ts, test/compile/mark/init.test.ts, test/compositemark/boxplot.test.ts
fixes #5263, fixes #4849
Also detect the orientation of bar marks from aggregation.
=>  fix: set orient of bar in boxpolot macro

site/docs/projection.md
The plural should be "projections", not "projection's"
=> docs: correct pluralization and capitalization typos

src/compile/selection/transforms/scales.ts, test/compile/selection/scales.test.ts
Fixes #4975 which was caused by overriding the top-level signal expression when a scale-bound selection was projected over multiple fields.
=> fix: bug with top-level signal for scale-bound selection

src/compile/buildmodel.ts, src/compile/layer.ts, src/log/message.ts, src/spec/map.ts, test/normalize/core.test.ts
Motivation: a user has a typo in the syntax and was a bit shocked to see just  "Invalid spec" error, which isn't very helpful.
=> fix: improve invalid spec error message

build/vega-lite-schema.json, src/selection.ts, test/compile/selection/multi.test.ts, test/compile/selection/parse.test.ts
This will reduce confusion and propensity for users to adopt a short hand initialization scheme until such a time that we support columnar initialization (#4766, #5199, #5298).
/cc @gordonwoodhull
=> fix!: drop SelectionInitMapping as a possible type for multi selection init.

examples/compiled/interactive_brush.vg.json, examples/compiled/interactive_query_widgets.vg.json, examples/compiled/selection_clear_brush.vg.json, src/compile/selection/assemble.ts, src/compile/selection/index.ts, src/compile/selection/interval.ts, src/datetime.ts, test/compile/selection/multi.test.ts, test/compile/selection/single.test.ts, test/datetime.test.ts
Fixes #5199, which revealed several minor bugs:
1. Now that initial values for selections are embedded directly as dataset values (rather than embedded in signal expressions), we no longer need to string escape model names. 
2. Datetime expressions should evaluate to numerical timestamps, rather than strings. 
3. Vega's `modify` expression should also test for object equality (which wasn't previously necessary for our logic because the same object was being reused in every tuple and thus strict equality testing `===` would correctly evaluate to `true`). vega/vega#1909.
4. ~~Although the typings/schema disallow it (and I believe should continue to disallow it, for simplicity/disambiguity), when a multi selection is projected over a single field, it is reasonable to expect people to use a …
=> fix: toggling initialized values from multi selections 

examples/compiled/interactive_query_widgets.vg.json, examples/compiled/selection_bind_cylyr.vg.json, examples/compiled/selection_bind_origin.vg.json, examples/compiled/trellis_selections.vg.json, site/docs/selection/bind.md, src/compile/selection/assemble.ts, src/compile/selection/multi.ts, src/compile/selection/parse.ts, src/compile/selection/transforms/clear.ts, src/compile/selection/transforms/inputs.ts, src/compile/selection/transforms/project.ts, src/compile/selection/transforms/scales.ts, src/compile/selection/transforms/transforms.ts, test/compile/selection/clear.test.ts, test/compile/selection/inputs.test.ts
As per #4936 and altair-viz/altair#1553, our previous default of leaving direct manipulation interaction enabled for selections bound to input widgets was confusing to users. This PR switches the default such that direct manipulation interaction is disabled by default, but users may choose to explicitly re-enable it by specifying an `on` or `clear` properties.
=> feat!: by default, disable direct manipulation for widget-bound selections.

src/compile/mark/mark.ts, test/compile/mark/mark.test.ts
(See https://observablehq.com/d/f1ada87d23956054 -- the right way to use key is to specify the field name directly)
=> fix: correct key output

build/vega-lite-schema.json, src/vega.schema.ts
This seems to be a typo. We may want to consider porting the fix back to the 3.2 branch, since the schema is incorrect there as well.
=> fix: property `y2` should accept `height` not `width`

site/docs/projection.md
This adds the `equalEarth` projection to the `projection.md` [file](https://github.com/mattijn/vega-lite/blob/master/site/docs/projection.md). 
I cannot find any other place where there is made a reference to the projection types. So I guess it should be fine like this.
=> docs: include equalEarth in the projection.md

src/compile/selection/transforms/project.ts, src/log/message.ts
We used to prevent scale-bound selections from being initialized (users instead would have to explicitly define scale domains to initialize these type of selections). This is because selections used to be initialized via signals (#4139), which would populate the selection store on the second pulse and thus would not be ready in time for scale initialization. However, after switching selection initialization to happen directly in the store (#4943), this limitation no longer exists and scale-bound selections can be initialized directly rather than via the scale domain workaround.
Closes #5319.
=> feat: enable initialization of scale-bound selections.

build/vega-lite-schema.json, src/bin.ts, src/channeldef.ts, src/datetime.ts, src/header.ts, src/impute.ts, src/mark.ts, src/resolve.ts, src/selection.ts, src/stack.ts, src/transform.ts
- Format string values as `"foo"`
- Format other values that are valid JSON or code as `foo`
=> docs: more consistent formatting of values

src/compile/data/formatparse.ts, src/compile/data/parse.ts, src/compile/selection/assemble.ts, src/compile/selection/index.ts, src/compile/selection/multi.ts, src/compile/selection/transforms/inputs.ts, src/compile/selection/transforms/project.ts, src/compile/selection/transforms/scales.ts, test/compile/data/formatparse.test.ts, test/compile/selection/inputs.test.ts, test/compile/selection/multi.test.ts, test/compile/selection/parse.test.ts, test/compile/selection/scales.test.ts, test/compile/selection/single.test.ts
Fields are only flattened if they participate in encoding rules. Thus, we continue to use bracket notation to access datum values in signal expressions as we cannot be guaranteed that the flattened field will be present. However, the field name stored as part of a SelectionProjection will *always* use dot notation as these names are either returned to us flattened by `model.vgField` or users explicitly specify them in the input spec (in which case, dot notation is their only recourse). Thus, when referencing the field via a selection's top-level signal, we just directly access the flattened field name, rather than unpacking it via bracket notation.
Fixes #5334.
=> fix: correct references to flattened fields in selection signals.

examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_not_aggregate_normalized.vl.json, src/compositemark/boxplot.ts, src/compositemark/common.ts
Part of https://github.com/vega/vega-lite/issues/5407
The remaining issue is that `axis: null` won't get merged across layer -- see [this example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESGPQBPZEbMBtUAh3DCMAazNIdnQ-N2DIZCV4bk1GJWozIOD3AA9MjWz3djSzPCNWZDjCqAAzOzFNSIBJAFkAEQAhAH0AJR00jKrCyDwvQmRIgEdWdCU8Zn6qSALg1xX3L3zq93RqaiNhPAmcSGTWObV1+NHxqZm5hfmlq+cV14hXLJCYiJPysQmQwSSRSAy2wzy+iuOz2B1oR0iqGQs0u21q9UaJ1anV6-XSqO2IzGxyg01m810T0B0Kg6ByjFgZiUrDEYheQ3cyTE3D8+kgFHQYgqkQOjTW1UgsEYAC8SQYBUKSQBWd6rDTOAC6IFeQA).
=> fix: make composite mark preserve null `title`, `scale`, `axis`

examples/compiled/boxplot_1D_horizontal.vg.json, examples/compiled/boxplot_1D_horizontal_custom_mark.vg.json, examples/compiled/boxplot_1D_horizontal_explicit.vg.json, examples/compiled/boxplot_1D_vertical.vg.json, examples/compiled/boxplot_2D_horizontal.vg.json, examples/compiled/boxplot_2D_horizontal_color_size.vg.json, examples/compiled/boxplot_2D_vertical.vg.json, examples/compiled/boxplot_minmax_2D_horizontal.vg.json, examples/compiled/boxplot_minmax_2D_horizontal_custom_midtick_color.vg.json, examples/compiled/boxplot_minmax_2D_vertical.vg.json, examples/compiled/boxplot_tooltip_aggregate.vg.json, examples/compiled/boxplot_tooltip_not_aggregate.vg.json, examples/compiled/layer_boxplot_circle.vg.json, examples/specs/normalized/boxplot_1D_horizontal_custom_mark_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_explicit_normalized.vl.json, examples/specs/normalized/boxplot_1D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_1D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_color_size_normalized.vl.json, examples/specs/normalized/boxplot_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_custom_midtick_color_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_horizontal_normalized.vl.json, examples/specs/normalized/boxplot_minmax_2D_vertical_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_aggregate_normalized.vl.json, examples/specs/normalized/boxplot_tooltip_not_aggregate_normalized.vl.json, examples/specs/normalized/layer_boxplot_circle_normalized.vl.json, src/compositemark/boxplot.ts, test/compositemark/boxplot.test.ts
This will help simplify the number of data sources in the Vega outputs
Part of https://github.com/vega/vega-lite/issues/5404
=> fix: do not generate unnecessary invalid filter for boxplots

CONTRIBUTING.md
<h1>Description</h1>
1. I have added a comma after the introductory phase <strong>Generally</strong>.
2. <strong>an issues</strong> was changed to <strong>issues</strong>.
3. The first letter of a proper noun should be capital always, hence I have changed <strong>github</strong> to <strong>Github</strong>.
4. I have removed <strong>a</strong> before the <strong>property tables</strong>.
5. The singular verb <strong>produces</strong> does not appear to agree with the plural subject <strong>systems</strong>. So <strong>produces</strong> was changed to <strong>produce</strong>.
6. space was added between <strong>comma</strong> and <strong>you.</strong>.
Thanks a lot!!!
=> docs: fix typographical errors

examples/compiled/interactive_area_brush.vg.json, src/compile/data/optimizers.ts, test/compile/selection/timeunit.test.ts, test/transformextract.test.ts
I suspect this will resolve several of the bugs with selections projected over time units. 
The `RemoveDuplicateTimeNode` optimizer is a `BottomUpOptimizer` but, as previously written, would preserve the bottom-most time unit node and consider ones further upstream to be duplicates. As a result, you would get weird orderings like the one found in [interactive_area_brush](https://vega.github.io/editor/#/examples/vega-lite/interactive_area_brush) where the selection filter would come _before_ the time unit it depends on:
```json
"transform": [
{
"type": "filter",
"expr": "!(length(data(\"brush_store\"))) || (vlSelectionTest(\"brush_store\", datum))"
},
{
"type": "formula",
"as": "yearmonth_date",
"expr": "datetime(year(datum[\"date\"]), month(datum[\"date\"]), 1, 0, 0, 0, 0)"
}
```
With the …
=> fix: optimizer DuplicateTimeNode should remove bottom-most node first

codecov.yml
Temporarily enable coverage comments so that we see coverage even if we have updates to the schema or examples.
=> ci: enable coverage comment

examples/compiled/airport_connections.vg.json, examples/compiled/interactive_multi_line_label.vg.json, examples/compiled/interactive_paintbrush.vg.json, examples/compiled/interactive_paintbrush_color_nearest.vg.json, examples/compiled/interactive_stocks_nearest_index.vg.json, examples/compiled/selection_multi_condition.vg.json, examples/compiled/trellis_selections.vg.json, src/compile/selection/transforms/nearest.ts, test/compile/selection/nearest.test.ts
The `nearest` selection transform adds a voronoi tessellation that completely covers a group mark's data rectangle. However, it seems like events originating on the group mark still fire on the bottom and right edges of the group/voronoi mark (see vega/vega#2112) which can cause odd flickering issues (which I observed when working on the interactive index chart, #5286)
This PR resolves this issue by updating the `nearest` transform to scope events to the voronoi mark it adds.
=> fix: scope events to voronoi mark to prevent misfires from group

package.json, src/bin.ts, src/projection.ts, src/spec/facet.ts, src/spec/repeat.ts, src/transform.ts, yarn.lock
Needed for https://github.com/jupyterlab/jupyterlab/pull/7428.
cc @jasongrout
=> fix: ensure compatibility with TS 3.7

site/docs/selection/init.md
"Initialzing" -> "Initializing" in the title.
=> docs: fix typo in "Initializing a Selection" title

src/compile/data/debug.ts, src/compile/data/optimize.ts, src/compile/data/optimizers.ts, src/compile/data/parse.ts, src/compile/selection/index.ts, test/compile/data/graticule.test.ts, test/compile/data/sequence.test.ts, test/compile/selection/identifier.test.ts
Fixes #5512. Previously, we would try to add `IdentifierNodes` during parsing as needed (i.e., when the model tree contained a default discrete selection). However, this approach was quite brittle requiring [an ugly set of tests](https://github.com/vega/vega-lite/compare/as/identifierTransform?expand=1#diff-6ff9ac68ad5af5ba27bd1c51a6d58548L317) that would place the node _after_ forks thus not persisting the identifier field across derived datasets. 
Instead, in this PR, we _always_ add `IdentifierNodes` during parsing and then removing the unnecessary ones during optimization. Additional unit tests ensures correct behavior during multi-views and binning.
=> fix: always add IdentifierNode, remove unnecessaries during optimization

build/vega-lite-schema.json, src/axis.ts, tsconfig.json
This fixes #5477 with a one-line change in `axis.ts`
=> fix: axis typing for strictNullCheck

build/vega-lite-schema.json, src/vega.schema.ts
=> fix: support null as mark fill and stroke color

site/usage/ecosystem.md
Adds a link to ColorBrewer-Lite - a fork of the original ColorBrewer2 project - to the ecosystem page. ColorBrewer-Lite allows importing Vega-Lite specifications into ColorBrewer to pick one of the well-designed color schemes for a color encoding. ColorBrewer-Lite is part of a research project on visualization toolchaining (https://vis-au.github.io/toolchaining).
=> docs: add reference to ColorBrewer-Lite to ecosystem page

site/_data/examples.json
Fix https://github.com/vega/vega-lite/issues/5633
=> docs: add top examples for 4.0 to the gallery/editor

build/vega-lite-schema.json, site/_includes/docs_toc.md, site/docs/transform/lookup.md, src/compile/data/lookup.ts, src/transform.ts
This fix has a few benefits:
- make it possible to reference the object in the docs
- simplify output schema
- simplify output Altair classes (only one LookupTransform class)
Part of https://github.com/vega/vega-lite/issues/5634
cc: @arvind
=> fix: remove unnecessary division between Data/SelectionLookupTransform + docs SelectionLookup

src/timeunit.ts, test/timeunit.test.ts
There are a couple functions that are now unnecessary after the move to Vega time format.
=> chore: remove now unnecessary timeunit functions

site/docs/transform/regression.md
Existing formatting was unclear.
=> docs: fix regression formulas in doc pages

site/_includes/type.html
=> docs: fix docs for fixed length array (e.g., `[number, number]`)

src/axis.ts
(Conditional axis config is only in Vega-Lite, so the name was misleading.)
=> refactor: rename VgAxisConfigNoSignals to AxisConfigBaseWithConditional

site/docs/mark/rule.md
Thanks to @keckelt for flagging this issue on slack.
=> docs: fix references to examples

build/vega-lite-schema.json, examples/specs/normalized/trellis_barley_layer_median_normalized.vl.json, examples/specs/trellis_barley_layer_median.vl.json, src/compile/unit.ts, src/spec/base.ts, src/spec/index.ts, src/spec/layer.ts, src/spec/unit.ts, test/util.ts
(since it's a part of a common frame)
fix #5793
=> fix!: make layered unit specs not accept `width` and `height`

examples/compiled/stacked_bar_count_corner_radius_config.vg.json, examples/compiled/stacked_bar_count_corner_radius_mark.vg.json, examples/compiled/stacked_bar_count_corner_radius_mark_x.vg.json, examples/compiled/stacked_bar_count_corner_radius_stroke.vg.json, src/compile/mark/mark.ts
=> fix: make cornerRadius work for stacked bars with timeUnit

site/docs/encoding/field.md
This `repeat-ref` keyword  is [showing up in the docs](https://vega.github.io/vega-lite/docs/field.html):
As the number is in the code anyway, I thought it is safe to remove it but it is referenced in [vega-lite/site/_data/link.yml#L299-L300](https://github.com/keckelt/vega-lite/blob/e0c6eac22954d91dfe0061f73e927cd0a6d9e498/site/_data/link.yml#L299-L300) and I'm not really sure what that does.
I can remove the anchor there as well or change the code here so that the anchor works again (with a little help 😉  )
=> docs: fix {:#repeat-ref} anchor in field.md

site/docs/encoding/axis.md
Let's see if https://github.com/vega/vega/pull/2314 gets any edits before merging.
=> docs: add missing `index` property for expression in the axis docs

src/channeldef.ts, test/compile/scale/domain.test.ts
#5578 introduced a bug wherein an explicit scale domain would be incorrectly parsed when timeUnit was being used. PR includes a test to verify correctness.
=> fix: correct explicit domain when timeunit is used

build/vega-lite-schema.json, package.json, site/docs/config.md, src/config.ts, src/spec/base.ts, src/spec/unit.ts
Fix https://github.com/vega/vega-lite/issues/5854
=> fix: bring back width/height/view for unit specs inside layers (as deprecated)

scripts/version.sh
This PR addresses PR #3649 - an annoyingly slow `version.sh` script.
**Note:** This solution does *not* use `jq`, as the originating issue suggested.
The source of this slowness is actually the `npm list` command built-in to NPM, which is used by the script to extract the installed versions of various packages.
Unfortunately, the `npm list` command uses a package called `readPackageTree` to recursively walk the file tree in `node_modules`, inflate the various lockfile/shrinkwrap files possibly available, and produce a tree of package versions. Unfortunately, it does this *regardless* of any filters or depth parameters, which are applied *after* the tree is constructed. This means that performance of the command degrades as the number and depth of dependencies increases. At the time of …
=> perf: faster `version.sh`

build/vega-lite-schema.json, src/scale.ts
=> fix: accept arrays as range elements (for strokeDash)

src/compile/axis/parse.ts, test/compile/axis/parse.test.ts
The old code sometimes drop config when there is a default rule for undefined config value.
=> fix: correctly apply axis config

build/vega-lite-schema.json, src/header.ts
This is not particularly important, but it's super easy so I'd rather not leave it as a technical debt.
Note that since we manually map header groups, we mostly get these for free. :)
=> feat(experimental): support signal ref for most of header properties

build/vega-lite-schema.json, examples/compiled/interactive_dashboard_europe_pop.vg.json, src/sort.ts, test/compile/data/facet.test.ts, test/compile/scale/domain.test.ts
fixes #5951
Reverts https://github.com/vega/vega-lite/issues/5951
We already use min for other cases such as 
```json
{
"$schema": "https://vega.github.io/schema/vega-lite/v4.json",
"description": "A simple bar chart with embedded data.",
"data": {
"values": [
{"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
{"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
{"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
]
},
"mark": "bar",
"encoding": {
"x": {"field": "a", "type": "ordinal", "sort": "descending"},
"y": {"field": "b", "type": "quantitative"}
}
}
```
=> fix: change default sort op to min

src/axis.ts
=> fix: apply rounding to grid and ticks so they are aligned

src/compile/mark/init.ts, test/compile/mark/init.test.ts
fix https://github.com/vega/vega-lite/issues/5942
=> fix: make cornerRadiusEnd apply to all cornerRadius for ranged bars

src/channeldef.ts, src/compile/facet.ts, src/compile/mark/init.ts, src/compile/unit.ts, src/encoding.ts, test/channeldef.test.ts, test/compile/mark/init.test.ts, test/encoding.test.ts
We shouldn't call these normalizeXXX since we call them in init.
Some of the logic, perhaps could be moved to normalize at some point (but not in this PR). 
Until we perform such refactors, it's at least better to name based on when they are called. 
Merge https://github.com/vega/vega-lite/pull/5968 first
=> refactor: correctly name methods called in init

examples/compiled/concat_bar_scales_discretize_2_cols.vg.json, examples/compiled/concat_weather.vg.json, src/compile/concat.ts, src/compile/layoutsize/parse.ts, src/compile/model.ts, src/spec/base.ts, test/compile/concat.test.ts
Fixes https://github.com/vega/vega-lite/issues/6023
We now consistently treat a concat spec with 1 column as a vconcat.
=> refactor: remove concat type from concat model

src/compile/data/aggregate.ts, test/compile/data/aggregate.test.ts
Fixes https://github.com/vega/vega-lite/issues/6066
=> fix: escape paths in dimension fields

site/ecosystem.md
Added a new entry referring the vega_embed_flutter package which is flutter widget to embed vega-lite specs in flutter web pages.
=> docs: Adding a new tool for embedding vega-lite in flutter-web.

build/vega-lite-schema.json, site/docs/config.md, site/docs/encoding/axis.md, src/axis.ts, src/compile/axis/config.ts, src/compile/axis/parse.ts, test/compile/axis/parse.test.ts
Merge https://github.com/vega/vega-lite/pull/6082 first
=> feat: support axis config based on both orientation and type (e.g., `config.axisXTemporal`)	

examples/compiled/bar_diverging_stack_population_pyramid.vg.json, examples/compiled/geo_layer_line_london.vg.json, examples/compiled/rect_heatmap_weather.vg.json, examples/compiled/sequence_line_fold.vg.json, src/compile/legend/assemble.ts, test/compile/legend/parse.test.ts
Vega schema actually doesn't support null or empty string for title
=> fix: broken test for legend title

src/compile/mark/init.ts
=> fix: rule orientation for binned data (e.g., error bar for binned data)

src/compile/scale/range.ts, test/compile/scale/range.test.ts
fix #5501
This could be important for making a layer not using the whole width height.
Even if we have signals, users don't always know the width/height signal names in multi-view settings without looking at vega, so this will still be useful.
=> feat: support "width" / "height" in the range array

src/compile/axis/parse.ts
From a quick performance inspection, parse axis is the slowest part in the compilation process because of these unnecessary calls.
=> refactor(perf): don't compute labelAngle/orient when unnecessary

build/vega-lite-schema.json, src/channeldef.ts, src/header.ts, test/channeldef.test.ts
fix #4637
This would help with discoverability. Basically both axis and legend do have `orient`, so it would be consistent for header to have it too.
=> feat: support header `orient` as a shortcut for setting both labelOrient and titleOrient

scripts/build-example.sh
The console will now output
```
Compiling bar (~160 ms)
```
instead of 
```
Compiling bar
```
Note that `build:example` is much faster than building each example in the parallel version (`build:examples`)
=> chore: add timer (in ms) to build-example script, so we can benchmark

src/compile/axis/config.ts, src/compile/axis/parse.ts, src/compile/axis/properties.ts, test/compile/axis/properties.test.ts
This may reduce ~5% of compile time on my computer from a set of quick runs.
=> perf: avoid redundant axisConfigType calculation

src/mark.ts
so we can strong type the extraction logic with `Flag`
=> refactor: extract VLOnlyMarkConfig

site/docs/view/title.md
Added the following props to view/title.html spec page: align, dx, dy, lineHeight, and subtitle props
Fixes #6220
=> docs: add missing properties for title parameter object

src/compile/mark/encode/valueref.ts
fix band position for arc (fix #6238)
This also makes we output `band: 1` instead of `band: true`. 
Unfortunately, it's hard to isolate the change (I tried).
=> refactor: avoid unnecessary assignment

src/compile/axis/config.ts
In https://github.com/vega/vega-lite/pull/6278, I used Object.assign to merge the configs instead of looping through them for each property.
However, this means that the array order has to go from the lowest precedence to the highest precedence.
=> fix: correct precedence for axis config style

src/compile/mark/arc.ts, src/compile/mark/area.ts, src/compile/mark/bar.ts, src/compile/mark/encode/base.ts, src/compile/mark/geoshape.ts, src/compile/mark/image.ts, src/compile/mark/line.ts, src/compile/mark/point.ts, src/compile/mark/rect.ts, src/compile/mark/rule.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, test/compile/mark/arc.test.ts
=> fix: arc marks shouldn't output `theta`

build/vega-lite-schema.json, src/mark.ts
We shouldn't include them as it's introducing multiple ways to do the same thing.
Plus, startAngle and endAngle doesn't really mean anything. 
(It's just like x and x2, in that neither of them is strictly start nor end.) 
I'd argue that this isn't a breaking change since I intentionally didn't document them in https://vega.github.io/vega-lite/docs/arc.html
=> fix: hide startAngle/endAngle from mark def as they aren't necessary

build/vega-lite-schema.json, src/compile/legend/parse.ts, src/datetime.ts, test/transformextract.test.ts
merge https://github.com/vega/vega-lite/pull/6302 first
=> fix: don't include fill/strokeOpacity legends (unsupported by Vega)

src/compile/axis/properties.ts
so it's easier to write cases for signals
Re do of https://github.com/vega/vega-lite/pull/6309
The misleading check marks is really disrupting our flows:
=> refactor: consolidate labelAlign logic for x and y

src/compile/mark/encode/valueref.ts, src/mark.ts
=> fix: mark's offset properties should support signals

src/channeldef.ts, test/compile/scale/domain.test.ts
=> fix: support timestamp / month name in scale domain for single time unit

src/compile/mark/encode/position-range.ts, test/compile/mark/arc.test.ts
=> fix:  apply offset to both range positions when position2 is unspecified

site/docs/encoding.md, site/docs/encoding/scale.md
There are a couple links in the docs for [encoding](https://vega.github.io/vega-lite/docs/encoding.html) that are broken right now, namely [`position-datum-def`](https://vega.github.io/vega-lite/docs/encoding.html#mark-prop-datum-def) and [`position-field-def`](https://vega.github.io/vega-lite/docs/encoding.html#mark-prop-field-def). The cause is jekyll not handling multiple anchors for one heading, and the fix is to define one of the anchors using HTML like in `encoding/scale.md`.
In the process of making this change, I learned that the [`name` attribute is deprecated for `a` elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#name), so I replaced it with the `id` attribute as recommended.
I also found an anchor for `padding` which is no longer needed since [padding has …
=> docs: fix multiple anchors for same heading

src/scale.ts
Merge after #6354
See https://github.com/vega/vega-lite/pull/5913
=> refractor: remove use of namespaces

src/datetime.ts, src/timeunit.ts
* use loop instead of reduce for better readability
* remove need for `Record<SingleTimeUnit, string>`
* fix typos
=> refactor: improve time unit code

build/vega-lite-schema.json, src/channeldef.ts, src/compile/legend/encode.ts, src/compile/mark/encode/nonposition.ts, src/compile/mark/encode/valueref.ts, src/mark.ts, src/selection.ts, src/vega.schema.ts
`Value` should represent all possible values of `ValueDef`
(`ValueOrGradientOrText` sounds very funny)
=> refactor: simplify Value types

src/channeldef.ts, src/predicate.ts, test/predicate.test.ts
=> fix: remove unnecessary time() in expr for predicates

src/config.ts, test/config.test.ts
part of https://github.com/vega/vega-lite/issues/6404
=> fix: don't output tooltip: {content:'encoding'} in the config

build/vega-lite-schema.json, scripts/rename-schema.sh, site/_data/link.yml, site/docs/encoding.md, src/channeldef.ts, src/compile/mark/encode/conditional.ts, src/compile/mark/encode/text.ts, src/compile/mark/encode/valueref.ts, src/compositemark/common.ts, src/encoding.ts, test/compile/mark/encode/text.test.ts
fix #6433
Note that we'll still support conditional axis signal like this:
```
gridColor: {
condition: {
test: '<is major grid>',
signal: 'majorGridColor' // this can also be `value: "#ddd"`
},
signal: 'gridColor'  // this can also be `value: "#eee"`
}
```
=> fix: revise `encoding.color = {signal:...}` to be `{value: {signal:...}}`

src/config.ts, src/title.ts, test/config.test.ts
=> fix: correctly redirect align, baseline, dx, dy, and limit of config.title to config.style.group-subtitle

src/channeldef.ts, src/util.ts, test/compile/data/stack.test.ts
=> fix: unescape escaped fields in `as`

src/compile/model.ts
I believe the previous behavior was incorrect as the docs never said that we would remove titles when `config.aria=false`.
=> fix: don't remove titles from accessibility tree when config.aria is false

src/compile/format.ts, test/compile/axis/encode.test.ts
=> fix: don't pass undefined to custom formatting function when no format is provided

src/selection.ts
This is an attempt to explain how to achieve toggling without requiring the user to hold down the shift-key.
See the discussion in https://github.com/altair-viz/altair/issues/2151. I read and re-read this part of the documentation but couldn’t for the life of me figure out how to enable toggling without using a modifier key.
=> docs: explain how to achieve toggling without shift-key

src/compile/axis/assemble.ts, src/compile/axis/parse.ts, src/compile/data/bin.ts, src/compile/data/optimizers.ts, src/compile/data/source.ts, src/compile/data/timeunit.ts, src/compile/header/assemble.ts, src/compile/legend/encode.ts, src/compile/legend/parse.ts, src/compile/mark/encode/aria.ts, src/compile/model.ts, src/compile/selection/transforms/project.ts, src/config.ts, src/normalize/core.ts, src/normalize/rangestep.ts, src/util.ts, test/compile/model.test.ts
close #6519
Note that we do not support descriptions with signals for top-level descriptions. We also only use descriptions for views that create groups such as concatenated charts (i.e. not layered charts).
=> feat: use view descriptions for accessibility

bin/vl2pdf, bin/vl2png, bin/vl2svg
Fixes #5380
CLIs were assuming all data urls had a base of
/dev/ because of the passed argument and
https://github.com/vega/vega/blob/8fe8d36961c128df8300e6bc4fe6aac1e537bbe0/packages/vega-cli/src/render.js#L22
=> fix: don't pass /dev/stdin to vl scripts to fix issues with baseurl

build/vega-lite-schema.json, src/data.ts
The use of `Dict<unknown>` as an InlineDataset element would not allow the use of an interface to represent an array element. Reverting to `object`.
Note: I'm not able to run `yarn test` locally - is this because I'm using Windows?
=> fix: revert to object for inlineDataset element

src/compile/mark/mark.ts
I'm grouping different cases that call `getMarkGroups(model)` together
If we want to implement halo directly in Vega-Lite (see https://github.com/vega/vega/issues/2483), this might be helpful.
That said, right now I kinda feel like halo will be simpler to implement in Vega.
=> refactor: simplify parseMarkGroups

jest-puppeteer.config.js, package.json, yarn.lock
http-server uses an old version of ecstatic with https://github.com/advisories/GHSA-9q64-mpxx-87fg. This fixes the issue.
=> chore: switch to serve

.github/workflows/check.yml, .github/workflows/release.yml, .github/workflows/test.yml, src/index.ts
With this change, we are now building even automated commits so that we don't end up in a situation where we miss that a test failed but not in the last commit.
=> ci: use pat to build automated commits

src/compositemark/boxplot.ts, test/compositemark/boxplot.test.ts
Fix #4524 
Fix #4925
Boxplot did not include `bins` and `timeUnits` transform into `filteredLayersMixins`' transform. So, I included them.
=> fix: incorrect boxplot when using temporal field

build/vega-lite-schema.json, src/compositemark/errorbar.ts, test/compositemark/errorbar.test.ts, test/util.ts
Fix #6495 from the discussion in #6502 
- Drop size encoding in errorbar
- `mark.size` sets `mark.ticks.size` if `mark.ticks.size` is not specified
- `mark.thickness` sets:
- `mark.ticks.thickness` if `mark.ticks.thickness` is not specified
- `mark.rule.size` if `mark.rule.size` is not specified
=> fix: errorbar thickness and size

src/normalize/core.ts
Fix https://github.com/vega/vega-lite/issues/6762
The encoding: null now override parent encoding like expected:
=> fix: make encoding null override parent encoding

.github/workflows/test.yml, package.json, yarn.lock
We don't need the codecov token anymore.
=> ci: simplify code coverage

site/docs/composition/repeat.md
=> docs: document that repeat into layer does not stack or create a legend

src/compile/data/optimizers.ts
=> fix: do not error when there are unused source nodes

src/compile/axis/properties.ts, src/compile/legend/properties.ts, test/compile/axis/properties.test.ts, test/compile/legend/properties.test.ts
Closes #6934
* Set defaultLabelOverlap in Axis and Legend to "greedy" for symlog scale type
* Add corresponding tests
=> fix: set `defaultLabelOverlap` to "greedy" for symlog scale type

build/vega-lite-schema.json, src/mark.ts
Replaces https://github.com/vega/vega-lite/pull/6939
=> docs: fix documentation for mark text baseline #6939

.github/workflows/check.yml, .github/workflows/test.yml
it's actually faster without (or at least more predictable)
=> ci: remove caching

site/ecosystem.md
add Jekyll Diagrams & Liquid Diagrams to the ecosystem page.
=> docs: add Jekyll Diagrams & Liquid Diagrams to ecosystem

site/examples/index.md
I add a link to a collection of examples described below to the list of external examples on the website.
**Project description** 
This project is a port of the [BBC ggplot2 cookbook](https://bbc.github.io/rcookbook/) into Vega-Lite. This
makes use of the `gapminder` dataset which is included as a CSV in this
repository. The goal is to have useful examples of vega-lite specifications
recreating the main plots in the BBC cookbook. These /should/ be are easy to
reuse. If getting the last 20% of the visualisation to agree makes up 80% of the
code, then I will opt for only getting it 80% correct.
=> docs: add BBC Visual and Data Journalism cookbook port to examples page

src/channel.ts
Seems like this was just overlooked when channel type defs were changed, lemme know if I'm wrong.
=> fix: supportMark accepts ExtendedChannel

site/docs/transform/bin.md
I find this a bit unclear currently, and also often get asked what determines the actual number of bins. This PR is my understanding of https://observablehq.com/@d3/d3-bin, particularly this section:
> Unexpected? The result is not guaranteed to yield the exact number of buckets we asked for. That number is only an indication, passed to the threshold generator. As you change that value with the slider, you might notice the reason why this happens: the domain gets sliced at “nicely-rounded” values — using d3.ticks — and these rounded values do not fall exactly on the bin’s domain.
Also PRed in vega https://github.com/vega/vega/pull/2944
---
Please:
- For new …
=> docs: explain why there will be fewer bins than specified in `maxbins`

build/vega-lite-schema.json, src/channeldef.ts
=> fix!: latitude/longitude should not support valueDef

src/index.ts
To support webpack 5. See https://webpack.js.org/migrate/5/#cleanup-the-code.
=> refactor: export directly instead of importing first, don't export from package

build/vega-lite-schema.json, scripts/rename-schema.sh, src/compile/format.ts, src/compile/mark/encode/offset.ts, src/compile/mark/encode/position-range.ts, src/compile/mark/text.ts, src/compositemark/index.ts, src/normalize/base.ts, src/normalize/core.ts, src/normalize/index.ts, src/normalize/pathoverlay.ts, src/parameter.ts, src/predicate.ts, src/spec/index.ts, src/spec/layer.ts, src/spec/repeat.ts, src/spec/unit.ts, test/channeldef.test.ts, test/compile/facet.test.ts, test/compile/mark/encode/offset.test.ts, test/compositemark/errorbar.test.ts, test/config.test.ts, test/normalize/ruleforrangedline.test.ts, test/util.ts, tsconfig.build.json, tsconfig.json
fixes #6823
Needs https://github.com/vega/ts-json-schema-generator/pull/549
=> fix: remove normalized spec from schema

build/vega-lite-schema.json, src/channeldef.ts, src/guide.ts, src/header.ts
it wasn't supposed to be there in the first place
=> fix: remove labelExpr from formatters

site/docs/view/size.md
=> docs: document autosizing behavior

site/_layouts/plain.html, site/static/main.css
fix #7020
Note: I also need to adjust CSS so the menu is wide enough to say "Vega-Lite API".
=> docs: add link to vega-lite-api

build/vega-lite-schema.json, src/axis.ts
=> fix: correct axis schema to clarify which properties support expression

src/compile/selection/translate.ts, src/compile/selection/zoom.ts
=> fix: use correct expression functions to pan/zoom symlog scales

src/compile/selection/parse.ts, src/compile/selection/scales.ts, test/compile/selection/scales.test.ts
Fixes #6882. 
In #5351, we began to support flattened fields in selection signals. However, code review caught some good issues that were fixed in https://github.com/vega/vega-lite/pull/5351/commits/ea6f407d099ca9b15149111d31d71d5245a3f3a4 but weren't propagated through to the way scale bindings reference fields. This PR fixes that bug.
=> fix: correctly flatten nested field references for scale bindings

src/normalize/index.ts, src/normalize/selectioncompat.ts, test/normalize/selectioncompat.test.ts
In https://github.com/vega/vega-lite/pull/7114, we introduced a normalizer to automatically transition from the old selection syntax to the new selection parameters. Unfortunately, in te previous PR, this new normalizer incorrectly ran _after_ the core normalizer. As a result, it could not correctly transition selections for specs that were themselves normalized (e.g., those that use `row`/`column` or `line` marks with `"point": true`). 
This PR switches the order such that the selection compatibility normalizer runs _first_, with an corresponding unit test to ensure we correctly transition selections for generic/extended specs.
=> fix: selection compatibility normalizer should run first

src/compile/data/bin.ts, src/compile/scale/assemble.ts, src/compile/selection/assemble.ts, src/compile/selection/parse.ts, src/compile/selection/translate.ts, src/compile/selection/zoom.ts, test/compile/selection/scales.test.ts, test/compile/selection/translate.test.ts, test/compile/selection/zoom.test.ts
Fixes #5386, #5413, as well as an incomplete implementation of #7158.
=> fix: scale-bound selections should respect reversals

src/compile/axis/properties.ts
Before, any axis blocks would be dropped from the resulting Vega, including any
axis settings. After, mirror the behavior of ("bin":true) - axis settings cause
the axis block to be included.
This because I wanted grid lines to accompany my pre-binned data.
Test case:
```
{ "mark": "bar",
"encoding": {
"x": {
"type": "temporal",
"bin": "binned",
"field": "start",
"axis": {"grid": true}
},
"x2": {"field": "end"},
"y": {"type": "quantitative", "field": "value"}
},
"transform": [
{"calculate": "toDate(datum.day)", "as": "day"},
{"calculate": "timeOffset('hours', datum.day, -12)", "as": "start"},
{"calculate": "timeOffset('hours', datum.day, 12)", "as": "end"}
],
"height": 250,
"width": 800,
"$schema": "https://vega.github.io/schema/vega-lite/v4.json",
"data": {
"values": [
{"day": …
```
=> fix: allow axis settings when ("bin":"binned").

src/channeldef.ts, src/log/message.ts, src/scale.ts, test/compile/facet.test.ts, test/scale.test.ts
fixes #7167
In https://github.com/vega/vega-lite/pull/6201/files#diff-245098c24d290d1cd456956b3a74d688f56ec8a89e28ca9851ddd21067d8518aR828, we only allowed discretizing scales for stroke dash. This pull request also enables support for shape.
=> fix: support discretizing scales for shape

src/channeldef.ts, src/vega.schema.ts
Related to #6912.
When you consume `TopLevelSpec` like `import type { TopLevelSpec } from 'vega-lite';` in a project with `strictNullChecks` set to `true`, you'll run into the following error:
```
ERROR
node_modules/vega-lite/build/src/vega.schema.d.ts:34:19 - error TS2344: Type 'null' does not satisfy the constraint 'SignalRef | ExprRef'.
34     value?: Value<null>;
~~~~
Found 1 error.
```
The problem seems to be that the generic `ES` for the `Value` type doesn't include `null`. Changing that type to `Value<ES extends ExprRef | SignalRef | null = ExprRef | SignalRef | null>` fixes it.
An alternative would be to remove the `<null>` from the code that references `Value` since the type definition includes `ExprRef | SignalRef` as a default anyway.
Let me know which version would make more …
=> fix: Remove <null> from Value to fix TopLevelSpec consumed by code using strict mode.

scripts/build-example.sh
Since we do not need symlink to `examples/compiled/data` anymore, should we remove it?
=> chore: rebuild examples

site/docs/transform/bin.md
This fixes the "create a histogram" link in the Binning documentation (https://vega.github.io/vega-lite/docs/bin.html)
Before:
- https://vega.github.io/vega-lite/docs/bin.html#example
After:
- https://vega.github.io/vega-lite/docs/bin.html#histogram
=> fix(docs): point "create a histogram" link to proper id on Binning documentation

site/docs/parameter/select.md
This should fix the issue #7465 which is caused by the conflicting id's of the two dropdowns used with same id's in two different section.
=> docs: fix id's of translate and zoom selection

site/tutorials/getting_started.md
The anchor `type` no longer exists on /docs/encoding.html
The "Type" link on the "Encoding" page points to /docs/type.html.
Update this page to point to the same location.
=> fix: docs broken encoding type link

tsconfig.json
Fixes #7437
Undoes https://github.com/vega/vega-lite/pull/7266
=> fix: generate es2015 output

src/compile/data/parse.ts
=> fix: do not use ancestor parse when the model defines a new dataset

site/_includes/docs_toc.md, src/compile/model.ts, src/title.ts, test/config.test.ts, test/title.test.ts
Also rename nonMark(TitleProperties) to be clearer. 
fix #7434
=> fix: do not ignore config.title.angle/limit 

src/compile/mark/arc.ts, src/compile/mark/bar.ts, src/compile/mark/encode/index.ts, src/compile/mark/encode/position-rect.ts, src/compile/mark/image.ts, src/compile/mark/rect.ts, test/compile/mark/encode/position-rect.test.ts
This PR makes:
- rectBinPosition private and only requires a few parameters.
- also re-write related tests by calling the broader `rectPosition` -- the tests should be now much more understandable 
- remove unnecessary `mark` param from `rectPosition`.
=> refactor: rectBinPosition(), rectPosition()

.github/workflows/test.yml, test/compile/selection/parse.test.ts, test/compile/selection/scales.test.ts
Without these changes, `yarn tsc` fails. It also makes sense since only points selections have `fields`. I added a check to the CI to prevent this issue in the future.
=> chore: fix selection types in tests

site/docs/types.md
Seems like the title of this page should be "Property Types", not "Parameter Types". When I stumbled upon it, I initially confused it for a list of available (Vega Lite parameters)[https://vega.github.io/vega-lite/docs/parameter.html]. FWIW: A nearly [identical page in Vega's docs](https://vega.github.io/vega/docs/types/) is also currently titled "Parameter Types".
=> docs: fix types page title

site/ecosystem.md
This adds Datapane's GitHub repo to the ecosystem. I put it in "Tools for Authoring Vega-Lite Visualizations" section, based on the other similar libraries there, but let me know if this is not the appropriate category.
Thanks!
=> docs(ecosystem): add Datapane library to ecosystem

package.json, rollup.config.js, yarn.lock
This makes all the Vega libraries external by renaming their imports to `Vega`. This works because Vega exports all the library functions at the top-level as well (done in https://github.com/vega/vega/pull/3154).
This pull request also fixes an issue where imports for external dependencies (namely Vega-util) were not renamed to Vega.
This patch is needed to support importing Vega-Lite as a stand alone bundle. See https://github.com/altair-viz/altair/pull/2517.
=> feat: smaller bundles by making vega libraries external

examples/compiled/facet_bullet.vg.json, examples/compiled/interactive_multi_line_pivot_tooltip.vg.json, examples/compiled/interactive_seattle_weather.vg.json, src/compile/data/dataflow.ts
This PR closes #4680 and #5475.  It helps with part of #5261.
The root cause of the problem is within the [moveFacetDown map](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/optimize.ts#L98). 
The problem occurs because the `swapWithParent` method does not preserve the order of branches in the tree, so the main [map](https://github.com/vega/vega-lite/blob/ac00c92b01aa702be251d89d463f2df53e612e8b/src/compile/data/optimize.ts#L98) iterates incorrectly.  It expects to be able to iterate over each branch in turn, but when the order changes, this fails.
I have used the following spec to find the bug.
<details>
<summary>Example buggy spec</summary>
```
{
"$schema": "https://vega.github.io/schema/vega-lite/v5.json",
"data": {
"values": [
{ …
```
=> fix: preserve node order in swapWithParent

src/compositemark/index.ts, src/spec/base.ts, src/spec/index.ts, test/jest.overrides.ts, tsconfig.build.json, tsconfig.json
Fixes #7869 
This makes it easier to use vega-lite in NextJS TypeScript projects, since NextJS uses SWC/Babel which require isolatedModules
=> feat: support isolatedModules

site/ecosystem.md
I would like to add my new project [VegaFusion](https://vegafusion.io/) to the ecosystem page.
I noticed that a few related projects that focus on scaling Vega-Lite/Altair visualizations to larger datasets were not already present, so added a new section named "Tools for Scaling Vega-Lite Visualizations" with descriptions of `altair-transform` (cc @jakevdp) and `ibis-vega-transform` (cc @saulshanabrook) and VegaFusion.
Happy to add something on [Scalable Vega](https://github.com/vega/scalable-vega) if that makes sense, and to reorganize/reword as you see fit.  Thanks!
=> docs: add ecosysem section for tools that scale Vega-Lite

.github/workflows/check.yml, scripts/bump.sh, scripts/check-and-commit-toc.sh, scripts/check-and-commit.sh, scripts/deploy-schema.sh, site/_data/versions.yml
Paving the way for #7972 by reducing the amount of git commit related work that the release bot needs to do.
- Introduces the "skip ci" suffix for all the scripts that make commits in the `scripts/` folder. An exception was made for `bump.sh` since that is run locally. This is important to prevent the risk of infinite loops (if the auto job also creates commits, it can trigger itself if we're not careful).
- Removes `versions.yml` from git. It appears to me that it's already pushed into the `_site` folder by the release.yml file because
Documenting the call chain:
1. The docs site gets built by this Workflow step
https://github.com/vega/vega-lite/blob/4f349e3dd7227364852a7b69af6c15824b910fff/.github/workflows/release.yml#L47-L48 
2. Redirects …
=> chore: remove generating and tracking versions.yml from version control

src/stack.ts, test/stack.test.ts
Fixes https://github.com/vega/vega-lite/issues/7993
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.7997.cf7b1d6.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.7997.cf7b1d6.0
yarn add vega-lite@5.2.1--canary.7997.cf7b1d6.0
```
</details>
=> fix: do not stack non linear scales

scripts/check-and-commit-toc.sh, scripts/check-and-commit.sh
- Avoid making direct commits to the prerelease branch.
- See https://github.com/vega/vega-lite/commit/ae13aff7b480cf9c994031eca08a6b1720e01ab3#r67485453
- Updated autocommit logic + comments as a follow-up to #7984
=> ci: only run updates to schema and TOC on human feature request branches

.github/workflows/check.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, site/_layouts/docs.html, site/_layouts/plain.html, site/ecosystem.md, site/static/post.ts
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8031.0044b51.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8031.0044b51.0
yarn add vega-lite@5.2.1--canary.8031.0044b51.0
```
</details>
=> chore: update master to next in CI scripts and docs

scripts/check-and-commit-toc.sh, scripts/check-and-commit.sh, scripts/deploy-schema.sh
Otherwise we skip CI for commits coming from the CI: https://github.com/vega/vega-lite/pull/8088.
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8089.0345f00.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8089.0345f00.0
yarn add vega-lite@5.2.1--canary.8089.0345f00.0
```
</details>
=> ci: don't skip the ci when we have automatic commits

src/scale.ts
fixes #8137
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8140.8f29ddb.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8140.8f29ddb.0
yarn add vega-lite@5.2.1--canary.8140.8f29ddb.0
```
</details>
=> fix: log correct property name

site/ecosystem.md
- Improve discoverability of a tool I contributed to the Figjam ecosystem for improving collaboration between product designers and data analysts
- Added entry to `ecosystem.md`
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8050.b5e6c82.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8050.b5e6c82.0
yarn add vega-lite@5.2.1--canary.8050.b5e6c82.0
```
</details>
=> docs: add Graphpad to Vega-Lite ecosystem

.github/ISSUE_TEMPLATE/config.yml, .github/SUPPORT.md, site/index.md
fixes #8171
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8174.602fa71.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8174.602fa71.0
yarn add vega-lite@5.2.1--canary.8174.602fa71.0
```
</details>
=> chore: fix link to Vega slack

site/usage/compile.md
Just fixing a small typo in the examples in the docs on `compile`, I think this was just a typo originally that never got caught.
=> docs: `titleFormat` -> `fieldTitle` in compile docs

site/docs/config.md
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8212.924ee60.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8212.924ee60.0
yarn add vega-lite@5.2.1--canary.8212.924ee60.0
```
</details>
=> Clarify that we need to turn on `customFormatTypes` to use custom format types 

.github/workflows/publish-to-npm.yml
<details>
<summary>📦 Published PR as canary version: <code>5.2.1--canary.8242.8790c53.0</code></summary>
<br />
```bash
npm install vega-lite@5.2.1--canary.8242.8790c53.0
yarn add vega-lite@5.2.1--canary.8242.8790c53.0
```
</details>
=> chore: publish script is not just for prereleases and canaries

src/compile/legend/encode.ts, test/compile/legend/encode.test.ts
Fixes a bug where the `numberFormat` function will run on non quantitative values.
<details>
<summary>📦 Published PR as canary version: <code>5.3.1--canary.8305.cda1c30.0</code></summary>
<br />
```bash
npm install vega-lite@5.3.1--canary.8305.cda1c30.0
yarn add vega-lite@5.3.1--canary.8305.cda1c30.0
```
</details>
=> Fix: check only run `config.numberFormat` on quantitative types

.github/workflows/publish-to-npm.yml, .github/workflows/release-docs-and-schema.yml, .github/workflows/test.yml
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.8328.0f7bd89.0</code></summary>
<br />
```bash
npm install vega-lite@5.4.1--canary.8328.0f7bd89.0
yarn add vega-lite@5.4.1--canary.8328.0f7bd89.0
```
</details>
=> ci: set up node before running yarn and use caching everywhere

examples/specs/bar_month_temporal.vl.json
Copy of https://github.com/vega/vega-lite/pull/8156
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.8352.4f8b2d8.0</code></summary>
<br />
```bash
npm install vega-lite@5.4.1--canary.8352.4f8b2d8.0
yarn add vega-lite@5.4.1--canary.8352.4f8b2d8.0
```
</details>
=> docs: Explicit temporal type

.github/workflows/publish-to-npm.yml, .github/workflows/release-docs-and-schema.yml, .github/workflows/test.yml, package.json
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.8355.8713057.0</code></summary>
<br />
```bash
npm install vega-lite@5.4.1--canary.8355.8713057.0
yarn add vega-lite@5.4.1--canary.8355.8713057.0
```
</details>
=> ci: simplify setup and use caching

site/ecosystem.md
Add [MarkText](https://github.com/marktext/marktext) to Vega-Lite ecosystem, a markdown editor support Vega-Lite to generate diagram.
=> docs: add MarkText to Vega-Lite ecosystem

.github/workflows/check-toc.yml, .github/workflows/check.yml, .github/workflows/merge-dependabot.yml, .github/workflows/publish-to-npm.yml, .github/workflows/release-docs-and-schema.yml, .github/workflows/test-docs.yml, .github/workflows/test.yml, scripts/check-and-commit-toc.sh, scripts/check-and-commit.sh
fixes #8326
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.8356.5b3a942.0</code></summary>
<br />
```bash
npm install vega-lite@5.4.1--canary.8356.5b3a942.0
yarn add vega-lite@5.4.1--canary.8356.5b3a942.0
```
</details>
=> ci: split scripts and refine triggers

.github/workflows/check-toc.yml, .github/workflows/check.yml, CONTRIBUTING.md
This PR is in relation to #8356. PRs on forked repos fail.
I believe this is related to: https://github.com/actions/checkout/issues/551.
<details>
<summary>📦 Published PR as canary version: <code>5.4.1--canary.8363.08df068.0</code></summary>
<br />
```bash
npm install vega-lite@5.4.1--canary.8363.08df068.0
yarn add vega-lite@5.4.1--canary.8363.08df068.0
```
</details>
=> ci: Use Pull Request Head Ref

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/check-toc.yml, .github/workflows/check.yml, .github/workflows/first-interaction.yml, CONTRIBUTING.md
Okay, after trying out #8363, #8365, and #8366, along with some ideas on my personal fork, I've come to the conclusion that switching the `Format, Schema, and Examples` CI to be on `push` rather than on `pull_request` is the best solution. The reason for this decision is the complexity between running the CI and committing changes on a target repository versus committing the changes to the PR branch. This would involve complex resolutions such as possibly `pull_request_target`, which has [security implications](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).
Therefore, this PR changes the contribution workflow so `check` will occur within the fork repository rather than on PR. We can add another CI to validate that the action ran successfully as well. …
=> ci: update contribution information

package.json
- Manual workaround for bug reported in https://github.com/vega/vega-lite/issues/8370#issuecomment-1223318989
- Manually increments package.json to the version that auto _would_ bump to when #8368 is merged
- No runtime impact
- Make sure not to merge this until we are able to merge #8368 immediately after.
=> chore(release): bump package.json version to v5.6.0

package.json
- https://github.com/vega/vega-lite/pull/8378 bumped us 1 patch version too high. 
- There may be a longer term fix, but at minimum we should clean up `next` so that this versioning issue doesn't block the release of core graphing features.
- Learned from https://github.com/vega/vega-lite/pull/8380 that we can't fix things by merging stable back into next since that creates a merge conflict. It seems that stable must lead in front of next, the reverse isn't possible.
- After this merges, the 5.6.0 release PR (https://github.com/vega/vega-lite/pull/8368 ) should no longer have a merge conflict.
=> fix: Set package.json version to 5.5.0 (re-sync with stable)

site/docs/encoding/scale.md
A very simple change that fixes a typo `therange` => `the range`.
=> docs: fix typo in 1:1 mapping caveat in scale documentation

site/docs/encoding/condition.md
=> docs: typo error

package.json, src/util.ts, yarn.lock
Supported since node 11
<details>
<summary>📦 Published PR as canary version: <code>5.6.0--canary.8434.91e1716.0</code></summary>
<br />
```bash
npm install vega-lite@5.6.0--canary.8434.91e1716.0
yarn add vega-lite@5.6.0--canary.8434.91e1716.0
```
</details>
=> feat: remove flatmap polyfill

src/channeldef.ts
=> fix: constrain `isConditionalParameter` type parameter

site/_data/examples.json, src/mark.ts
<details>
<summary>📦 Published PR as canary version: <code>5.6.1--canary.8592.fcbd150.0</code></summary>
<br />
```bash
npm install vega-lite@5.6.1--canary.8592.fcbd150.0
yarn add vega-lite@5.6.1--canary.8592.fcbd150.0
```
</details>
=> docs: correct link to docs instead of editor

site/ecosystem.md
* Scalene uses Vega-Lite for its visualizations in its (standard) web interface
* CSrankings uses Vega-Lite for bar charts / pie chart visualizations of faculty publication charts by area.
=> docs: add Scalene and CSrankings

site/docs/transform/window.md
I think this fixes the following although I can't test on my machine to be certain: https://github.com/vega/vega-lite/issues/8610
Also minor wording update.
=> docs: fix example in window.md

site/tutorials/explore.md
=> docs: tutorial references "temperature" when data is precipitation

site/_includes/docs_toc.md, site/ecosystem.md, src/channel.ts, src/compositemark/boxplot.ts, src/compositemark/errorband.ts, src/compositemark/errorbar.ts
<details>
<summary>📦 Published PR as canary version: <code>5.6.1--canary.8641.fe3f2dd.0</code></summary>
<br />
```bash
npm install vega-lite@5.6.1--canary.8641.fe3f2dd.0
yarn add vega-lite@5.6.1--canary.8641.fe3f2dd.0
```
</details>
=> docs: remove stars from some libraries on ecosystem page

site/static/main.css
I am trying to make the change shown for `0` in this screenshot, so that the text is not far below the sliders. I am not 100% sure this is the right css syntax so please double check
=> chore: align input sliders with numbers

src/compile/scale/domain.ts, test/compile/scale/domain.test.ts
Partially addresses https://github.com/vega/vega-lite/issues/5013
=> fix: correctly handle merging of domains with more than one sort object

src/normalize/toplevelselection.ts
Address one bug from #8348. 
<details>
<summary>📦 Published PR as canary version: <code>5.6.1--canary.8486.d7be769.0</code></summary>
<br />
```bash
npm install vega-lite@5.6.1--canary.8486.d7be769.0
yarn add vega-lite@5.6.1--canary.8486.d7be769.0
```
</details>
=> fix: prevent duplicate spec names in top-level selection view paths

src/compile/selection/legends.ts, test/compile/selection/legends.test.ts
Proposed fix for https://github.com/vega/vega-lite/issues/8143.
The problem this PR addresses is that when a boolean column is present in the legend, and a selection is bound to the legend, clicking on the `false` entry does nothing.
The problem is this expression:
```
datum.value || item().items[0].items[0].datum.value
```
When `datum.value` is falsy, it's value is never used. Instead, I think this expression should be
```
datum.value != null? datum.value: item().items[0].items[0].datum.value
```
so that the datum's value is used as long as it's not null or undefined.
---
Here is the result of this change for the repro in #8143
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZ …
=> fix: handle falsy legend values in selections

rollup.config.mjs, tsconfig.json
The defaults browserlists already doesn't include IE anymore. Also switching to es2020
=> feat: simplify rollup script and update to more modern js

src/compile/selection/legends.ts, test/compile/selection/legends.test.ts
Replacement for https://github.com/vega/vega-lite/pull/8800, which was reverted.  Fixes https://github.com/vega/vega-lite/issues/8143.
This implementation also handles `null` legend values by using the `isDefined` expression function.
=> fix: handle falsy legend values in selections (take 2)

site/docs/encoding.md
Current docs have a typo in the [Position Offset permalink](https://vega.github.io/vega-lite/docs/encoding.html#positon-offset). Fixing this to "position-offset" so the [reference here](https://github.com/vega/vega-lite/blob/309af9ac314b5c83ecf89afbda6069a63fd7a53e/site/docs/encoding.md?plain=1#L84) resolves properly.
=> docs: fix position-offset permalink in encoding.md

build/vega-lite-schema.json, package.json, src/compile/buildmodel.ts, src/compile/format.ts, src/compile/mark/encode/nonposition.ts, src/compile/mark/encode/offset.ts, src/compile/mark/encode/position-range.ts, src/compile/mark/encode/position-rect.ts, src/compile/mark/encode/valueref.ts, src/compile/mark/text.ts, src/compile/mark/tick.ts, src/compile/projection/parse.ts, src/compile/scale/component.ts, src/compile/scale/domain.ts, src/compile/scale/properties.ts, src/compile/signal.ts, src/normalize/base.ts, src/normalize/core.ts, src/normalize/index.ts, src/normalize/pathoverlay.ts, src/predicate.ts, src/selection.ts, test/channeldef.test.ts, test/compile/facet.test.ts, test/compile/mark/encode/offset.test.ts, test/compile/scale/domain.test.ts, test/config.test.ts, test/util.ts, tsconfig.json, yarn.lock
@arvind it looks like `fields` wasn't in interval selection configs but [the docs](https://vega.github.io/vega-lite/docs/selection.html) and tests say it's a shared config option. Does this look right to you that I moved `filelds`?
=> fix: update ts and fix typing issues

.github/dependabot.yml
Reduce update cadence.
To reduce even further, we can use [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) but this is the first step.
=> ci: monthly updates

examples/compiled/area_density_facet.vg.json, examples/compiled/area_density_stacked.vg.json, examples/compiled/area_density_stacked_fold.vg.json, src/compile/data/density.ts, test/compile/data/density.test.ts
Closes https://github.com/vega/vega-lite/issues/9078
=> fix: use resolve "shared" instead of steps to fix artifacts in grouped density transform

site/ecosystem.md
[Deneb.jl](https://github.com/brucala/Deneb.jl) adds support to Vega-Lite visualizations in the Julia language. It provides an [alternative to VegaLite.jl](https://brucala.github.io/Deneb.jl/dev/#Why-Deneb.jl?), trying to solve some of its problems while focusing on a consistent API inspired by python's Vega-Altair. 
It would be great if it gets added to the ecosystem page.
=> docs: add Deneb.jl to ecosystem

build/vega-lite-schema.json, src/scale.ts
Fix https://github.com/vega/vega-lite/issues/9130
Fix in correct types as discussed in https://github.com/vega/vega-lite/issues/9130
=> fix: correct types for domain unionWith

site/ecosystem.md
Sorry for the mistake that https://github.com/vega/vega-lite/pull/9144 is merged into `master`, which should be `main`.
=> docs: add pygwalker and gwalkr

README.md
The list is not up to date and I think it's best to link to the contributor page only. I don't mean to discount the contributions of anyone in that list but I think it should be much longer at this point and even longer in the future so to simplify things, I want to just link to the list that automatically updates. 
Once we have a governance model, we can link to how to become a contributor.
=> chore: update contributors in readme

site/ecosystem.md
Add [VegaLite](https://github.com/JoshDavid/VegaLite) to the VegaLite ecosystem, which is a plugin for the Dyalog APL programming language to build & render VegaLite visualizations. 
Related issue: https://github.com/JoshDavid/VegaLite/issues/9
=> docs: add APL plugin to ecosystem

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Enhancement.md, .github/PULL_REQUEST_TEMPLATE.md
As suggested by @arvind in https://github.com/vega/.github/pull/2#discussion_r1380801461
=> chore: simplify the templates

README.md
I was doing some research on which lib to use for visualizations in one of my side projects.
Stumbled upon Vega/Vega-Lite via https://github.com/altair-viz/altair and really liked what I saw in terms of the approach it takes to visualization.
When reading up on Vega-Lite, I noticed that this link in your README leads to an error message in the online editor: https://vega.github.io/editor/#/custom/vega-lite
This can be confusing, especially on mobile. I suggest swapping in a link to a simple example instead.
=> docs: link to valid bar chart example

src/compile/scale/range.ts
close #8754 
I found that the range for radius using width and height without checking if the model  is faceted
https://github.com/vega/vega-lite/blob/c33f46bad7f80f779e463a8a36481f888f18e222/src/compile/scale/range.ts#L311-L314
=> fix: use child signal for radius if faceted

jest.config.js
=> chore: replace outdated jest config style

.github/workflows/test.yml
=> ci: update codecov action so we don't use deprecated node 16

site/_layouts/plain.html
It's confusing that people can an immediate error when they click the link. 
Thanks @mkery for the suggestion.
=> docs: link to working example for "try online"

build/vega-lite-schema.json, src/compile/scale/range.ts, src/scale.ts
=> fix: support arrays in color schemes

build/vega-lite-schema.json, src/compile/mark/mark.ts, src/mark.ts, test/compile/mark/mark.test.ts
In Vega, [mark supports a signal for the `clip` property](https://vega.github.io/vega/docs/marks/#mark-clipping). To round out the Vega-Lite API, we should support it here as well, especially since it is trivial to add.
Tips:
=> feat: add support for signals in mark clip

src/compositemark/boxplot.ts, test/compositemark/boxplot.test.ts
This change ensures all field aliases are unescaped when generated. Before this change if a field was referenced like `"field": "one\\.two"` the boxplot code would generate calculated fields like `"as": "lower_box_one\\.two"`. This breaks downstream in the compiled Vega code which expects aliases to not include escape sequences.
As far as I could tell there is no issue open for this. The contributing.md doc explicitly calls out it is not necessary to open one, but I'm happy to do so if it helps.
=> fix: generate unescaped boxplot calculated field aliases

package.json, scripts/build-editor-preview.sh, src/index.ts
- A cloudflare-based take on https://github.com/vega/vega-lite/issues/9276
- As discussed w/ @domoritz, Previewing the editor site is probably more useful than the docs site, so we're going after that first
- Use explicit packageManager version so Cloudflare doesn't autoupgrade to yarn 3 (breaks lockfile)
- Add a build script (originally this was a 1-liner in package.json but it was getting hard to read) that
- Builds vega-lite
- Clones vega/editor and links the local vega-lite in place of the full build
- Install `vega/editor` without running the `prepare` script. (The CI device doesn't have rsync installed).
- Makes empty index.json for vega / vega-lite examples.
- Build editor with vite with `/` as the base URL (previously it was erroring due to thinking it was under the `/editor` …
=> build: Configure deployment previews with Vega Editor

scripts/build-editor-preview.sh
- Following https://github.com/vega/editor/pull/1420, https://github.com/vega/vega-lite/issues/9276 stopped working
- This updates the build command for compatibility with parcel.
- Updates stale comments
- Don't mention vite, try to stick to the yarn build command (with 1 parcel specific flag https://github.com/parcel-bundler/parcel/issues/206#issuecomment-350697310 )
- Check if deploy preview link loads correctly ( [src](https://cameron-yick-fix-deploy-prev.vega-lite.pages.dev/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AEEABBBoIcguIaZJ1h2DcyGA7nRiHETOMtXLDypJhUiioBKKigxEiCDGpoANqgYSD6wUxoAEwAHAC+ColoIABCqWhiYrn56ADCJagALADMFSBJACK1AJwAjM1JAKK1mT15LQUAYrViTSNJAOK1XR29BQASgwDsy+gAkpPp2QC6uSDI6gDWBdbqwXCyUGzKNLJkaKAAH …
=> build: switch bundler for deploy previews back to parcel

src/compile/data/aggregate.ts, test/compile/compile.test.ts
Fixes #6184.
When there are multiple elements in AggregateTransform with the same data field and aggregation operation, the code is currently only keeping the first output field name.
=> fix: for issue when there are multiple aggregates with the same data field and aggregation operation

site/docs/overview.md, site/docs/parameter/select.md
Fixes these links on https://vega.github.io/vega-lite/docs/:
> This documentation describes the [JSON specification language](https://vega.github.io/vega-lite/docs/#spec)
> ...
> - [Point Selection Properties](https://vega.github.io/vega-lite/docs/selection.html#point)
> - [Interval Selection Properties](https://vega.github.io/vega-lite/docs/selection.html#interval)
=> fix: links in docs

build/vega-lite-schema.json, src/compositemark/errorband.ts, src/compositemark/errorbar.ts
Minor clarification to the docs so that it is clear what type of CI is added. This info is available in the aggregation docs, but not in the docstring to the errorbar and errorband marks.
=> docs: Indicate what type of CI is made

src/compile/data/facet.ts, src/compile/selection/inputs.ts, src/compile/selection/interval.ts, src/compile/selection/translate.ts, src/compile/selection/zoom.ts, src/encoding.ts, src/timeunit.ts, src/util.ts
=> refactor: use optional chaining

site/static/index.ts
Clicking on `<a>` tags with the middle mouse button always opens them in a new tab.
Currently, they open `/docs.{page}.html#` since the href link and onclick link are different. 
<details>
<summary><h2>Checklist</h2></summary>
=> docs: middle mouse click opens editor example instead of docs in new tab

test/compile/selection/point.test.ts
- Assist w/ verifying the correct ESM update ( https://github.com/vega/vega/issues/3990 / https://github.com/vega/vega-lite/pull/9527)
- No functional change at runtime. 
- In test: make sure errors contain text relating to specific compiler error messages are thrown, rather than asserting _any_ error was thrown.
- Docs on Jest's toThrow [options](https://jestjs.io/docs/expect#tothrowerror)
- Our error is thrown by the [common logger](https://github.com/vega/vega-lite/blob/309e7b44165b21d84d53c29274676116d503713e/src/log/index.ts#L50)
=> test: Check error message contents when testing compiler for animated point selections

build/vega-lite-schema.json, src/legend.ts
Replaces https://github.com/vega/vega-lite/pull/9558
Fixes https://github.com/vega/vega-lite/issues/9524
=> fix: remove extra backtick in LegendConfig.labelOverlap documentation

package.json, src/compile/format.ts, src/spec/index.ts
Fixes #9583, fixes #9222
Simpler version of #9584
You can use this new feature to import types from arbitrary files. 
```ts
import type {TopLevelUnitSpec} from 'vega-lite/types_unstable/spec/unit.d.ts';
import type {Field} from 'vega-lite/types_unstable/channeldef.d.ts';
const spec: TopLevelUnitSpec<Field> = {
$schema: 'https://vega.github.io/schema/vega-lite/v5.json',
description: 'A simple bar chart with embedded data.',
data: {
values: [
{a: 'A', b: 28},
{a: 'B', b: 55},
{a: 'C', b: 43},
],
},
mark: 'bar',
encoding: {
x: {field: 'a', type: 'ordinal'},
y: {field: 'b', type: 'quantitative'},
},
};
```
=> feat: export types

README.md, site/_config.yml, site/index.md
Twitter is bad so replace links, add link to curriculum, remove mention of Vega-Lite 2
=> docs: update links and materials

site/ecosystem.md
- Keep `ecosystems.md` page up to date about commercial users of Wildcard Widget 
- (disclaimer: this is a project I worked on, Datadog is my employer).
- Adds Datadog's "Wildcard Widget" and "Custom Chart" to the set of tools that allow authoring Vega / Vega-lite specifications
- No impact on library runtime
- Any feedback on content or whether this went into the right section is welcome.
=> docs: Add Datadog Wildcard Widget + Custom Charts to the Ecosystems Page

examples/compiled/bar_simple_binned_timeunit_special_chars.vg.json, examples/compiled/time_output_utc_timeunit.vg.json, examples/compiled/time_parse_binnedutc.vg.json, examples/compiled/time_parse_utc.vg.json, src/compile/format.ts, test/compile/format.test.ts
Fixes https://github.com/vega/vega-lite/issues/7185
=> fix: ensure temporal field propagates to time expression

src/compile/mark/init.ts, src/normalize/pathoverlay.ts
Fixes https://github.com/vega/vega-lite/issues/9548
=> fix: do not set opacity in normalized marks for path overlays if it's set in the config

site/_data/examples.json
This PR deduplicates an example title in [examples.json](https://github.com/vega/vega-lite/blob/87bab0e88d555161748ac866428d8baaed157cb5/site/_data/examples.json) by updating the title of the `interactive_multi_line_pivot_tooltip` example to "Multi Series Line Chart with Tooltip via Pivot". Previously, both `interactive_multi_line_tooltip` and `interactive_multi_line_pivot_tooltip` shared the same title ("Multi Series Line Chart with Tooltip"). With this change, all example titles (which appear as the names of the examples on the example web site) within vega-lite are now unique, which will aid preparatory work in `vega/vega-datasets` to update the `README.md` to show which datasets are used in which vega/vega-lite/altair example galleries. Aside from this, the change also helps to …
=> fix: dedup example title
